/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2009 John-Mark Bell <jmb@netsurf-browser.org>
 */

#ifndef libcss_properties_h_
#define libcss_properties_h_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Property identifiers (opcodes)
 *
 * === AUTO-GENERATED - DO NOT EDIT ===
 * Property enum values are auto-generated from properties.toml.
 * See properties.toml for how to add new properties.
 */
enum css_properties_e {
#include "properties_enum.inc"

    CSS_N_PROPERTIES
};

/**
 * Special opcode for CSS custom property declarations (--name: value).
 * Defined outside the auto-generated enum so it doesn't affect
 * prop_dispatch[] indexing. Must be handled specially in cascade_style().
 *
 * Bytecode layout: [OPV] [name_string_idx] [value_string_idx]
 *   OPV uses CSS_PROP_CUSTOM_PROPERTY as the opcode.
 *   name_string_idx: index into stylesheet string_vector for the property name.
 *   value_string_idx: index into stylesheet string_vector for the raw value text.
 */
#define CSS_PROP_CUSTOM_PROPERTY CSS_N_PROPERTIES

enum css_align_content_e {
    CSS_ALIGN_CONTENT_INHERIT = 0x0,
    CSS_ALIGN_CONTENT_STRETCH = 0x1,
    CSS_ALIGN_CONTENT_FLEX_START = 0x2,
    CSS_ALIGN_CONTENT_FLEX_END = 0x3,
    CSS_ALIGN_CONTENT_CENTER = 0x4,
    CSS_ALIGN_CONTENT_SPACE_BETWEEN = 0x5,
    CSS_ALIGN_CONTENT_SPACE_AROUND = 0x6,
    CSS_ALIGN_CONTENT_SPACE_EVENLY = 0x7
};

enum css_align_items_e {
    CSS_ALIGN_ITEMS_INHERIT = 0x0,
    CSS_ALIGN_ITEMS_STRETCH = 0x1,
    CSS_ALIGN_ITEMS_FLEX_START = 0x2,
    CSS_ALIGN_ITEMS_FLEX_END = 0x3,
    CSS_ALIGN_ITEMS_CENTER = 0x4,
    CSS_ALIGN_ITEMS_BASELINE = 0x5
};

enum css_align_self_e {
    CSS_ALIGN_SELF_INHERIT = CSS_ALIGN_ITEMS_INHERIT,
    CSS_ALIGN_SELF_STRETCH = CSS_ALIGN_ITEMS_STRETCH,
    CSS_ALIGN_SELF_FLEX_START = CSS_ALIGN_ITEMS_FLEX_START,
    CSS_ALIGN_SELF_FLEX_END = CSS_ALIGN_ITEMS_FLEX_END,
    CSS_ALIGN_SELF_CENTER = CSS_ALIGN_ITEMS_CENTER,
    CSS_ALIGN_SELF_BASELINE = CSS_ALIGN_ITEMS_BASELINE,
    CSS_ALIGN_SELF_AUTO = 0x6
};

enum css_background_attachment_e {
    CSS_BACKGROUND_ATTACHMENT_INHERIT = 0x0,
    CSS_BACKGROUND_ATTACHMENT_FIXED = 0x1,
    CSS_BACKGROUND_ATTACHMENT_SCROLL = 0x2
};

enum css_background_color_e {
    CSS_BACKGROUND_COLOR_INHERIT = 0x0,
    CSS_BACKGROUND_COLOR_COLOR = 0x1,
    CSS_BACKGROUND_COLOR_CURRENT_COLOR = 0x2
};

enum css_background_image_e {
    CSS_BACKGROUND_IMAGE_INHERIT = 0x0,
    /* Consult pointer in struct to determine which */
    CSS_BACKGROUND_IMAGE_NONE = 0x1,
    CSS_BACKGROUND_IMAGE_IMAGE = 0x2,
    CSS_BACKGROUND_IMAGE_LINEAR_GRADIENT = 0x3,
    CSS_BACKGROUND_IMAGE_RADIAL_GRADIENT = 0x4
};

enum css_background_position_e { CSS_BACKGROUND_POSITION_INHERIT = 0x0, CSS_BACKGROUND_POSITION_SET = 0x1 };

enum css_background_repeat_e {
    CSS_BACKGROUND_REPEAT_INHERIT = 0x0,
    CSS_BACKGROUND_REPEAT_REPEAT_X = 0x1,
    CSS_BACKGROUND_REPEAT_REPEAT_Y = 0x2,
    CSS_BACKGROUND_REPEAT_REPEAT = 0x3,
    CSS_BACKGROUND_REPEAT_NO_REPEAT = 0x4
};

enum css_border_collapse_e {
    CSS_BORDER_COLLAPSE_INHERIT = 0x0,
    CSS_BORDER_COLLAPSE_SEPARATE = 0x1,
    CSS_BORDER_COLLAPSE_COLLAPSE = 0x2
};

enum css_border_spacing_e { CSS_BORDER_SPACING_INHERIT = 0x0, CSS_BORDER_SPACING_SET = 0x1 };

enum css_border_color_e {
    CSS_BORDER_COLOR_INHERIT = CSS_BACKGROUND_COLOR_INHERIT,
    CSS_BORDER_COLOR_COLOR = CSS_BACKGROUND_COLOR_COLOR,
    CSS_BORDER_COLOR_CURRENT_COLOR = CSS_BACKGROUND_COLOR_CURRENT_COLOR
};

enum css_border_style_e {
    CSS_BORDER_STYLE_INHERIT = 0x0,
    CSS_BORDER_STYLE_NONE = 0x1,
    CSS_BORDER_STYLE_HIDDEN = 0x2,
    CSS_BORDER_STYLE_DOTTED = 0x3,
    CSS_BORDER_STYLE_DASHED = 0x4,
    CSS_BORDER_STYLE_SOLID = 0x5,
    CSS_BORDER_STYLE_DOUBLE = 0x6,
    CSS_BORDER_STYLE_GROOVE = 0x7,
    CSS_BORDER_STYLE_RIDGE = 0x8,
    CSS_BORDER_STYLE_INSET = 0x9,
    CSS_BORDER_STYLE_OUTSET = 0xa
};

enum css_border_width_e {
    CSS_BORDER_WIDTH_INHERIT = 0x0,
    CSS_BORDER_WIDTH_THIN = 0x1,
    CSS_BORDER_WIDTH_MEDIUM = 0x2,
    CSS_BORDER_WIDTH_THICK = 0x3,
    CSS_BORDER_WIDTH_WIDTH = 0x4
};

enum css_bottom_e { CSS_BOTTOM_INHERIT = 0x0, CSS_BOTTOM_SET = 0x1, CSS_BOTTOM_AUTO = 0x2 };

enum css_box_sizing_e {
    CSS_BOX_SIZING_INHERIT = 0x0,
    CSS_BOX_SIZING_CONTENT_BOX = 0x1,
    CSS_BOX_SIZING_BORDER_BOX = 0x2
};

enum css_break_after_e {
    CSS_BREAK_AFTER_INHERIT = 0x0,
    CSS_BREAK_AFTER_AUTO = 0x1,
    CSS_BREAK_AFTER_AVOID = 0x2,
    CSS_BREAK_AFTER_ALWAYS = 0x3,
    CSS_BREAK_AFTER_LEFT = 0x4,
    CSS_BREAK_AFTER_RIGHT = 0x5,
    CSS_BREAK_AFTER_PAGE = 0x6,
    CSS_BREAK_AFTER_COLUMN = 0x7,
    CSS_BREAK_AFTER_AVOID_PAGE = 0x8,
    CSS_BREAK_AFTER_AVOID_COLUMN = 0x9
};

enum css_break_before_e {
    CSS_BREAK_BEFORE_INHERIT = CSS_BREAK_AFTER_INHERIT,
    CSS_BREAK_BEFORE_AUTO = CSS_BREAK_AFTER_AUTO,
    CSS_BREAK_BEFORE_AVOID = CSS_BREAK_AFTER_AVOID,
    CSS_BREAK_BEFORE_ALWAYS = CSS_BREAK_AFTER_ALWAYS,
    CSS_BREAK_BEFORE_LEFT = CSS_BREAK_AFTER_LEFT,
    CSS_BREAK_BEFORE_RIGHT = CSS_BREAK_AFTER_RIGHT,
    CSS_BREAK_BEFORE_PAGE = CSS_BREAK_AFTER_PAGE,
    CSS_BREAK_BEFORE_COLUMN = CSS_BREAK_AFTER_COLUMN,
    CSS_BREAK_BEFORE_AVOID_PAGE = CSS_BREAK_AFTER_AVOID_PAGE,
    CSS_BREAK_BEFORE_AVOID_COLUMN = CSS_BREAK_AFTER_AVOID_COLUMN
};

enum css_break_inside_e {
    CSS_BREAK_INSIDE_INHERIT = CSS_BREAK_AFTER_INHERIT,
    CSS_BREAK_INSIDE_AUTO = CSS_BREAK_AFTER_AUTO,
    CSS_BREAK_INSIDE_AVOID = CSS_BREAK_AFTER_AVOID,
    CSS_BREAK_INSIDE_AVOID_PAGE = CSS_BREAK_AFTER_AVOID_PAGE,
    CSS_BREAK_INSIDE_AVOID_COLUMN = CSS_BREAK_AFTER_AVOID_COLUMN
};

enum css_caption_side_e { CSS_CAPTION_SIDE_INHERIT = 0x0, CSS_CAPTION_SIDE_TOP = 0x1, CSS_CAPTION_SIDE_BOTTOM = 0x2 };

enum css_clear_e {
    CSS_CLEAR_INHERIT = 0x0,
    CSS_CLEAR_NONE = 0x1,
    CSS_CLEAR_LEFT = 0x2,
    CSS_CLEAR_RIGHT = 0x3,
    CSS_CLEAR_BOTH = 0x4
};

enum css_clip_e { CSS_CLIP_INHERIT = 0x0, CSS_CLIP_AUTO = 0x1, CSS_CLIP_RECT = 0x2 };

enum css_color_e { CSS_COLOR_INHERIT = 0x0, CSS_COLOR_COLOR = 0x1 };

enum css_column_count_e { CSS_COLUMN_COUNT_INHERIT = 0x0, CSS_COLUMN_COUNT_AUTO = 0x1, CSS_COLUMN_COUNT_SET = 0x2 };

enum css_column_fill_e { CSS_COLUMN_FILL_INHERIT = 0x0, CSS_COLUMN_FILL_BALANCE = 0x1, CSS_COLUMN_FILL_AUTO = 0x2 };

enum css_column_gap_e { CSS_COLUMN_GAP_INHERIT = 0x0, CSS_COLUMN_GAP_SET = 0x1, CSS_COLUMN_GAP_NORMAL = 0x2 };

enum css_column_rule_color_e {
    CSS_COLUMN_RULE_COLOR_INHERIT = CSS_BACKGROUND_COLOR_INHERIT,
    CSS_COLUMN_RULE_COLOR_COLOR = CSS_BACKGROUND_COLOR_COLOR,
    CSS_COLUMN_RULE_COLOR_CURRENT_COLOR = CSS_BACKGROUND_COLOR_CURRENT_COLOR
};

enum css_column_rule_style_e {
    CSS_COLUMN_RULE_STYLE_INHERIT = CSS_BORDER_STYLE_INHERIT,
    CSS_COLUMN_RULE_STYLE_NONE = CSS_BORDER_STYLE_NONE,
    CSS_COLUMN_RULE_STYLE_HIDDEN = CSS_BORDER_STYLE_HIDDEN,
    CSS_COLUMN_RULE_STYLE_DOTTED = CSS_BORDER_STYLE_DOTTED,
    CSS_COLUMN_RULE_STYLE_DASHED = CSS_BORDER_STYLE_DASHED,
    CSS_COLUMN_RULE_STYLE_SOLID = CSS_BORDER_STYLE_SOLID,
    CSS_COLUMN_RULE_STYLE_DOUBLE = CSS_BORDER_STYLE_DOUBLE,
    CSS_COLUMN_RULE_STYLE_GROOVE = CSS_BORDER_STYLE_GROOVE,
    CSS_COLUMN_RULE_STYLE_RIDGE = CSS_BORDER_STYLE_RIDGE,
    CSS_COLUMN_RULE_STYLE_INSET = CSS_BORDER_STYLE_INSET,
    CSS_COLUMN_RULE_STYLE_OUTSET = CSS_BORDER_STYLE_OUTSET
};

enum css_column_rule_width_e {
    CSS_COLUMN_RULE_WIDTH_INHERIT = CSS_BORDER_WIDTH_INHERIT,
    CSS_COLUMN_RULE_WIDTH_THIN = CSS_BORDER_WIDTH_THIN,
    CSS_COLUMN_RULE_WIDTH_MEDIUM = CSS_BORDER_WIDTH_MEDIUM,
    CSS_COLUMN_RULE_WIDTH_THICK = CSS_BORDER_WIDTH_THICK,
    CSS_COLUMN_RULE_WIDTH_WIDTH = CSS_BORDER_WIDTH_WIDTH
};

enum css_column_span_e { CSS_COLUMN_SPAN_INHERIT = 0x0, CSS_COLUMN_SPAN_NONE = 0x1, CSS_COLUMN_SPAN_ALL = 0x2 };

enum css_column_width_e { CSS_COLUMN_WIDTH_INHERIT = 0x0, CSS_COLUMN_WIDTH_SET = 0x1, CSS_COLUMN_WIDTH_AUTO = 0x2 };

enum css_content_e {
    CSS_CONTENT_INHERIT = 0x0,
    CSS_CONTENT_NONE = 0x1,
    CSS_CONTENT_NORMAL = 0x2,
    CSS_CONTENT_SET = 0x3
};

enum css_counter_increment_e {
    CSS_COUNTER_INCREMENT_INHERIT = 0x0,
    /* Consult pointer in struct to determine which */
    CSS_COUNTER_INCREMENT_NAMED = 0x1,
    CSS_COUNTER_INCREMENT_NONE = 0x1
};

enum css_counter_reset_e {
    CSS_COUNTER_RESET_INHERIT = 0x0,
    /* Consult pointer in struct to determine which */
    CSS_COUNTER_RESET_NAMED = 0x1,
    CSS_COUNTER_RESET_NONE = 0x1
};

enum css_cursor_e {
    CSS_CURSOR_INHERIT = 0x00,
    /* URLs exist if pointer is non-NULL */
    CSS_CURSOR_AUTO = 0x01,
    CSS_CURSOR_CROSSHAIR = 0x02,
    CSS_CURSOR_DEFAULT = 0x03,
    CSS_CURSOR_POINTER = 0x04,
    CSS_CURSOR_MOVE = 0x05,
    CSS_CURSOR_E_RESIZE = 0x06,
    CSS_CURSOR_NE_RESIZE = 0x07,
    CSS_CURSOR_NW_RESIZE = 0x08,
    CSS_CURSOR_N_RESIZE = 0x09,
    CSS_CURSOR_SE_RESIZE = 0x0a,
    CSS_CURSOR_SW_RESIZE = 0x0b,
    CSS_CURSOR_S_RESIZE = 0x0c,
    CSS_CURSOR_W_RESIZE = 0x0d,
    CSS_CURSOR_TEXT = 0x0e,
    CSS_CURSOR_WAIT = 0x0f,
    CSS_CURSOR_HELP = 0x10,
    CSS_CURSOR_PROGRESS = 0x11
};

enum css_direction_e { CSS_DIRECTION_INHERIT = 0x0, CSS_DIRECTION_LTR = 0x1, CSS_DIRECTION_RTL = 0x2 };

enum css_display_e {
    CSS_DISPLAY_INHERIT = 0x00,
    CSS_DISPLAY_INLINE = 0x01,
    CSS_DISPLAY_BLOCK = 0x02,
    CSS_DISPLAY_LIST_ITEM = 0x03,
    CSS_DISPLAY_RUN_IN = 0x04,
    CSS_DISPLAY_INLINE_BLOCK = 0x05,
    CSS_DISPLAY_TABLE = 0x06,
    CSS_DISPLAY_INLINE_TABLE = 0x07,
    CSS_DISPLAY_TABLE_ROW_GROUP = 0x08,
    CSS_DISPLAY_TABLE_HEADER_GROUP = 0x09,
    CSS_DISPLAY_TABLE_FOOTER_GROUP = 0x0a,
    CSS_DISPLAY_TABLE_ROW = 0x0b,
    CSS_DISPLAY_TABLE_COLUMN_GROUP = 0x0c,
    CSS_DISPLAY_TABLE_COLUMN = 0x0d,
    CSS_DISPLAY_TABLE_CELL = 0x0e,
    CSS_DISPLAY_TABLE_CAPTION = 0x0f,
    CSS_DISPLAY_NONE = 0x10,
    CSS_DISPLAY_FLEX = 0x11,
    CSS_DISPLAY_INLINE_FLEX = 0x12,
    CSS_DISPLAY_GRID = 0x13,
    CSS_DISPLAY_INLINE_GRID = 0x14
};

enum css_empty_cells_e { CSS_EMPTY_CELLS_INHERIT = 0x0, CSS_EMPTY_CELLS_SHOW = 0x1, CSS_EMPTY_CELLS_HIDE = 0x2 };

enum css_fill_e { CSS_FILL_INHERIT = 0x0, CSS_FILL_NONE = 0x1, CSS_FILL_COLOR = 0x2, CSS_FILL_CURRENT_COLOR = 0x3 };

enum css_fill_opacity_e { CSS_FILL_OPACITY_INHERIT = 0x0, CSS_FILL_OPACITY_SET = 0x1 };

enum css_flex_basis_e {
    CSS_FLEX_BASIS_INHERIT = 0x0,
    CSS_FLEX_BASIS_SET = 0x1,
    CSS_FLEX_BASIS_AUTO = 0x2,
    CSS_FLEX_BASIS_CONTENT = 0x3
};

enum css_flex_direction_e {
    CSS_FLEX_DIRECTION_INHERIT = 0x0,
    CSS_FLEX_DIRECTION_ROW = 0x1,
    CSS_FLEX_DIRECTION_ROW_REVERSE = 0x2,
    CSS_FLEX_DIRECTION_COLUMN = 0x3,
    CSS_FLEX_DIRECTION_COLUMN_REVERSE = 0x4
};

enum css_flex_grow_e { CSS_FLEX_GROW_INHERIT = 0x0, CSS_FLEX_GROW_SET = 0x1 };

enum css_flex_shrink_e { CSS_FLEX_SHRINK_INHERIT = 0x0, CSS_FLEX_SHRINK_SET = 0x1 };

enum css_flex_wrap_e {
    CSS_FLEX_WRAP_INHERIT = 0x0,
    CSS_FLEX_WRAP_NOWRAP = 0x1,
    CSS_FLEX_WRAP_WRAP = 0x2,
    CSS_FLEX_WRAP_WRAP_REVERSE = 0x3
};

enum css_float_e { CSS_FLOAT_INHERIT = 0x0, CSS_FLOAT_LEFT = 0x1, CSS_FLOAT_RIGHT = 0x2, CSS_FLOAT_NONE = 0x3 };

enum css_font_family_e {
    CSS_FONT_FAMILY_INHERIT = 0x0,
    /* Named fonts exist if pointer is non-NULL */
    CSS_FONT_FAMILY_SERIF = 0x1,
    CSS_FONT_FAMILY_SANS_SERIF = 0x2,
    CSS_FONT_FAMILY_CURSIVE = 0x3,
    CSS_FONT_FAMILY_FANTASY = 0x4,
    CSS_FONT_FAMILY_MONOSPACE = 0x5
};

enum css_font_size_e {
    CSS_FONT_SIZE_INHERIT = 0x0,
    CSS_FONT_SIZE_XX_SMALL = 0x1,
    CSS_FONT_SIZE_X_SMALL = 0x2,
    CSS_FONT_SIZE_SMALL = 0x3,
    CSS_FONT_SIZE_MEDIUM = 0x4,
    CSS_FONT_SIZE_LARGE = 0x5,
    CSS_FONT_SIZE_X_LARGE = 0x6,
    CSS_FONT_SIZE_XX_LARGE = 0x7,
    CSS_FONT_SIZE_LARGER = 0x8,
    CSS_FONT_SIZE_SMALLER = 0x9,
    CSS_FONT_SIZE_DIMENSION = 0xa
};

enum css_font_style_e {
    CSS_FONT_STYLE_INHERIT = 0x0,
    CSS_FONT_STYLE_NORMAL = 0x1,
    CSS_FONT_STYLE_ITALIC = 0x2,
    CSS_FONT_STYLE_OBLIQUE = 0x3
};

enum css_font_variant_e {
    CSS_FONT_VARIANT_INHERIT = 0x0,
    CSS_FONT_VARIANT_NORMAL = 0x1,
    CSS_FONT_VARIANT_SMALL_CAPS = 0x2
};

enum css_font_weight_e {
    CSS_FONT_WEIGHT_INHERIT = 0x0,
    CSS_FONT_WEIGHT_NORMAL = 0x1,
    CSS_FONT_WEIGHT_BOLD = 0x2,
    CSS_FONT_WEIGHT_BOLDER = 0x3,
    CSS_FONT_WEIGHT_LIGHTER = 0x4,
    CSS_FONT_WEIGHT_100 = 0x5,
    CSS_FONT_WEIGHT_200 = 0x6,
    CSS_FONT_WEIGHT_300 = 0x7,
    CSS_FONT_WEIGHT_400 = 0x8,
    CSS_FONT_WEIGHT_500 = 0x9,
    CSS_FONT_WEIGHT_600 = 0xa,
    CSS_FONT_WEIGHT_700 = 0xb,
    CSS_FONT_WEIGHT_800 = 0xc,
    CSS_FONT_WEIGHT_900 = 0xd
};

enum css_height_e { CSS_HEIGHT_INHERIT = 0x0, CSS_HEIGHT_SET = 0x1, CSS_HEIGHT_AUTO = 0x2 };

enum css_justify_content_e {
    CSS_JUSTIFY_CONTENT_INHERIT = 0x0,
    CSS_JUSTIFY_CONTENT_FLEX_START = 0x1,
    CSS_JUSTIFY_CONTENT_FLEX_END = 0x2,
    CSS_JUSTIFY_CONTENT_CENTER = 0x3,
    CSS_JUSTIFY_CONTENT_SPACE_BETWEEN = 0x4,
    CSS_JUSTIFY_CONTENT_SPACE_AROUND = 0x5,
    CSS_JUSTIFY_CONTENT_SPACE_EVENLY = 0x6
};

enum css_left_e { CSS_LEFT_INHERIT = 0x0, CSS_LEFT_SET = 0x1, CSS_LEFT_AUTO = 0x2 };

enum css_letter_spacing_e {
    CSS_LETTER_SPACING_INHERIT = CSS_COLUMN_GAP_INHERIT,
    CSS_LETTER_SPACING_SET = CSS_COLUMN_GAP_SET,
    CSS_LETTER_SPACING_NORMAL = CSS_COLUMN_GAP_NORMAL
};

enum css_line_height_e {
    CSS_LINE_HEIGHT_INHERIT = 0x0,
    CSS_LINE_HEIGHT_NUMBER = 0x1,
    CSS_LINE_HEIGHT_DIMENSION = 0x2,
    CSS_LINE_HEIGHT_NORMAL = 0x3
};

enum css_list_style_image_e {
    CSS_LIST_STYLE_IMAGE_INHERIT = 0x0,
    /* Consult pointer in struct to determine which */
    CSS_LIST_STYLE_IMAGE_URI = 0x1,
    CSS_LIST_STYLE_IMAGE_NONE = 0x1
};

enum css_list_style_position_e {
    CSS_LIST_STYLE_POSITION_INHERIT = 0x0,
    CSS_LIST_STYLE_POSITION_INSIDE = 0x1,
    CSS_LIST_STYLE_POSITION_OUTSIDE = 0x2
};

enum css_list_style_type_e {
    CSS_LIST_STYLE_TYPE_INHERIT = 0x0,
    CSS_LIST_STYLE_TYPE_DISC = 0x1,
    CSS_LIST_STYLE_TYPE_CIRCLE = 0x2,
    CSS_LIST_STYLE_TYPE_SQUARE = 0x3,
    CSS_LIST_STYLE_TYPE_DECIMAL = 0x4,
    CSS_LIST_STYLE_TYPE_DECIMAL_LEADING_ZERO = 0x5,
    CSS_LIST_STYLE_TYPE_LOWER_ROMAN = 0x6,
    CSS_LIST_STYLE_TYPE_UPPER_ROMAN = 0x7,
    CSS_LIST_STYLE_TYPE_LOWER_GREEK = 0x8,
    CSS_LIST_STYLE_TYPE_LOWER_LATIN = 0x9,
    CSS_LIST_STYLE_TYPE_UPPER_LATIN = 0xa,
    CSS_LIST_STYLE_TYPE_ARMENIAN = 0xb,
    CSS_LIST_STYLE_TYPE_GEORGIAN = 0xc,
    CSS_LIST_STYLE_TYPE_LOWER_ALPHA = 0xd,
    CSS_LIST_STYLE_TYPE_UPPER_ALPHA = 0xe,
    CSS_LIST_STYLE_TYPE_NONE = 0xf,
    CSS_LIST_STYLE_TYPE_BINARY = 0x10,
    CSS_LIST_STYLE_TYPE_OCTAL = 0x11,
    CSS_LIST_STYLE_TYPE_LOWER_HEXADECIMAL = 0x12,
    CSS_LIST_STYLE_TYPE_UPPER_HEXADECIMAL = 0x13,
    CSS_LIST_STYLE_TYPE_ARABIC_INDIC = 0x14,
    CSS_LIST_STYLE_TYPE_LOWER_ARMENIAN = 0x15,
    CSS_LIST_STYLE_TYPE_UPPER_ARMENIAN = 0x16,
    CSS_LIST_STYLE_TYPE_BENGALI = 0x17,
    CSS_LIST_STYLE_TYPE_CAMBODIAN = 0x18,
    CSS_LIST_STYLE_TYPE_KHMER = 0x19,
    CSS_LIST_STYLE_TYPE_CJK_DECIMAL = 0x1a,
    CSS_LIST_STYLE_TYPE_DEVANAGARI = 0x1b,
    CSS_LIST_STYLE_TYPE_GUJARATI = 0x1c,
    CSS_LIST_STYLE_TYPE_GURMUKHI = 0x1d,
    CSS_LIST_STYLE_TYPE_HEBREW = 0x1e,
    CSS_LIST_STYLE_TYPE_KANNADA = 0x1f,
    CSS_LIST_STYLE_TYPE_LAO = 0x20,
    CSS_LIST_STYLE_TYPE_MALAYALAM = 0x21,
    CSS_LIST_STYLE_TYPE_MONGOLIAN = 0x22,
    CSS_LIST_STYLE_TYPE_MYANMAR = 0x23,
    CSS_LIST_STYLE_TYPE_ORIYA = 0x24,
    CSS_LIST_STYLE_TYPE_PERSIAN = 0x25,
    CSS_LIST_STYLE_TYPE_TAMIL = 0x26,
    CSS_LIST_STYLE_TYPE_TELUGU = 0x27,
    CSS_LIST_STYLE_TYPE_THAI = 0x28,
    CSS_LIST_STYLE_TYPE_TIBETAN = 0x29,
    CSS_LIST_STYLE_TYPE_CJK_EARTHLY_BRANCH = 0x2a,
    CSS_LIST_STYLE_TYPE_CJK_HEAVENLY_STEM = 0x2b,
    CSS_LIST_STYLE_TYPE_HIAGANA = 0x2c,
    CSS_LIST_STYLE_TYPE_HIAGANA_IROHA = 0x2d,
    CSS_LIST_STYLE_TYPE_KATAKANA = 0x2e,
    CSS_LIST_STYLE_TYPE_KATAKANA_IROHA = 0x2f,
    CSS_LIST_STYLE_TYPE_JAPANESE_INFORMAL = 0x30,
    CSS_LIST_STYLE_TYPE_JAPANESE_FORMAL = 0x31,
    CSS_LIST_STYLE_TYPE_KOREAN_HANGUL_FORMAL = 0x32,
    CSS_LIST_STYLE_TYPE_KOREAN_HANJA_INFORMAL = 0x33,
    CSS_LIST_STYLE_TYPE_KOREAN_HANJA_FORMAL = 0x34
};

enum css_margin_e { CSS_MARGIN_INHERIT = 0x0, CSS_MARGIN_SET = 0x1, CSS_MARGIN_AUTO = 0x2 };

enum css_max_height_e { CSS_MAX_HEIGHT_INHERIT = 0x0, CSS_MAX_HEIGHT_SET = 0x1, CSS_MAX_HEIGHT_NONE = 0x2 };

enum css_max_width_e { CSS_MAX_WIDTH_INHERIT = 0x0, CSS_MAX_WIDTH_SET = 0x1, CSS_MAX_WIDTH_NONE = 0x2 };

enum css_min_height_e { CSS_MIN_HEIGHT_INHERIT = 0x0, CSS_MIN_HEIGHT_SET = 0x1, CSS_MIN_HEIGHT_AUTO = 0x2 };

enum css_min_width_e { CSS_MIN_WIDTH_INHERIT = 0x0, CSS_MIN_WIDTH_SET = 0x1, CSS_MIN_WIDTH_AUTO = 0x2 };

enum css_opacity_e { CSS_OPACITY_INHERIT = 0x0, CSS_OPACITY_SET = 0x1 };

enum css_order_e { CSS_ORDER_INHERIT = 0x0, CSS_ORDER_SET = 0x1 };

enum css_object_fit_e {
    CSS_OBJECT_FIT_INHERIT = 0x0,
    CSS_OBJECT_FIT_FILL = 0x1,
    CSS_OBJECT_FIT_CONTAIN = 0x2,
    CSS_OBJECT_FIT_COVER = 0x3,
    CSS_OBJECT_FIT_NONE = 0x4,
    CSS_OBJECT_FIT_SCALE_DOWN = 0x5
};

enum css_object_position_e { CSS_OBJECT_POSITION_INHERIT = 0x0, CSS_OBJECT_POSITION_SET = 0x1 };

enum css_transform_e { CSS_TRANSFORM_INHERIT = 0x0, CSS_TRANSFORM_NONE = 0x1, CSS_TRANSFORM_FUNCTIONS = 0x2 };

enum css_outline_color_e {
    CSS_OUTLINE_COLOR_INHERIT = CSS_BACKGROUND_COLOR_INHERIT,
    CSS_OUTLINE_COLOR_COLOR = CSS_BACKGROUND_COLOR_COLOR,
    CSS_OUTLINE_COLOR_CURRENT_COLOR = CSS_BACKGROUND_COLOR_CURRENT_COLOR,
    CSS_OUTLINE_COLOR_INVERT = 0x3
};

enum css_outline_style_e {
    CSS_OUTLINE_STYLE_INHERIT = CSS_BORDER_STYLE_INHERIT,
    CSS_OUTLINE_STYLE_NONE = CSS_BORDER_STYLE_NONE,
    CSS_OUTLINE_STYLE_DOTTED = CSS_BORDER_STYLE_DOTTED,
    CSS_OUTLINE_STYLE_DASHED = CSS_BORDER_STYLE_DASHED,
    CSS_OUTLINE_STYLE_SOLID = CSS_BORDER_STYLE_SOLID,
    CSS_OUTLINE_STYLE_DOUBLE = CSS_BORDER_STYLE_DOUBLE,
    CSS_OUTLINE_STYLE_GROOVE = CSS_BORDER_STYLE_GROOVE,
    CSS_OUTLINE_STYLE_RIDGE = CSS_BORDER_STYLE_RIDGE,
    CSS_OUTLINE_STYLE_INSET = CSS_BORDER_STYLE_INSET,
    CSS_OUTLINE_STYLE_OUTSET = CSS_BORDER_STYLE_OUTSET
};

enum css_outline_width_e {
    CSS_OUTLINE_WIDTH_INHERIT = CSS_BORDER_WIDTH_INHERIT,
    CSS_OUTLINE_WIDTH_THIN = CSS_BORDER_WIDTH_THIN,
    CSS_OUTLINE_WIDTH_MEDIUM = CSS_BORDER_WIDTH_MEDIUM,
    CSS_OUTLINE_WIDTH_THICK = CSS_BORDER_WIDTH_THICK,
    CSS_OUTLINE_WIDTH_WIDTH = CSS_BORDER_WIDTH_WIDTH
};

enum css_overflow_e {
    CSS_OVERFLOW_INHERIT = 0x0,
    CSS_OVERFLOW_VISIBLE = 0x1,
    CSS_OVERFLOW_HIDDEN = 0x2,
    CSS_OVERFLOW_SCROLL = 0x3,
    CSS_OVERFLOW_AUTO = 0x4
};

enum css_orphans_e { CSS_ORPHANS_INHERIT = 0x0, CSS_ORPHANS_SET = 0x1 };

enum css_padding_e { CSS_PADDING_INHERIT = 0x0, CSS_PADDING_SET = 0x1 };

enum css_page_break_after_e {
    CSS_PAGE_BREAK_AFTER_INHERIT = CSS_BREAK_AFTER_INHERIT,
    CSS_PAGE_BREAK_AFTER_AUTO = CSS_BREAK_AFTER_AUTO,
    CSS_PAGE_BREAK_AFTER_AVOID = CSS_BREAK_AFTER_AVOID,
    CSS_PAGE_BREAK_AFTER_ALWAYS = CSS_BREAK_AFTER_ALWAYS,
    CSS_PAGE_BREAK_AFTER_LEFT = CSS_BREAK_AFTER_LEFT,
    CSS_PAGE_BREAK_AFTER_RIGHT = CSS_BREAK_AFTER_RIGHT
};

enum css_page_break_before_e {
    CSS_PAGE_BREAK_BEFORE_INHERIT = CSS_BREAK_AFTER_INHERIT,
    CSS_PAGE_BREAK_BEFORE_AUTO = CSS_BREAK_AFTER_AUTO,
    CSS_PAGE_BREAK_BEFORE_AVOID = CSS_BREAK_AFTER_AVOID,
    CSS_PAGE_BREAK_BEFORE_ALWAYS = CSS_BREAK_AFTER_ALWAYS,
    CSS_PAGE_BREAK_BEFORE_LEFT = CSS_BREAK_AFTER_LEFT,
    CSS_PAGE_BREAK_BEFORE_RIGHT = CSS_BREAK_AFTER_RIGHT
};

enum css_page_break_inside_e {
    CSS_PAGE_BREAK_INSIDE_INHERIT = CSS_BREAK_AFTER_INHERIT,
    CSS_PAGE_BREAK_INSIDE_AUTO = CSS_BREAK_AFTER_AUTO,
    CSS_PAGE_BREAK_INSIDE_AVOID = CSS_BREAK_AFTER_AVOID
};

enum css_position_e {
    CSS_POSITION_INHERIT = 0x0,
    CSS_POSITION_STATIC = 0x1,
    CSS_POSITION_RELATIVE = 0x2,
    CSS_POSITION_ABSOLUTE = 0x3,
    CSS_POSITION_FIXED = 0x4,
    CSS_POSITION_STICKY = 0x5
};

enum css_quotes_e {
    CSS_QUOTES_INHERIT = 0x0,
    /* Consult pointer in struct to determine which */
    CSS_QUOTES_STRING = 0x1,
    CSS_QUOTES_NONE = 0x1
};

enum css_right_e { CSS_RIGHT_INHERIT = 0x0, CSS_RIGHT_SET = 0x1, CSS_RIGHT_AUTO = 0x2 };

enum css_stroke_opacity_e { CSS_STROKE_OPACITY_INHERIT = 0x0, CSS_STROKE_OPACITY_SET = 0x1 };

enum css_stroke_e {
    CSS_STROKE_INHERIT = 0x0,
    CSS_STROKE_NONE = 0x1,
    CSS_STROKE_COLOR = 0x2,
    CSS_STROKE_CURRENT_COLOR = 0x3
};

enum css_stroke_width_e { CSS_STROKE_WIDTH_INHERIT = 0x0, CSS_STROKE_WIDTH_SET = 0x1 };

enum css_table_layout_e { CSS_TABLE_LAYOUT_INHERIT = 0x0, CSS_TABLE_LAYOUT_AUTO = 0x1, CSS_TABLE_LAYOUT_FIXED = 0x2 };

enum css_text_align_e {
    CSS_TEXT_ALIGN_INHERIT = 0x0,
    CSS_TEXT_ALIGN_INHERIT_IF_NON_MAGIC = 0x1,
    CSS_TEXT_ALIGN_LEFT = 0x2,
    CSS_TEXT_ALIGN_RIGHT = 0x3,
    CSS_TEXT_ALIGN_CENTER = 0x4,
    CSS_TEXT_ALIGN_JUSTIFY = 0x5,
    CSS_TEXT_ALIGN_DEFAULT = 0x6,
    CSS_TEXT_ALIGN_LIBCSS_LEFT = 0x7,
    CSS_TEXT_ALIGN_LIBCSS_CENTER = 0x8,
    CSS_TEXT_ALIGN_LIBCSS_RIGHT = 0x9
};

enum css_text_decoration_e {
    CSS_TEXT_DECORATION_INHERIT = 0x00,
    CSS_TEXT_DECORATION_NONE = 0x10,
    CSS_TEXT_DECORATION_BLINK = (1 << 3),
    CSS_TEXT_DECORATION_LINE_THROUGH = (1 << 2),
    CSS_TEXT_DECORATION_OVERLINE = (1 << 1),
    CSS_TEXT_DECORATION_UNDERLINE = (1 << 0)
};

enum css_text_indent_e { CSS_TEXT_INDENT_INHERIT = 0x0, CSS_TEXT_INDENT_SET = 0x1 };

enum css_text_transform_e {
    CSS_TEXT_TRANSFORM_INHERIT = 0x0,
    CSS_TEXT_TRANSFORM_CAPITALIZE = 0x1,
    CSS_TEXT_TRANSFORM_UPPERCASE = 0x2,
    CSS_TEXT_TRANSFORM_LOWERCASE = 0x3,
    CSS_TEXT_TRANSFORM_NONE = 0x4
};

enum css_top_e { CSS_TOP_INHERIT = 0x0, CSS_TOP_SET = 0x1, CSS_TOP_AUTO = 0x2 };

enum css_unicode_bidi_e {
    CSS_UNICODE_BIDI_INHERIT = 0x0,
    CSS_UNICODE_BIDI_NORMAL = 0x1,
    CSS_UNICODE_BIDI_EMBED = 0x2,
    CSS_UNICODE_BIDI_BIDI_OVERRIDE = 0x3
};

enum css_vertical_align_e {
    CSS_VERTICAL_ALIGN_INHERIT = 0x0,
    CSS_VERTICAL_ALIGN_BASELINE = 0x1,
    CSS_VERTICAL_ALIGN_SUB = 0x2,
    CSS_VERTICAL_ALIGN_SUPER = 0x3,
    CSS_VERTICAL_ALIGN_TOP = 0x4,
    CSS_VERTICAL_ALIGN_TEXT_TOP = 0x5,
    CSS_VERTICAL_ALIGN_MIDDLE = 0x6,
    CSS_VERTICAL_ALIGN_BOTTOM = 0x7,
    CSS_VERTICAL_ALIGN_TEXT_BOTTOM = 0x8,
    CSS_VERTICAL_ALIGN_SET = 0x9
};

enum css_visibility_e {
    CSS_VISIBILITY_INHERIT = 0x0,
    CSS_VISIBILITY_VISIBLE = 0x1,
    CSS_VISIBILITY_HIDDEN = 0x2,
    CSS_VISIBILITY_COLLAPSE = 0x3
};

enum css_white_space_e {
    CSS_WHITE_SPACE_INHERIT = 0x0,
    CSS_WHITE_SPACE_NORMAL = 0x1,
    CSS_WHITE_SPACE_PRE = 0x2,
    CSS_WHITE_SPACE_NOWRAP = 0x3,
    CSS_WHITE_SPACE_PRE_WRAP = 0x4,
    CSS_WHITE_SPACE_PRE_LINE = 0x5
};

enum css_widows_e { CSS_WIDOWS_INHERIT = 0x0, CSS_WIDOWS_SET = 0x1 };

enum css_width_e { CSS_WIDTH_INHERIT = 0x0, CSS_WIDTH_SET = 0x1, CSS_WIDTH_AUTO = 0x2 };

enum css_word_spacing_e {
    CSS_WORD_SPACING_INHERIT = CSS_COLUMN_GAP_INHERIT,
    CSS_WORD_SPACING_SET = CSS_COLUMN_GAP_SET,
    CSS_WORD_SPACING_NORMAL = CSS_COLUMN_GAP_NORMAL
};

enum css_writing_mode_e {
    CSS_WRITING_MODE_INHERIT = 0x0,
    CSS_WRITING_MODE_HORIZONTAL_TB = 0x1,
    CSS_WRITING_MODE_VERTICAL_RL = 0x2,
    CSS_WRITING_MODE_VERTICAL_LR = 0x3
};

/* CSS Grid value enums */
enum css_grid_auto_flow_e {
    CSS_GRID_AUTO_FLOW_INHERIT = 0x0,
    CSS_GRID_AUTO_FLOW_ROW = 0x1,
    CSS_GRID_AUTO_FLOW_COLUMN = 0x2,
    CSS_GRID_AUTO_FLOW_ROW_DENSE = 0x3,
    CSS_GRID_AUTO_FLOW_COLUMN_DENSE = 0x4
};

enum css_row_gap_e {
    CSS_ROW_GAP_INHERIT = CSS_COLUMN_GAP_INHERIT,
    CSS_ROW_GAP_SET = CSS_COLUMN_GAP_SET,
    CSS_ROW_GAP_NORMAL = CSS_COLUMN_GAP_NORMAL
};

enum css_grid_template_e { CSS_GRID_TEMPLATE_INHERIT = 0x0, CSS_GRID_TEMPLATE_NONE = 0x1, CSS_GRID_TEMPLATE_SET = 0x2 };

enum css_grid_line_e {
    CSS_GRID_LINE_INHERIT = 0x0,
    CSS_GRID_LINE_AUTO = 0x1,
    CSS_GRID_LINE_SET = 0x2,
    CSS_GRID_LINE_SPAN = 0x3
};

enum css_z_index_e { CSS_Z_INDEX_INHERIT = 0x0, CSS_Z_INDEX_SET = 0x1, CSS_Z_INDEX_AUTO = 0x2 };

#ifdef __cplusplus
}
#endif

#endif
