/*
 * This file is part of LibCSS.
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 *
 * Manual opcode enums for properties that cannot be auto-generated.
 * These are properties marked MANUAL or OPCODES:MANUAL in properties.gen,
 * or properties using shared/WRAP/GENERIC opcode patterns.
 *
 * Auto-generated opcodes are in opcodes.inc (produced by property_generator.py).
 */

#ifndef css_bytecode_opcodes_manual_h_
#define css_bytecode_opcodes_manual_h_

enum op_azimuth {
    AZIMUTH_ANGLE = 0x0080,

    AZIMUTH_LEFTWARDS = 0x0040,
    AZIMUTH_RIGHTWARDS = 0x0041,

    AZIMUTH_BEHIND = (1 << 5),
    AZIMUTH_LEFT_SIDE = 0x0000,
    AZIMUTH_FAR_LEFT = 0x0001,
    AZIMUTH_LEFT = 0x0002,
    AZIMUTH_CENTER_LEFT = 0x0003,
    AZIMUTH_CENTER = 0x0004,
    AZIMUTH_CENTER_RIGHT = 0x0005,
    AZIMUTH_RIGHT = 0x0006,
    AZIMUTH_FAR_RIGHT = 0x0007,
    AZIMUTH_RIGHT_SIDE = 0x0008
};

enum op_background_image {
    BACKGROUND_IMAGE_NONE = 0x0000,
    BACKGROUND_IMAGE_URI = 0x0080,
    BACKGROUND_IMAGE_LINEAR_GRADIENT = 0x0081,
    BACKGROUND_IMAGE_RADIAL_GRADIENT = 0x0082
};

enum op_background_position {
    BACKGROUND_POSITION_HORZ_SET = 0x0080,
    BACKGROUND_POSITION_HORZ_CENTER = 0x0000,
    BACKGROUND_POSITION_HORZ_RIGHT = 0x0010,
    BACKGROUND_POSITION_HORZ_LEFT = 0x0020,

    BACKGROUND_POSITION_VERT_SET = 0x0008,
    BACKGROUND_POSITION_VERT_CENTER = 0x0000,
    BACKGROUND_POSITION_VERT_BOTTOM = 0x0001,
    BACKGROUND_POSITION_VERT_TOP = 0x0002
};

enum op_border_spacing { BORDER_SPACING_SET = 0x0080 };

enum op_border_color {
    BORDER_COLOR_TRANSPARENT = 0x0000,
    BORDER_COLOR_CURRENT_COLOR = 0x0001,
    BORDER_COLOR_SET = 0x0080
};

enum op_border_style {
    BORDER_STYLE_NONE = 0x0000,
    BORDER_STYLE_HIDDEN = 0x0001,
    BORDER_STYLE_DOTTED = 0x0002,
    BORDER_STYLE_DASHED = 0x0003,
    BORDER_STYLE_SOLID = 0x0004,
    BORDER_STYLE_DOUBLE = 0x0005,
    BORDER_STYLE_GROOVE = 0x0006,
    BORDER_STYLE_RIDGE = 0x0007,
    BORDER_STYLE_INSET = 0x0008,
    BORDER_STYLE_OUTSET = 0x0009
};

enum op_border_width {
    BORDER_WIDTH_CALC = VALUE_IS_CALC,
    BORDER_WIDTH_SET = 0x0080,
    BORDER_WIDTH_THIN = 0x0000,
    BORDER_WIDTH_MEDIUM = 0x0001,
    BORDER_WIDTH_THICK = 0x0002
};

enum op_bottom { BOTTOM_CALC = VALUE_IS_CALC, BOTTOM_SET = 0x0080, BOTTOM_AUTO = 0x0000 };

enum op_clip {
    CLIP_SHAPE_MASK = 0x0087,
    CLIP_SHAPE_RECT = 0x0080,

    CLIP_RECT_TOP_AUTO = 0x0008,
    CLIP_RECT_RIGHT_AUTO = 0x0010,
    CLIP_RECT_BOTTOM_AUTO = 0x0020,
    CLIP_RECT_LEFT_AUTO = 0x0040,

    CLIP_AUTO = 0x0000
};

enum op_column_rule_style {
    COLUMN_RULE_STYLE_NONE = BORDER_STYLE_NONE,
    COLUMN_RULE_STYLE_HIDDEN = BORDER_STYLE_HIDDEN,
    COLUMN_RULE_STYLE_DOTTED = BORDER_STYLE_DOTTED,
    COLUMN_RULE_STYLE_DASHED = BORDER_STYLE_DASHED,
    COLUMN_RULE_STYLE_SOLID = BORDER_STYLE_SOLID,
    COLUMN_RULE_STYLE_DOUBLE = BORDER_STYLE_DOUBLE,
    COLUMN_RULE_STYLE_GROOVE = BORDER_STYLE_GROOVE,
    COLUMN_RULE_STYLE_RIDGE = BORDER_STYLE_RIDGE,
    COLUMN_RULE_STYLE_INSET = BORDER_STYLE_INSET,
    COLUMN_RULE_STYLE_OUTSET = BORDER_STYLE_OUTSET
};

enum op_column_rule_width {
    COLUMN_RULE_WIDTH_CALC = BORDER_WIDTH_CALC,
    COLUMN_RULE_WIDTH_SET = BORDER_WIDTH_SET,
    COLUMN_RULE_WIDTH_THIN = BORDER_WIDTH_THIN,
    COLUMN_RULE_WIDTH_MEDIUM = BORDER_WIDTH_MEDIUM,
    COLUMN_RULE_WIDTH_THICK = BORDER_WIDTH_THICK
};

enum op_content {
    CONTENT_STRING = 0x0080,
    CONTENT_URI = 0x0081,
    CONTENT_COUNTER = 0x0082,
    CONTENT_COUNTERS = 0x0083,
    CONTENT_ATTR = 0x0084,

    CONTENT_COUNTER_STYLE_SHIFT = 8,
    CONTENT_COUNTERS_STYLE_SHIFT = 8,

    CONTENT_NORMAL = 0x0000,
    CONTENT_NONE = 0x0001,
    CONTENT_OPEN_QUOTE = 0x0002,
    CONTENT_CLOSE_QUOTE = 0x0003,
    CONTENT_NO_OPEN_QUOTE = 0x0004,
    CONTENT_NO_CLOSE_QUOTE = 0x0005
};

enum op_cursor {
    CURSOR_URI = 0x0080,

    CURSOR_AUTO = 0x0000,
    CURSOR_CROSSHAIR = 0x0001,
    CURSOR_DEFAULT = 0x0002,
    CURSOR_POINTER = 0x0003,
    CURSOR_MOVE = 0x0004,
    CURSOR_E_RESIZE = 0x0005,
    CURSOR_NE_RESIZE = 0x0006,
    CURSOR_NW_RESIZE = 0x0007,
    CURSOR_N_RESIZE = 0x0008,
    CURSOR_SE_RESIZE = 0x0009,
    CURSOR_SW_RESIZE = 0x000a,
    CURSOR_S_RESIZE = 0x000b,
    CURSOR_W_RESIZE = 0x000c,
    CURSOR_TEXT = 0x000d,
    CURSOR_WAIT = 0x000e,
    CURSOR_HELP = 0x000f,
    CURSOR_PROGRESS = 0x0010
};

enum op_elevation {
    ELEVATION_ANGLE = 0x0080,
    ELEVATION_BELOW = 0x0000,
    ELEVATION_LEVEL = 0x0001,
    ELEVATION_ABOVE = 0x0002,
    ELEVATION_HIGHER = 0x0003,
    ELEVATION_LOWER = 0x0004
};

enum op_fill_opacity { FILL_OPACITY_SET = 0x0080 };

enum op_fill { FILL_NONE = 0x0000, FILL_CURRENT_COLOR = 0x0001, FILL_SET = 0x0080 };

/* op_flex_wrap removed — now auto-generated in opcodes.inc */


enum op_font_family {
    FONT_FAMILY_STRING = 0x0080,
    FONT_FAMILY_IDENT_LIST = 0x0081,

    FONT_FAMILY_END = 0x0000,

    FONT_FAMILY_SERIF = 0x0001,
    FONT_FAMILY_SANS_SERIF = 0x0002,
    FONT_FAMILY_CURSIVE = 0x0003,
    FONT_FAMILY_FANTASY = 0x0004,
    FONT_FAMILY_MONOSPACE = 0x0005
};

enum op_font_weight {
    FONT_WEIGHT_NORMAL = 0x0000,
    FONT_WEIGHT_BOLD = 0x0001,
    FONT_WEIGHT_BOLDER = 0x0002,
    FONT_WEIGHT_LIGHTER = 0x0003,
    FONT_WEIGHT_100 = 0x0004,
    FONT_WEIGHT_200 = 0x0005,
    FONT_WEIGHT_300 = 0x0006,
    FONT_WEIGHT_400 = 0x0007,
    FONT_WEIGHT_500 = 0x0008,
    FONT_WEIGHT_600 = 0x0009,
    FONT_WEIGHT_700 = 0x000a,
    FONT_WEIGHT_800 = 0x000b,
    FONT_WEIGHT_900 = 0x000c
};

enum op_left { LEFT_CALC = BOTTOM_CALC, LEFT_SET = BOTTOM_SET, LEFT_AUTO = BOTTOM_AUTO };

enum op_list_style_type {
    LIST_STYLE_TYPE_DISC = 0x0000,
    LIST_STYLE_TYPE_CIRCLE = 0x0001,
    LIST_STYLE_TYPE_SQUARE = 0x0002,
    LIST_STYLE_TYPE_DECIMAL = 0x0003,
    LIST_STYLE_TYPE_DECIMAL_LEADING_ZERO = 0x0004,
    LIST_STYLE_TYPE_LOWER_ROMAN = 0x0005,
    LIST_STYLE_TYPE_UPPER_ROMAN = 0x0006,
    LIST_STYLE_TYPE_LOWER_GREEK = 0x0007,
    LIST_STYLE_TYPE_LOWER_LATIN = 0x0008,
    LIST_STYLE_TYPE_UPPER_LATIN = 0x0009,
    LIST_STYLE_TYPE_ARMENIAN = 0x000a,
    LIST_STYLE_TYPE_GEORGIAN = 0x000b,
    LIST_STYLE_TYPE_LOWER_ALPHA = 0x000c,
    LIST_STYLE_TYPE_UPPER_ALPHA = 0x000d,
    LIST_STYLE_TYPE_NONE = 0x000e,
    LIST_STYLE_TYPE_BINARY = 0x000f,
    LIST_STYLE_TYPE_OCTAL = 0x0010,
    LIST_STYLE_TYPE_LOWER_HEXADECIMAL = 0x0011,
    LIST_STYLE_TYPE_UPPER_HEXADECIMAL = 0x0012,
    LIST_STYLE_TYPE_ARABIC_INDIC = 0x0013,
    LIST_STYLE_TYPE_LOWER_ARMENIAN = 0x0014,
    LIST_STYLE_TYPE_UPPER_ARMENIAN = 0x0015,
    LIST_STYLE_TYPE_BENGALI = 0x0016,
    LIST_STYLE_TYPE_CAMBODIAN = 0x0017,
    LIST_STYLE_TYPE_KHMER = 0x0018,
    LIST_STYLE_TYPE_CJK_DECIMAL = 0x0019,
    LIST_STYLE_TYPE_DEVANAGARI = 0x001a,
    LIST_STYLE_TYPE_GUJARATI = 0x001b,
    LIST_STYLE_TYPE_GURMUKHI = 0x001c,
    LIST_STYLE_TYPE_HEBREW = 0x001d,
    LIST_STYLE_TYPE_KANNADA = 0x001e,
    LIST_STYLE_TYPE_LAO = 0x001f,
    LIST_STYLE_TYPE_MALAYALAM = 0x0020,
    LIST_STYLE_TYPE_MONGOLIAN = 0x0021,
    LIST_STYLE_TYPE_MYANMAR = 0x0022,
    LIST_STYLE_TYPE_ORIYA = 0x0023,
    LIST_STYLE_TYPE_PERSIAN = 0x0024,
    LIST_STYLE_TYPE_TAMIL = 0x0025,
    LIST_STYLE_TYPE_TELUGU = 0x0026,
    LIST_STYLE_TYPE_THAI = 0x0027,
    LIST_STYLE_TYPE_TIBETAN = 0x0028,
    LIST_STYLE_TYPE_CJK_EARTHLY_BRANCH = 0x0029,
    LIST_STYLE_TYPE_CJK_HEAVENLY_STEM = 0x002a,
    LIST_STYLE_TYPE_HIAGANA = 0x002b,
    LIST_STYLE_TYPE_HIAGANA_IROHA = 0x002c,
    LIST_STYLE_TYPE_KATAKANA = 0x002d,
    LIST_STYLE_TYPE_KATAKANA_IROHA = 0x002e,
    LIST_STYLE_TYPE_JAPANESE_INFORMAL = 0x002f,
    LIST_STYLE_TYPE_JAPANESE_FORMAL = 0x0030,
    LIST_STYLE_TYPE_KOREAN_HANGUL_FORMAL = 0x0031,
    LIST_STYLE_TYPE_KOREAN_HANJA_INFORMAL = 0x0032,
    LIST_STYLE_TYPE_KOREAN_HANJA_FORMAL = 0x0033
};

enum op_margin { MARGIN_CALC = VALUE_IS_CALC, MARGIN_SET = 0x0080, MARGIN_AUTO = 0x0000 };

enum op_opacity { OPACITY_SET = 0x0080 };

enum op_outline_color {
    OUTLINE_COLOR_TRANSPARENT = 0x0000,
    OUTLINE_COLOR_CURRENT_COLOR = 0x0001,
    OUTLINE_COLOR_INVERT = 0x0002,
    OUTLINE_COLOR_SET = 0x0080
};

enum op_outline_style {
    OUTLINE_STYLE_NONE = BORDER_STYLE_NONE,
    OUTLINE_STYLE_HIDDEN = BORDER_STYLE_HIDDEN,
    OUTLINE_STYLE_DOTTED = BORDER_STYLE_DOTTED,
    OUTLINE_STYLE_DASHED = BORDER_STYLE_DASHED,
    OUTLINE_STYLE_SOLID = BORDER_STYLE_SOLID,
    OUTLINE_STYLE_DOUBLE = BORDER_STYLE_DOUBLE,
    OUTLINE_STYLE_GROOVE = BORDER_STYLE_GROOVE,
    OUTLINE_STYLE_RIDGE = BORDER_STYLE_RIDGE,
    OUTLINE_STYLE_INSET = BORDER_STYLE_INSET,
    OUTLINE_STYLE_OUTSET = BORDER_STYLE_OUTSET
};

enum op_outline_width {
    OUTLINE_WIDTH_SET = BORDER_WIDTH_SET,
    OUTLINE_WIDTH_THIN = BORDER_WIDTH_THIN,
    OUTLINE_WIDTH_MEDIUM = BORDER_WIDTH_MEDIUM,
    OUTLINE_WIDTH_THICK = BORDER_WIDTH_THICK
};

/* op_overflow removed — OVERFLOW_* values are defined by
 * auto-generated enum op_overflow_x in opcodes.inc.
 * overflow_y (OPCODES:MANUAL) references the same values. */


enum op_padding { PADDING_CALC = VALUE_IS_CALC, PADDING_SET = 0x0080 };

enum op_play_during {
    PLAY_DURING_TYPE_MASK = 0x009f,
    PLAY_DURING_URI = 0x0080,
    PLAY_DURING_MIX = (1 << 6),
    PLAY_DURING_REPEAT = (1 << 5),

    PLAY_DURING_AUTO = 0x0000,
    PLAY_DURING_NONE = 0x0001
};

enum op_quotes {
    QUOTES_STRING = 0x0080,

    QUOTES_NONE = 0x0000
};

enum op_right { RIGHT_SET = BOTTOM_SET, RIGHT_AUTO = BOTTOM_AUTO };

enum op_stroke_opacity { STROKE_OPACITY_SET = 0x0080 };

enum op_text_decoration {
    TEXT_DECORATION_NONE = 0x0000,

    TEXT_DECORATION_BLINK = (1 << 3),
    TEXT_DECORATION_LINE_THROUGH = (1 << 2),
    TEXT_DECORATION_OVERLINE = (1 << 1),
    TEXT_DECORATION_UNDERLINE = (1 << 0)
};

enum op_top { TOP_CALC = BOTTOM_CALC, TOP_SET = BOTTOM_SET, TOP_AUTO = BOTTOM_AUTO };

enum op_voice_family {
    VOICE_FAMILY_STRING = 0x0080,
    VOICE_FAMILY_IDENT_LIST = 0x0081,

    VOICE_FAMILY_END = 0x0000,

    VOICE_FAMILY_MALE = 0x0001,
    VOICE_FAMILY_FEMALE = 0x0002,
    VOICE_FAMILY_CHILD = 0x0003
};

/* op_white_space removed — now auto-generated in opcodes.inc */


enum op_grid_auto_flow {
    GRID_AUTO_FLOW_ROW = 0x0000,
    GRID_AUTO_FLOW_COLUMN = 0x0001,
    GRID_AUTO_FLOW_ROW_DENSE = 0x0002,
    GRID_AUTO_FLOW_COLUMN_DENSE = 0x0003
};

enum op_grid_line { GRID_LINE_AUTO = 0x0000, GRID_LINE_SET = 0x0001, GRID_LINE_SPAN = 0x0002 };

enum op_grid_template { GRID_TEMPLATE_NONE = 0x0000, GRID_TEMPLATE_SET = 0x0080 };

enum op_object_position {
    OBJECT_POSITION_HORZ_SET = 0x0080,
    OBJECT_POSITION_HORZ_CENTER = 0x0000,
    OBJECT_POSITION_HORZ_RIGHT = 0x0010,
    OBJECT_POSITION_HORZ_LEFT = 0x0020,

    OBJECT_POSITION_VERT_SET = 0x0008,
    OBJECT_POSITION_VERT_CENTER = 0x0000,
    OBJECT_POSITION_VERT_BOTTOM = 0x0001,
    OBJECT_POSITION_VERT_TOP = 0x0002
};

enum op_transform {
    TRANSFORM_NONE = 0x0000,
    TRANSFORM_TRANSLATE = 0x0001,
    TRANSFORM_TRANSLATEX = 0x0002,
    TRANSFORM_TRANSLATEY = 0x0003,
    TRANSFORM_SCALE = 0x0004,
    TRANSFORM_SCALEX = 0x0005,
    TRANSFORM_SCALEY = 0x0006,
    TRANSFORM_ROTATE = 0x0007
};

#endif
