#!/usr/bin/python3

import sys
import subprocess
import os

import subprocess

outDir = sys.argv[1]
parser = sys.argv[2]
srcFile = sys.argv[3]

nrArgs = len(sys.argv) -1

if nrArgs != 3:
    print("Number of arguments given: ", nrArgs)
    print("Three arguments are required: output directory, gen_parser binary location, properties.gen location")
    exit(1)

propFile = open(srcFile, 'r')
Lines = propFile.readlines()

for line in Lines:
    line = line.strip()
    if (line != "") and (not line.startswith("#")):
        # Skip properties with manual implementations (SHORTHAND or MANUAL keyword)
        if " SHORTHAND" in line or " MANUAL" in line:
            continue
        genName = line.split(':', 1)[0]
        outFile = os.path.join(outDir, "autogenerated_{0}.c".format(genName))
        
        # Strip OPCODES:MANUAL — only used by property_generator.py, not gen_parser
        gen_line = line.replace("OPCODES:MANUAL ", "")
        
        try:
            # Use subprocess to avoid shell quoting issues on Windows
            subprocess.run([parser, '-o', outFile, gen_line], check=True)
        except subprocess.CalledProcessError as e:
            print("Error generating parser for {0}: {1}".format(genName, e))
            exit(1)
