/*
 * This file is auto-generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Command: python contrib/libcss/src/select/select_generator.py --toml contrib/libcss/properties.toml /tmp/select_out
 */

/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2017 The NetSurf Project
 */

#ifndef CSS_COMPUTED_COMPUTED_H_
#define CSS_COMPUTED_COMPUTED_H_
#include <libcss/computed.h>
#include <libcss/gradient.h>
#include "select/calc.h"

#ifndef css_fixed_or_calc_typedef
#define css_fixed_or_calc_typedef
typedef union {
	css_fixed value;
	lwc_string *calc;
} css_fixed_or_calc;
#endif


struct css_computed_style_i {
/*
 * Property                       Size (bits)     Size (bytes)
 * ---                            ---             ---
 * align_content                    3
 * align_items                      3
 * align_self                       3
 * background_attachment            2
 * background_color                 2               4
 * background_image                 4             sizeof(ptr)
 * background_position              1 + 12          8
 * background_repeat                3
 * border_bottom_color              2               4
 * border_bottom_style              4
 * border_bottom_width              3 + 6           4
 * border_collapse                  2
 * border_left_color                2               4
 * border_left_style                4
 * border_left_width                3 + 6           4
 * border_right_color               2               4
 * border_right_style               4
 * border_right_width               3 + 6           4
 * border_spacing                   1 + 12          8
 * border_top_color                 2               4
 * border_top_style                 4
 * border_top_width                 3 + 6           4
 * bottom                           2 + 6           4
 * box_sizing                       2
 * break_after                      4
 * break_before                     4
 * break_inside                     4
 * caption_side                     2
 * clear                            3
 * clip                             6 + 24         16
 * color                            1               4
 * column_count                     2               4
 * column_fill                      2
 * column_gap                       2 + 6           4
 * column_rule_color                2               4
 * column_rule_style                4
 * column_rule_width                3 + 6           4
 * column_span                      2
 * column_width                     2 + 6           4
 * direction                        2
 * display                          5
 * empty_cells                      2
 * fill                             2               4
 * fill_opacity                     1               4
 * flex_basis                       2 + 6           4
 * flex_direction                   3
 * flex_grow                        1               4
 * flex_shrink                      1               4
 * flex_wrap                        2
 * float                            2
 * font_size                        4 + 6           4
 * font_style                       2
 * font_variant                     2
 * font_weight                      4
 * grid_auto_flow                   3
 * grid_column_end                  2               4
 * grid_column_start                2               4
 * grid_row_end                     2               4
 * grid_row_start                   2               4
 * height                           2 + 6           4
 * justify_content                  3
 * left                             2 + 6           4
 * letter_spacing                   2 + 6           4
 * line_height                      2 + 6           4
 * list_style_image                 1             sizeof(ptr)
 * list_style_position              2
 * list_style_type                  6
 * margin_bottom                    2 + 6           4
 * margin_left                      2 + 6           4
 * margin_right                     2 + 6           4
 * margin_top                       2 + 6           4
 * max_height                       2 + 6           4
 * max_width                        2 + 6           4
 * min_height                       2 + 6           4
 * min_width                        2 + 6           4
 * object_fit                       3
 * object_position                  1 + 12          8
 * opacity                          1               4
 * order                            1               4
 * orphans                          1               4
 * outline_color                    2               4
 * outline_style                    4
 * outline_width                    3 + 6           4
 * overflow_x                       3
 * overflow_y                       3
 * padding_bottom                   1 + 6           4
 * padding_left                     1 + 6           4
 * padding_right                    1 + 6           4
 * padding_top                      1 + 6           4
 * page_break_after                 3
 * page_break_before                3
 * page_break_inside                2
 * position                         3
 * right                            2 + 6           4
 * row_gap                          2 + 6           4
 * stroke                           2               4
 * stroke_opacity                   1               4
 * stroke_width                     1 + 6           4
 * tab_size                         2               4
 * table_layout                     2
 * text_align                       4
 * text_decoration                  5
 * text_indent                      1 + 6           4
 * text_transform                   3
 * top                              2 + 6           4
 * unicode_bidi                     2
 * vertical_align                   4 + 6           4
 * visibility                       2
 * white_space                      3
 * widows                           1               4
 * width                            2 + 6           4
 * word_spacing                     2 + 6           4
 * writing_mode                     2
 * z_index                          2               4
 *
 * Encode content as an array of content items, terminated with a blank entry.
 *
 * content                          2             sizeof(ptr)
 *
 * Encode counter_increment as an array of name, value pairs, terminated with a
 * blank entry.
 *
 * counter_increment                1             sizeof(ptr)
 *
 * Encode counter_reset as an array of name, value pairs, terminated with a
 * blank entry.
 *
 * counter_reset                    1             sizeof(ptr)
 *
 * Encode counter_set as an array of name, value pairs, terminated with a blank
 * entry.
 *
 * counter_set                      2             sizeof(ptr)
 *
 * Encode cursor uri(s) as an array of string objects, terminated with a blank
 * entry.
 *
 * cursor                           5             sizeof(ptr)
 *
 * Encode font family as an array of string objects, terminated with a blank
 * entry.
 *
 * font_family                      3             sizeof(ptr)
 *
 * Encode grid tracks as an array of track items, terminated with a zero-value
 * entry.
 *
 * grid_template_columns            2             sizeof(ptr)
 *
 * Encode grid tracks as an array of track items, terminated with a zero-value
 * entry.
 *
 * grid_template_rows               2             sizeof(ptr)
 *
 * Encode quotes as an array of string objects, terminated with a blank entry.
 *
 * quotes                           1             sizeof(ptr)
 *
 * Transform functions stored in css_computed_style.transform_*
 *
 * transform                        2
 *
 * ---                            ---             ---
 *                                564 bits        280 + 11sizeof(ptr) bytes
 *                                ===================
 *                                351 + 11sizeof(ptr) bytes
 *
 * Bit allocations:
 *
 * 0  bbbbbbbbbbbbbvvvvvvvvvvooooooooo
 * background_position; vertical_align; outline_width
 *
 * 1  wwwwwwwwiiiiiiiittttttttrrrrrrrr
 * word_spacing; width; top; row_gap
 *
 * 2  rrrrrrrrmmmmmmmmiiiiiiiiaaaaaaaa
 * right; min_width; min_height; max_width
 *
 * 3  mmmmmmmmaaaaaaaarrrrrrrrgggggggg
 * max_height; margin_top; margin_right; margin_left
 *
 * 4  mmmmmmmmlllllllleeeeeeeeffffffff
 * margin_bottom; line_height; letter_spacing; left
 *
 * 5  hhhhhhhhffffffffccccccccoooooooo
 * height; flex_basis; column_width; column_gap
 *
 * 6  ooooooooooooobbbbbbbbbbbbbllllll
 * object_position; border_spacing; list_style_type
 *
 * 7  bbbbbbbbbooooooooorrrrrrrrrttttt
 * border_right_width; border_left_width; border_bottom_width; text_decoration
 *
 * 8  ffffffffffcccccccccbbbbbbbbbtttt
 * font_size; column_rule_width; border_top_width; text_align
 *
 * 9  ooooffffccccbbbbrrrreeeeddddiiii
 * outline_style; font_weight; column_rule_style; break_inside; break_before;
 * break_after; border_top_style; border_right_style
 *
 * 10 bbbbbbbbtttttttssssssspppppppwww
 * bottom; text_indent; stroke_width; padding_top; white_space
 *
 * 11 cccccccccccccccccccccccccccccczz
 * clip; z_index
 *
 * 12 bbbbooooaaaatttpppgggeeevvvrrrww
 * border_left_style; border_bottom_style; background_image; text_transform;
 * position; page_break_before; page_break_after; overflow_y; overflow_x;
 * writing_mode
 *
 * 13 ooojjjgggffflllcccbbbaaaiiinnnvv
 * object_fit; justify_content; grid_auto_flow; font_family; flex_direction;
 * clear; background_repeat; align_self; align_items; align_content; visibility
 *
 * 14 uuttaabbssppoollggrriiddccmmffnn
 * unicode_bidi; transform; table_layout; tab_size; stroke; page_break_inside;
 * outline_color; list_style_position; grid_template_rows;
 * grid_template_columns; grid_row_start; grid_row_end; grid_column_start;
 * grid_column_end; font_variant; font_style
 *
 * 15 fflliieeddccoouummnnttaabbrrggBB
 * float; flex_wrap; fill; empty_cells; direction; counter_set; content;
 * column_span; column_rule_color; column_fill; column_count; caption_side;
 * box_sizing; border_top_color; border_right_color; border_left_color
 *
 * 16 pppppppaaaaaaadddddddiiiiicccccw
 * padding_right; padding_left; padding_bottom; display; cursor; widows
 *
 * 17 bbooaaccsqrdplfeiunC............
 * border_collapse; border_bottom_color; background_color;
 * background_attachment; stroke_opacity; quotes; orphans; order; opacity;
 * list_style_image; flex_shrink; flex_grow; fill_opacity; counter_reset;
 * counter_increment; color
 */
	uint32_t bits[18];

	css_color background_color;
	lwc_string *background_image;
	css_fixed background_position_a;
	css_fixed background_position_b;
	css_color border_bottom_color;
	css_fixed border_bottom_width;
	css_color border_left_color;
	css_fixed border_left_width;
	css_color border_right_color;
	css_fixed border_right_width;
	css_fixed border_spacing_a;
	css_fixed border_spacing_b;
	css_color border_top_color;
	css_fixed border_top_width;
	css_fixed bottom;
	css_fixed clip_a;
	css_fixed clip_b;
	css_fixed clip_c;
	css_fixed clip_d;
	css_color color;
	int32_t column_count;
	css_fixed column_gap;
	css_color column_rule_color;
	css_fixed column_rule_width;
	css_fixed column_width;
	css_color fill;
	css_fixed fill_opacity;
	css_fixed_or_calc flex_basis;
	css_fixed flex_grow;
	css_fixed flex_shrink;
	css_fixed font_size;
	int32_t grid_column_end;
	int32_t grid_column_start;
	int32_t grid_row_end;
	int32_t grid_row_start;
	css_fixed height;
	css_fixed left;
	css_fixed letter_spacing;
	css_fixed line_height;
	lwc_string *list_style_image;
	css_fixed margin_bottom;
	css_fixed margin_left;
	css_fixed margin_right;
	css_fixed margin_top;
	css_fixed max_height;
	css_fixed max_width;
	css_fixed min_height;
	css_fixed min_width;
	css_fixed object_position_a;
	css_fixed object_position_b;
	css_fixed opacity;
	int32_t order;
	int32_t orphans;
	css_color outline_color;
	css_fixed outline_width;
	css_fixed padding_bottom;
	css_fixed padding_left;
	css_fixed padding_right;
	css_fixed padding_top;
	css_fixed right;
	css_fixed row_gap;
	css_color stroke;
	css_fixed stroke_opacity;
	css_fixed stroke_width;
	int32_t tab_size;
	css_fixed text_indent;
	css_fixed top;
	css_fixed vertical_align;
	int32_t widows;
	css_fixed_or_calc width;
	css_fixed word_spacing;
	int32_t z_index;
};

struct css_computed_style {
	struct css_computed_style_i i;

	css_computed_content_item *content;
	css_computed_counter *counter_increment;
	css_computed_counter *counter_reset;
	css_computed_counter *counter_set;
	lwc_string **cursor;
	lwc_string **font_family;
	css_computed_grid_track *grid_template_columns;
	css_computed_grid_track *grid_template_rows;
	lwc_string **quotes;

	/* CSS transform function data */
	uint32_t transform_count;
	css_transform_function *transform_functions;

	/* CSS gradient data */
	css_linear_gradient *background_gradient;
	css_radial_gradient *background_radial_gradient;

	struct css_computed_style *next;
	uint32_t count;
	uint32_t bin;
	css_calculator *calc;
};

#endif
