/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2009 John-Mark Bell <jmb@netsurf-browser.org>
 *
 * Manual computed style getters - functions with custom logic that
 * cannot be auto-generated from properties.toml.
 *
 * Auto-generated simple wrappers are in autogenerated_computed.inc.
 */

#include <libcss/computed.h>
#include "select/propget.h"
#include "select/unit.h"

uint8_t css_computed_outline_width(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    /* This property is in the uncommon block, so we need to handle
     * absolute value calculation for initial value (medium) here. */
    if (get_outline_width(style, length, unit) == CSS_BORDER_WIDTH_MEDIUM) {
        *length = INTTOFIX(2);
        *unit = CSS_UNIT_PX;
    }

    return CSS_BORDER_WIDTH_WIDTH;
}

uint8_t css_computed_clip(const css_computed_style *style, css_computed_clip_rect *rect)
{
    return get_clip(style, rect);
}

uint8_t css_computed_top(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    uint8_t position = css_computed_position(style);
    uint8_t top = get_top(style, length, unit);

    /* Fix up, based on computed position */
    if (position == CSS_POSITION_STATIC) {
        /* Static -> auto */
        top = CSS_TOP_AUTO;
    } else if (position == CSS_POSITION_RELATIVE) {
        /* Relative -> follow $9.4.3 */
        uint8_t bottom = get_bottom_bits(style);

        if (top == CSS_TOP_AUTO && (bottom & 0x3) == CSS_BOTTOM_AUTO) {
            /* Both auto => 0px */
            *length = 0;
            *unit = CSS_UNIT_PX;
        } else if (top == CSS_TOP_AUTO) {
            /* Top is auto => -bottom */
            *length = -style->i.bottom;
            *unit = (css_unit)(bottom >> 2);
        }

        top = CSS_TOP_SET;
    }

    return top;
}

uint8_t css_computed_right(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    uint8_t position = css_computed_position(style);
    uint8_t right = get_right(style, length, unit);

    /* Fix up, based on computed position */
    if (position == CSS_POSITION_STATIC) {
        /* Static -> auto */
        right = CSS_RIGHT_AUTO;
    } else if (position == CSS_POSITION_RELATIVE) {
        /* Relative -> follow $9.4.3 */
        uint8_t left = get_left_bits(style);

        if (right == CSS_RIGHT_AUTO && (left & 0x3) == CSS_LEFT_AUTO) {
            /* Both auto => 0px */
            *length = 0;
            *unit = CSS_UNIT_PX;
        } else if (right == CSS_RIGHT_AUTO) {
            /* Right is auto => -left */
            *length = -style->i.left;
            *unit = (css_unit)(left >> 2);
        } else {
            /** \todo Consider containing block's direction
             * if overconstrained */
        }

        right = CSS_RIGHT_SET;
    }

    return right;
}

uint8_t css_computed_bottom(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    uint8_t position = css_computed_position(style);
    uint8_t bottom = get_bottom(style, length, unit);

    /* Fix up, based on computed position */
    if (position == CSS_POSITION_STATIC) {
        /* Static -> auto */
        bottom = CSS_BOTTOM_AUTO;
    } else if (position == CSS_POSITION_RELATIVE) {
        /* Relative -> follow $9.4.3 */
        uint8_t top = get_top_bits(style);

        if (bottom == CSS_BOTTOM_AUTO && (top & 0x3) == CSS_TOP_AUTO) {
            /* Both auto => 0px */
            *length = 0;
            *unit = CSS_UNIT_PX;
        } else if (bottom == CSS_BOTTOM_AUTO || (top & 0x3) != CSS_TOP_AUTO) {
            /* Bottom is auto or top is not auto => -top */
            *length = -style->i.top;
            *unit = (css_unit)(top >> 2);
        }

        bottom = CSS_BOTTOM_SET;
    }

    return bottom;
}

uint8_t css_computed_left(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    uint8_t position = css_computed_position(style);
    uint8_t left = get_left(style, length, unit);

    /* Fix up, based on computed position */
    if (position == CSS_POSITION_STATIC) {
        /* Static -> auto */
        left = CSS_LEFT_AUTO;
    } else if (position == CSS_POSITION_RELATIVE) {
        /* Relative -> follow $9.4.3 */
        uint8_t right = get_right_bits(style);

        if (left == CSS_LEFT_AUTO && (right & 0x3) == CSS_RIGHT_AUTO) {
            /* Both auto => 0px */
            *length = 0;
            *unit = CSS_UNIT_PX;
        } else if (left == CSS_LEFT_AUTO) {
            /* Left is auto => -right */
            *length = -style->i.right;
            *unit = (css_unit)(right >> 2);
        } else {
            /** \todo Consider containing block's direction
             * if overconstrained */
        }

        left = CSS_LEFT_SET;
    }

    return left;
}

uint8_t
css_computed_width_px(const css_computed_style *style, const css_unit_ctx *unit_ctx, int available_px, int *px_out)
{
    enum css_width_e type;
    css_unit unit = CSS_UNIT_PX;
    css_fixed_or_calc value = {.value = 0};

    type = get_width(style, &value, &unit);
    switch (type) {
    case CSS_WIDTH_INHERIT:
        break;
    case CSS_WIDTH_AUTO:
        break;
    case CSS_WIDTH_SET:
        switch (unit) {
        case CSS_UNIT_CALC:
            // fprintf(stderr, "CALC WIDTH: available_px=%d calc_ptr=%p\n", available_px, (void *)value.calc);
            if (css_calculator_calculate(style->calc, unit_ctx, available_px, value.calc, style, &unit, &value.value) ==
                CSS_OK) {
                type = CSS_WIDTH_SET;
                *px_out = FIXTOINT(css_unit_css2device_px(value.value, unit_ctx->device_dpi));
                // fprintf(stderr, "CALC WIDTH: SUCCESS result=%d unit=%d\n", *px_out, unit);
            } else {
                type = CSS_WIDTH_AUTO;
                // fprintf(stderr, "CALC WIDTH: FAILED, falling back to AUTO\n");
            }
            break;
        case CSS_UNIT_PCT:
            if (available_px < 0) {
                type = CSS_WIDTH_AUTO;
                break;
            }

            *px_out = FPCT_OF_INT_TOINT(value.value, available_px);
            break;
        case CSS_UNIT_FIT_CONTENT:
        case CSS_UNIT_MIN_CONTENT:
        case CSS_UNIT_MAX_CONTENT:
            /* These sizing keywords cannot be resolved to a fixed pixel value.
             * Treat as AUTO so the layout engine can shrink-to-fit content. */
            type = CSS_WIDTH_AUTO;
            break;
        default:
            *px_out = FIXTOINT(css_unit_len2device_px(style, unit_ctx, value.value, unit));
            break;
        }
        break;
    }

    return type;
}

uint8_t css_computed_width(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    css_fixed_or_calc length_ = {.value = 0};
    uint8_t ret = get_width(style, &length_, unit);
    if (ret == CSS_WIDTH_SET) {
        if (*unit == CSS_UNIT_CALC) {
            return CSS_WIDTH_AUTO;
        }
        *length = length_.value;
    }
    return ret;
}

uint8_t css_computed_float(const css_computed_style *style)
{
    uint8_t position = css_computed_position(style);
    uint8_t value = get_float(style);

    /* Fix up as per $9.7:2 */
    if (position == CSS_POSITION_ABSOLUTE || position == CSS_POSITION_FIXED)
        return CSS_FLOAT_NONE;

    return value;
}

uint8_t css_computed_min_height(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    uint8_t min_height = get_min_height(style, length, unit);

    if (min_height == CSS_MIN_HEIGHT_AUTO) {
        uint8_t display = get_display(style);

        if (display != CSS_DISPLAY_FLEX && display != CSS_DISPLAY_INLINE_FLEX) {
            min_height = CSS_MIN_HEIGHT_SET;
            *length = 0;
            *unit = CSS_UNIT_PX;
        }
    }

    return min_height;
}

uint8_t css_computed_min_width(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    uint8_t min_width = get_min_width(style, length, unit);

    if (min_width == CSS_MIN_WIDTH_AUTO) {
        uint8_t display = get_display(style);

        if (display != CSS_DISPLAY_FLEX && display != CSS_DISPLAY_INLINE_FLEX) {
            min_width = CSS_MIN_WIDTH_SET;
            *length = 0;
            *unit = CSS_UNIT_PX;
        }
    }

    return min_width;
}

uint8_t css_computed_column_rule_color(const css_computed_style *style, css_color *color)
{
    /* This property is in the uncommon block, so we need to handle
     * absolute value calculation for initial value (currentColor) here. */
    if (get_column_rule_color(style, color) == CSS_COLUMN_RULE_COLOR_CURRENT_COLOR) {
        css_computed_color(style, color);
    }
    return CSS_COLUMN_RULE_COLOR_COLOR;
}

uint8_t css_computed_column_rule_width(const css_computed_style *style, css_fixed *length, css_unit *unit)
{
    /* This property is in the uncommon block, so we need to handle
     * absolute value calculation for initial value (medium) here. */
    if (get_column_rule_width(style, length, unit) == CSS_BORDER_WIDTH_MEDIUM) {
        *length = INTTOFIX(2);
        *unit = CSS_UNIT_PX;
    }

    return CSS_BORDER_WIDTH_WIDTH;
}

uint8_t css_computed_display(const css_computed_style *style, bool root)
{
    uint8_t position = css_computed_position(style);
    uint8_t display = get_display(style);

    /* Return computed display as per $9.7 */

    if (display == CSS_DISPLAY_NONE)
        return display; /* 1. */

    if ((position == CSS_POSITION_ABSOLUTE || position == CSS_POSITION_FIXED) /* 2. */
        || css_computed_float(style) != CSS_FLOAT_NONE /* 3. */ || root /* 4. */) {
        if (display == CSS_DISPLAY_INLINE_TABLE) {
            return CSS_DISPLAY_TABLE;
        } else if (display == CSS_DISPLAY_INLINE_FLEX) {
            return CSS_DISPLAY_FLEX;
        } else if (display == CSS_DISPLAY_INLINE_GRID) {
            return CSS_DISPLAY_GRID;
        } else if (display == CSS_DISPLAY_INLINE || display == CSS_DISPLAY_RUN_IN ||
            display == CSS_DISPLAY_TABLE_ROW_GROUP || display == CSS_DISPLAY_TABLE_COLUMN ||
            display == CSS_DISPLAY_TABLE_COLUMN_GROUP || display == CSS_DISPLAY_TABLE_HEADER_GROUP ||
            display == CSS_DISPLAY_TABLE_FOOTER_GROUP || display == CSS_DISPLAY_TABLE_ROW ||
            display == CSS_DISPLAY_TABLE_CELL || display == CSS_DISPLAY_TABLE_CAPTION ||
            display == CSS_DISPLAY_INLINE_BLOCK) {
            return CSS_DISPLAY_BLOCK;
        }
    }

    /* 5. */
    return display;
}

uint8_t css_computed_display_static(const css_computed_style *style)
{
    return get_display(style);
}

/**
 * Get the flex-basis property value in device pixels.
 *
 * \note  If available_px is set to a negative number (invalid) then,
 *        if the computation would have required a valid available
 *        width, it will return CSS_FLEX_BASIS_AUTO.
 *
 * This will resolve `calc()` expressions to used values.
 *
 * \param[in]  style         A computed style.
 * \param[in]  unit_ctx      Unit conversion context.
 * \param[in]  available_px  The available width in pixels.
 * \param[out] px_out        Returns flex-basis in pixels if and only if the
 *                           call returns CSS_FLEX_BASIS_SET.
 * \return CSS_FLEX_BASIS_SET, CSS_FLEX_BASIS_AUTO, or CSS_FLEX_BASIS_CONTENT.
 */
uint8_t
css_computed_flex_basis_px(const css_computed_style *style, const css_unit_ctx *unit_ctx, int available_px, int *px_out)
{
    enum css_flex_basis_e type;
    css_unit unit = CSS_UNIT_PX;
    css_fixed_or_calc value = {.value = 0};

    type = get_flex_basis(style, &value, &unit);
    switch (type) {
    case CSS_FLEX_BASIS_INHERIT:
        break;
    case CSS_FLEX_BASIS_AUTO:
    case CSS_FLEX_BASIS_CONTENT:
        break;
    case CSS_FLEX_BASIS_SET:
        switch (unit) {
        case CSS_UNIT_CALC: {
            css_error err = css_calculator_calculate(
                style->calc, unit_ctx, available_px, value.calc, style, &unit, &value.value);
            if (err == CSS_OK) {
                type = CSS_FLEX_BASIS_SET;
                *px_out = FIXTOINT(css_unit_css2device_px(value.value, unit_ctx->device_dpi));
            } else {
                type = CSS_FLEX_BASIS_AUTO;
            }
        } break;
        case CSS_UNIT_PCT:
            if (available_px < 0) {
                type = CSS_FLEX_BASIS_AUTO;
                break;
            }

            *px_out = FPCT_OF_INT_TOINT(value.value, available_px);
            break;
        default:
            *px_out = FIXTOINT(css_unit_len2device_px(style, unit_ctx, value.value, unit));
            break;
        }
        break;
    }

    return type;
}

uint8_t
css_computed_grid_template_columns(const css_computed_style *style, int32_t *n_tracks, css_computed_grid_track **tracks)
{
    css_computed_grid_track *t = NULL;
    uint8_t type = get_grid_template_columns(style, &t);

    if (tracks != NULL) {
        *tracks = t;
    }

    /* Count tracks if requested */
    if (n_tracks != NULL && t != NULL) {
        int32_t count = 0;
        while (t[count].value != 0 || t[count].unit != 0) {
            count++;
        }
        *n_tracks = count;
    } else if (n_tracks != NULL) {
        *n_tracks = 0;
    }

    return type;
}

uint8_t
css_computed_grid_template_rows(const css_computed_style *style, int32_t *n_tracks, css_computed_grid_track **tracks)
{
    css_computed_grid_track *t = NULL;
    uint8_t type = get_grid_template_rows(style, &t);

    if (tracks != NULL) {
        *tracks = t;
    }

    /* Count tracks if requested */
    if (n_tracks != NULL && t != NULL) {
        int32_t count = 0;
        while (t[count].value != 0 || t[count].unit != 0) {
            count++;
        }
        *n_tracks = count;
    } else if (n_tracks != NULL) {
        *n_tracks = 0;
    }

    return type;
}

uint8_t
css_computed_transform(const css_computed_style *style, uint32_t *n_functions, const css_transform_function **functions)
{
    css_transform_function *funcs = NULL;
    uint32_t count = 0;
    uint8_t type = get_transform(style, &count, &funcs);
    if (n_functions != NULL)
        *n_functions = count;
    if (functions != NULL)
        *functions = funcs;
    return type;
}
