#ifndef WISP_NEW_POLYFILLS_H
#define WISP_NEW_POLYFILLS_H

static const char *new_polyfills_js =
" \n"
"/* ==========================================================================  \n"
"   MODULE 10: DOMIMPLEMENTATION, IMPORTNODE & ADOPTNODE  \n"
"   ========================================================================== */  \n"
"(function() {  \n"
"    'use strict';  \n"
"    const global = globalThis;  \n"
"  \n"
"    class DOMImplementation {  \n"
"        createDocumentType(qualifiedName, publicId, systemId) {  \n"
"            qualifiedName = String(qualifiedName);  \n"
"            publicId = String(publicId || '');  \n"
"            systemId = String(systemId || '');  \n"
"  \n"
"            const dt = Object.create(global.DocumentType ? global.DocumentType.prototype : global.Node.prototype);  \n"
"            dt.name = qualifiedName;  \n"
"            dt.publicId = publicId;  \n"
"            dt.systemId = systemId;  \n"
"            dt.nodeType = 10;  \n"
"            dt.nodeName = qualifiedName;  \n"
"            return dt;  \n"
"        }  \n"
"  \n"
"        createDocument(namespace, qualifiedName, doctype = null) {  \n"
"            const doc = Object.create(global.XMLDocument ? global.XMLDocument.prototype : global.Document.prototype);  \n"
"            doc.nodeType = 9;  \n"
"            doc.nodeName = '#document';  \n"
"            doc.implementation = this;  \n"
"  \n"
"            if (doctype) {  \n"
"                doc.appendChild(doctype);  \n"
"            }  \n"
"            if (qualifiedName) {  \n"
"                const elem = doc.createElementNS(namespace, qualifiedName);  \n"
"                doc.appendChild(elem);  \n"
"            }  \n"
"            return doc;  \n"
"        }  \n"
"  \n"
"        createHTMLDocument(title) {  \n"
"            const doc = Object.create(global.Document.prototype);  \n"
"            doc.nodeType = 9;  \n"
"            doc.nodeName = '#document';  \n"
"            doc.implementation = this;  \n"
"  \n"
"            const html = doc.createElement('html');  \n"
"            const head = doc.createElement('head');  \n"
"            const body = doc.createElement('body');  \n"
"  \n"
"            if (title !== undefined) {  \n"
"                const titleEl = doc.createElement('title');  \n"
"                titleEl.textContent = String(title);  \n"
"                head.appendChild(titleEl);  \n"
"            }  \n"
"  \n"
"            html.appendChild(head);  \n"
"            html.appendChild(body);  \n"
"            doc.appendChild(html);  \n"
"            return doc;  \n"
"        }  \n"
"  \n"
"        hasFeature() {  \n"
"            return true; // Per DOM Level 4 / WHATWG specification  \n"
"        }  \n"
"    }  \n"
"  \n"
"    if (global.Document && Document.prototype) {  \n"
"        const proto = Document.prototype;  \n"
"  \n"
"        proto.importNode = function(node, deep = false) {  \n"
"            if (!node || !node.nodeType) {  \n"
"                throw new TypeError(\"Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.\");  \n"
"            }  \n"
"            if (node.nodeType === 9) { // DOCUMENT_NODE  \n"
"                throw new DOMException(\"Cannot import a Document node.\", \"NotSupportedError\");  \n"
"            }  \n"
"  \n"
"            let clone;  \n"
"            switch (node.nodeType) {  \n"
"                case 1: // ELEMENT_NODE  \n"
"                    clone = this.createElementNS(node.namespaceURI, node.tagName || node.nodeName);  \n"
"                    if (node.attributes) {  \n"
"                        for (let i = 0; i < node.attributes.length; i++) {  \n"
"                            const attr = node.attributes[i];  \n"
"                            clone.setAttributeNS(attr.namespaceURI, attr.name, attr.value);  \n"
"                        }  \n"
"                    }  \n"
"                    break;  \n"
"                case 3: // TEXT_NODE  \n"
"                    clone = this.createTextNode(node.nodeValue || node.data || '');  \n"
"                    break;  \n"
"                case 8: // COMMENT_NODE  \n"
"                    clone = this.createComment(node.nodeValue || node.data || '');  \n"
"                    break;  \n"
"                case 11: // DOCUMENT_FRAGMENT_NODE  \n"
"                    clone = this.createDocumentFragment();  \n"
"                    break;  \n"
"                default:  \n"
"                    clone = node.cloneNode(false);  \n"
"                    break;  \n"
"            }  \n"
"  \n"
"            if (deep && node.childNodes) {  \n"
"                for (let i = 0; i < node.childNodes.length; i++) {  \n"
"                    clone.appendChild(this.importNode(node.childNodes[i], true));  \n"
"                }  \n"
"            }  \n"
"            return clone;  \n"
"        };  \n"
"  \n"
"        proto.adoptNode = function(node) {  \n"
"            if (!node || !node.nodeType) {  \n"
"                throw new TypeError(\"Failed to execute 'adoptNode' on 'Document': parameter 1 is not of type 'Node'.\");  \n"
"            }  \n"
"            if (node.nodeType === 9) {  \n"
"                throw new DOMException(\"Cannot adopt a Document node.\", \"NotSupportedError\");  \n"
"            }  \n"
"            if (node.nodeType === 10) {  \n"
"                throw new DOMException(\"Cannot adopt a DocumentType node.\", \"HierarchyRequestError\");  \n"
"            }  \n"
"  \n"
"            const oldDoc = node.ownerDocument;  \n"
"            if (node.parentNode) {  \n"
"                node.parentNode.removeChild(node);  \n"
"            }  \n"
"  \n"
"            function setOwnerDoc(n, targetDoc) {  \n"
"                n.ownerDocument = targetDoc;  \n"
"                if (n.childNodes) {  \n"
"                    for (let i = 0; i < n.childNodes.length; i++) {  \n"
"                        setOwnerDoc(n.childNodes[i], targetDoc);  \n"
"                    }  \n"
"                }  \n"
"            }  \n"
"            setOwnerDoc(node, this);  \n"
"  \n"
"            if (global.customElements && global.customElements.__on_adopt) {  \n"
"                global.customElements.__on_adopt(node, oldDoc, this);  \n"
"            }  \n"
"  \n"
"            return node;  \n"
"        };  \n"
"    }  \n"
"  \n"
"    if (global.document && !global.document.implementation) {  \n"
"        global.document.implementation = new DOMImplementation();  \n"
"    }  \n"
"    global.DOMImplementation = DOMImplementation;  \n"
"})(); \n"

"/* ==========================================================================  \n"
"   MODULE 11: TABULAR DOM & MUTATION ENGINE  \n"
"   ========================================================================== */  \n"
"(function() {  \n"
"    'use strict';  \n"
"    const global = globalThis;  \n"
"  \n"
"    function getTableChildrenByTag(parent, tagName) {  \n"
"        const results = [];  \n"
"        const ch = parent.childNodes || [];  \n"
"        for (let i = 0; i < ch.length; i++) {  \n"
"            if (ch[i].nodeType === 1 && ch[i].tagName.toLowerCase() === tagName.toLowerCase()) {  \n"
"                results.push(ch[i]);  \n"
"            }  \n"
"        }  \n"
"        return results;  \n"
"    }  \n"
"  \n"
"    /* --------------------------------------------------------------------------  \n"
"     * HTMLTableElement  \n"
"     * -------------------------------------------------------------------------- */  \n"
"    if (global.HTMLTableElement && HTMLTableElement.prototype) {  \n"
"        const proto = HTMLTableElement.prototype;  \n"
"  \n"
"        Object.defineProperty(proto, 'caption', {  \n"
"            get() { return getTableChildrenByTag(this, 'caption')[0] || null; },  \n"
"            set(val) {  \n"
"                const old = this.caption;  \n"
"                if (old) this.removeChild(old);  \n"
"                if (val) this.insertBefore(val, this.firstChild);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createCaption = function() {  \n"
"            let cap = this.caption;  \n"
"            if (!cap) {  \n"
"                cap = this.ownerDocument.createElement('caption');  \n"
"                this.insertBefore(cap, this.firstChild);  \n"
"            }  \n"
"            return cap;  \n"
"        };  \n"
"  \n"
"        proto.deleteCaption = function() {  \n"
"            const cap = this.caption;  \n"
"            if (cap) this.removeChild(cap);  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'tHead', {  \n"
"            get() { return getTableChildrenByTag(this, 'thead')[0] || null; },  \n"
"            set(val) {  \n"
"                const old = this.tHead;  \n"
"                if (old) this.removeChild(old);  \n"
"                if (val) {  \n"
"                    const cap = this.caption;  \n"
"                    this.insertBefore(val, cap ? cap.nextSibling : this.firstChild);  \n"
"                }  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createTHead = function() {  \n"
"            let th = this.tHead;  \n"
"            if (!th) {  \n"
"                th = this.ownerDocument.createElement('thead');  \n"
"                const cap = this.caption;  \n"
"                this.insertBefore(th, cap ? cap.nextSibling : this.firstChild);  \n"
"            }  \n"
"            return th;  \n"
"        };  \n"
"  \n"
"        proto.deleteTHead = function() {  \n"
"            const th = this.tHead;  \n"
"            if (th) this.removeChild(th);  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'tFoot', {  \n"
"            get() { return getTableChildrenByTag(this, 'tfoot')[0] || null; },  \n"
"            set(val) {  \n"
"                const old = this.tFoot;  \n"
"                if (old) this.removeChild(old);  \n"
"                if (val) this.appendChild(val);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createTFoot = function() {  \n"
"            let tf = this.tFoot;  \n"
"            if (!tf) {  \n"
"                tf = this.ownerDocument.createElement('tfoot');  \n"
"                this.appendChild(tf);  \n"
"            }  \n"
"            return tf;  \n"
"        };  \n"
"  \n"
"        proto.deleteTFoot = function() {  \n"
"            const tf = this.tFoot;  \n"
"            if (tf) this.removeChild(tf);  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'tBodies', {  \n"
"            get() { return getTableChildrenByTag(this, 'tbody'); },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createTBody = function() {  \n"
"            const tb = this.ownerDocument.createElement('tbody');  \n"
"            const tf = this.tFoot;  \n"
"            this.insertBefore(tb, tf || null);  \n"
"            return tb;  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'rows', {  \n"
"            get() {  \n"
"                const rowList = [];  \n"
"                if (this.tHead) rowList.push(...getTableChildrenByTag(this.tHead, 'tr'));  \n"
"                for (let tbody of this.tBodies) {  \n"
"                    rowList.push(...getTableChildrenByTag(tbody, 'tr'));  \n"
"                }  \n"
"                rowList.push(...getTableChildrenByTag(this, 'tr'));  \n"
"                if (this.tFoot) rowList.push(...getTableChildrenByTag(this.tFoot, 'tr'));  \n"
"                return rowList;  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.insertRow = function(index = -1) {  \n"
"            const allRows = this.rows;  \n"
"            if (index < -1 || index > allRows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const tr = this.ownerDocument.createElement('tr');  \n"
"            if (allRows.length === 0) {  \n"
"                let tb = this.tBodies[0] || this.createTBody();  \n"
"                tb.appendChild(tr);  \n"
"            } else if (index === -1 || index === allRows.length) {  \n"
"                const lastRow = allRows[allRows.length - 1];  \n"
"                lastRow.parentNode.appendChild(tr);  \n"
"            } else {  \n"
"                const targetRow = allRows[index];  \n"
"                targetRow.parentNode.insertBefore(tr, targetRow);  \n"
"            }  \n"
"            return tr;  \n"
"        };  \n"
"  \n"
"        proto.deleteRow = function(index) {  \n"
"            const allRows = this.rows;  \n"
"            if (index === -1) index = allRows.length - 1;  \n"
"            if (index < 0 || index >= allRows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const targetRow = allRows[index];  \n"
"            targetRow.parentNode.removeChild(targetRow);  \n"
"        };  \n"
"    }  \n"
"  \n"
"    /* --------------------------------------------------------------------------  \n"
"     * HTMLTableSectionElement  \n"
"     * -------------------------------------------------------------------------- */  \n"
"    if (global.HTMLTableSectionElement && HTMLTableSectionElement.prototype) {  \n"
"        const proto = HTMLTableSectionElement.prototype;  \n"
"  \n"
"        Object.defineProperty(proto, 'rows', {  \n"
"            get() { return getTableChildrenByTag(this, 'tr'); },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.insertRow = function(index = -1) {  \n"
"            const rows = this.rows;  \n"
"            if (index < -1 || index > rows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const tr = this.ownerDocument.createElement('tr');  \n"
"            if (index === -1 || index === rows.length) {  \n"
"                this.appendChild(tr);  \n"
"            } else {  \n"
"                this.insertBefore(tr, rows[index]);  \n"
"            }  \n"
"            return tr;  \n"
"        };  \n"
"  \n"
"        proto.deleteRow = function(index) {  \n"
"            const rows = this.rows;  \n"
"            if (index === -1) index = rows.length - 1;  \n"
"            if (index < 0 || index >= rows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            this.removeChild(rows[index]);  \n"
"        };  \n"
"    }  \n"
"  \n"
"    /* --------------------------------------------------------------------------  \n"
"     * HTMLTableRowElement & HTMLTableCellElement  \n"
"     * -------------------------------------------------------------------------- */  \n"
"    if (global.HTMLTableRowElement && HTMLTableRowElement.prototype) {  \n"
"        const proto = HTMLTableRowElement.prototype;  \n"
"  \n"
"        Object.defineProperty(proto, 'cells', {  \n"
"            get() {  \n"
"                const list = [];  \n"
"                const ch = this.childNodes || [];  \n"
"                for (let i = 0; i < ch.length; i++) {  \n"
"                    if (ch[i].nodeType === 1 && (ch[i].tagName.toLowerCase() === 'td' || ch[i].tagName.toLowerCase() === 'th')) {  \n"
"                        list.push(ch[i]);  \n"
"                    }  \n"
"                }  \n"
"                return list;  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        Object.defineProperty(proto, 'rowIndex', {  \n"
"            get() {  \n"
"                let table = this.parentNode;  \n"
"                while (table && table.tagName.toLowerCase() !== 'table') table = table.parentNode;  \n"
"                if (!table) return -1;  \n"
"                return table.rows.indexOf(this);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        Object.defineProperty(proto, 'sectionRowIndex', {  \n"
"            get() {  \n"
"                if (!this.parentNode) return -1;  \n"
"                return getTableChildrenByTag(this.parentNode, 'tr').indexOf(this);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.insertCell = function(index = -1) {  \n"
"            const cells = this.cells;  \n"
"            if (index < -1 || index > cells.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const td = this.ownerDocument.createElement('td');  \n"
"            if (index === -1 || index === cells.length) {  \n"
"                this.appendChild(td);  \n"
"            } else {  \n"
"                this.insertBefore(td, cells[index]);  \n"
"            }  \n"
"            return td;  \n"
"        };  \n"
"  \n"
"        proto.deleteCell = function(index) {  \n"
"            const cells = this.cells;  \n"
"            if (index === -1) index = cells.length - 1;  \n"
"            if (index < 0 || index >= cells.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            this.removeChild(cells[index]);  \n"
"        };  \n"
"    }  \n"
"  \n"
"    if (global.HTMLTableCellElement && HTMLTableCellElement.prototype) {  \n"
"        Object.defineProperty(HTMLTableCellElement.prototype, 'cellIndex', {  \n"
"            get() {  \n"
"                if (!this.parentNode || this.parentNode.tagName.toLowerCase() !== 'tr') return -1;  \n"
"                return this.parentNode.cells.indexOf(this);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"    }  \n"
"})(); \n"


"/* ========================================================================== MODULE 9: DOM PARSING & SERIALIZATION SUBSYSTEM ========================================================================== */  \n"
"(function() { 'use strict'; const global = globalThis; \n"
" \n"
"class DOMParser { parseFromString(string, type) { string = String(string); type = String(type).toLowerCase(); \n"
" \n"
"    if (type === 'text/html') {  \n"
"        const doc = document.implementation.createHTMLDocument('');  \n"
"        doc.documentElement.innerHTML = string;  \n"
"        return doc;  \n"
"    }  \n"
" \n"
"    if (type === 'text/xml' || type === 'application/xml' || type === 'application/xhtml+xml' || type === 'image/svg+xml') {  \n"
"        const doc = document.implementation.createDocument(  \n"
"            type === 'image/svg+xml' ? 'http://www.w3.org/2000/svg' : (type === 'application/xhtml+xml' ? 'http://www.w3.org/1999/xhtml' : null),  \n"
"            '',  \n"
"            null  \n"
"        );  \n"
" \n"
"        // Reconstruct basic tree representation  \n"
"        const template = document.createElement('template');  \n"
"        template.innerHTML = string;  \n"
"        const root = template.content ? template.content.firstChild : template.firstChild;  \n"
" \n"
"        if (root) {  \n"
"            const imported = doc.importNode(root, true);  \n"
"            doc.appendChild(imported);  \n"
"        } else {  \n"
"            const parserError = doc.createElementNS('http://www.mozilla.org/newlayout/xml/parsererror.xml', 'parsererror');  \n"
"            parserError.textContent = 'XML Parsing Error';  \n"
"            doc.appendChild(parserError);  \n"
"        }  \n"
"        return doc;  \n"
"    }  \n"
" \n"
"    throw new TypeError(`Failed to execute 'parseFromString' on 'DOMParser': The provided value '${type}' is not a valid enum value of type SupportedType.`);  \n"
"}  \n"
"} \n"
" \n"
"if (global.Element && Element.prototype) { const proto = Element.prototype; \n"
" \n"
"proto.insertAdjacentHTML = function(position, text) {  \n"
"    position = String(position).toLowerCase().trim();  \n"
"    const doc = this.ownerDocument || document;  \n"
"    const container = doc.createElement('template');  \n"
"    container.innerHTML = String(text);  \n"
"    const fragment = container.content || (function() {  \n"
"        const frag = doc.createDocumentFragment();  \n"
"        while (container.firstChild) frag.appendChild(container.firstChild);  \n"
"        return frag;  \n"
"    })();  \n"
" \n"
"    switch (position) {  \n"
"        case 'beforebegin':  \n"
"            if (!this.parentNode) {  \n"
"                throw new DOMException(\"Cannot insert HTML before an element without a parent.\", \"InvalidStateError\");  \n"
"            }  \n"
"            this.parentNode.insertBefore(fragment, this);  \n"
"            break;  \n"
"        case 'afterbegin':  \n"
"            this.insertBefore(fragment, this.firstChild);  \n"
"            break;  \n"
"        case 'beforeend':  \n"
"            this.appendChild(fragment);  \n"
"            break;  \n"
"        case 'afterend':  \n"
"            if (!this.parentNode) {  \n"
"                throw new DOMException(\"Cannot insert HTML after an element without a parent.\", \"InvalidStateError\");  \n"
"            }  \n"
"            this.parentNode.insertBefore(fragment, this.nextSibling);  \n"
"            break;  \n"
"        default:  \n"
"            throw new DOMException(`Failed to execute 'insertAdjacentHTML' on 'Element': The position provided ('${position}') is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.`, \"SyntaxError\");  \n"
"    }  \n"
"};  \n"
" \n"
"Object.defineProperty(proto, 'outerHTML', {  \n"
"    get() {  \n"
"        const serializer = new global.XMLSerializer();  \n"
"        return serializer.serializeToString(this);  \n"
"    },  \n"
"    set(htmlText) {  \n"
"        const parent = this.parentNode;  \n"
"        if (!parent) {  \n"
"            throw new DOMException(\"Cannot set outerHTML on an element with no parent node.\", \"NoModificationAllowedError\");  \n"
"        }  \n"
"        const doc = this.ownerDocument || document;  \n"
"        const template = doc.createElement('template');  \n"
"        template.innerHTML = String(htmlText);  \n"
"        const fragment = template.content || (function() {  \n"
"            const frag = doc.createDocumentFragment();  \n"
"            while (template.firstChild) frag.appendChild(template.firstChild);  \n"
"            return frag;  \n"
"        })();  \n"
"        parent.replaceChild(fragment, this);  \n"
"    },  \n"
"    configurable: true,  \n"
"    enumerable: true  \n"
"});  \n"
"} \n"
" \n"
"global.DOMParser = DOMParser; })(); \n"
;

#endif /* WISP_NEW_POLYFILLS_H */
