#ifndef WISP_NEW_POLYFILLS_H
#define WISP_NEW_POLYFILLS_H

static const char *new_polyfills_js =
" \n"
"/* ==========================================================================  \n"
"   MODULE 10: DOMIMPLEMENTATION, IMPORTNODE & ADOPTNODE  \n"
"   ========================================================================== */  \n"
"(function() {  \n"
"    'use strict';  \n"
"    const global = globalThis;  \n"
"  \n"
"    class DOMImplementation {  \n"
"        createDocumentType(qualifiedName, publicId, systemId) {  \n"
"            qualifiedName = String(qualifiedName);  \n"
"            publicId = String(publicId || '');  \n"
"            systemId = String(systemId || '');  \n"
"  \n"
"            const dt = Object.create(global.DocumentType ? global.DocumentType.prototype : global.Node.prototype);  \n"
"            dt.name = qualifiedName;  \n"
"            dt.publicId = publicId;  \n"
"            dt.systemId = systemId;  \n"
"            dt.nodeType = 10;  \n"
"            dt.nodeName = qualifiedName;  \n"
"            return dt;  \n"
"        }  \n"
"  \n"
"        createDocument(namespace, qualifiedName, doctype = null) {  \n"
"            const doc = Object.create(global.XMLDocument ? global.XMLDocument.prototype : global.Document.prototype);  \n"
"            doc.nodeType = 9;  \n"
"            doc.nodeName = '#document';  \n"
"            doc.implementation = this;  \n"
"  \n"
"            if (doctype) {  \n"
"                doc.appendChild(doctype);  \n"
"            }  \n"
"            if (qualifiedName) {  \n"
"                const elem = doc.createElementNS(namespace, qualifiedName);  \n"
"                doc.appendChild(elem);  \n"
"            }  \n"
"            return doc;  \n"
"        }  \n"
"  \n"
"        createHTMLDocument(title) {  \n"
"            const doc = Object.create(global.Document.prototype);  \n"
"            doc.nodeType = 9;  \n"
"            doc.nodeName = '#document';  \n"
"            doc.implementation = this;  \n"
"  \n"
"            const html = doc.createElement('html');  \n"
"            const head = doc.createElement('head');  \n"
"            const body = doc.createElement('body');  \n"
"  \n"
"            if (title !== undefined) {  \n"
"                const titleEl = doc.createElement('title');  \n"
"                titleEl.textContent = String(title);  \n"
"                head.appendChild(titleEl);  \n"
"            }  \n"
"  \n"
"            html.appendChild(head);  \n"
"            html.appendChild(body);  \n"
"            doc.appendChild(html);  \n"
"            return doc;  \n"
"        }  \n"
"  \n"
"        hasFeature() {  \n"
"            return true; // Per DOM Level 4 / WHATWG specification  \n"
"        }  \n"
"    }  \n"
"  \n"
"    if (global.Document && Document.prototype) {  \n"
"        const proto = Document.prototype;  \n"
"  \n"
"        proto.importNode = function(node, deep = false) {  \n"
"            if (!node || !node.nodeType) {  \n"
"                throw new TypeError(\"Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.\");  \n"
"            }  \n"
"            if (node.nodeType === 9) { // DOCUMENT_NODE  \n"
"                throw new DOMException(\"Cannot import a Document node.\", \"NotSupportedError\");  \n"
"            }  \n"
"  \n"
"            let clone;  \n"
"            switch (node.nodeType) {  \n"
"                case 1: // ELEMENT_NODE  \n"
"                    clone = this.createElementNS(node.namespaceURI, node.tagName || node.nodeName);  \n"
"                    if (node.attributes) {  \n"
"                        for (let i = 0; i < node.attributes.length; i++) {  \n"
"                            const attr = node.attributes[i];  \n"
"                            clone.setAttributeNS(attr.namespaceURI, attr.name, attr.value);  \n"
"                        }  \n"
"                    }  \n"
"                    break;  \n"
"                case 3: // TEXT_NODE  \n"
"                    clone = this.createTextNode(node.nodeValue || node.data || '');  \n"
"                    break;  \n"
"                case 8: // COMMENT_NODE  \n"
"                    clone = this.createComment(node.nodeValue || node.data || '');  \n"
"                    break;  \n"
"                case 11: // DOCUMENT_FRAGMENT_NODE  \n"
"                    clone = this.createDocumentFragment();  \n"
"                    break;  \n"
"                default:  \n"
"                    clone = node.cloneNode(false);  \n"
"                    break;  \n"
"            }  \n"
"  \n"
"            if (deep && node.childNodes) {  \n"
"                for (let i = 0; i < node.childNodes.length; i++) {  \n"
"                    clone.appendChild(this.importNode(node.childNodes[i], true));  \n"
"                }  \n"
"            }  \n"
"            return clone;  \n"
"        };  \n"
"  \n"
"        proto.adoptNode = function(node) {  \n"
"            if (!node || !node.nodeType) {  \n"
"                throw new TypeError(\"Failed to execute 'adoptNode' on 'Document': parameter 1 is not of type 'Node'.\");  \n"
"            }  \n"
"            if (node.nodeType === 9) {  \n"
"                throw new DOMException(\"Cannot adopt a Document node.\", \"NotSupportedError\");  \n"
"            }  \n"
"            if (node.nodeType === 10) {  \n"
"                throw new DOMException(\"Cannot adopt a DocumentType node.\", \"HierarchyRequestError\");  \n"
"            }  \n"
"  \n"
"            const oldDoc = node.ownerDocument;  \n"
"            if (node.parentNode) {  \n"
"                node.parentNode.removeChild(node);  \n"
"            }  \n"
"  \n"
"            function setOwnerDoc(n, targetDoc) {  \n"
"                n.ownerDocument = targetDoc;  \n"
"                if (n.childNodes) {  \n"
"                    for (let i = 0; i < n.childNodes.length; i++) {  \n"
"                        setOwnerDoc(n.childNodes[i], targetDoc);  \n"
"                    }  \n"
"                }  \n"
"            }  \n"
"            setOwnerDoc(node, this);  \n"
"  \n"
"            if (global.customElements && global.customElements.__on_adopt) {  \n"
"                global.customElements.__on_adopt(node, oldDoc, this);  \n"
"            }  \n"
"  \n"
"            return node;  \n"
"        };  \n"
"    }  \n"
"  \n"
"    if (global.document && !global.document.implementation) {  \n"
"        global.document.implementation = new DOMImplementation();  \n"
"    }  \n"
"    global.DOMImplementation = DOMImplementation;  \n"
"})(); \n"

"/* ==========================================================================  \n"
"   MODULE 11: TABULAR DOM & MUTATION ENGINE  \n"
"   ========================================================================== */  \n"
"(function() {  \n"
"    'use strict';  \n"
"    const global = globalThis;  \n"
"  \n"
"    function getTableChildrenByTag(parent, tagName) {  \n"
"        const results = [];  \n"
"        const ch = parent.childNodes || [];  \n"
"        for (let i = 0; i < ch.length; i++) {  \n"
"            if (ch[i].nodeType === 1 && ch[i].tagName.toLowerCase() === tagName.toLowerCase()) {  \n"
"                results.push(ch[i]);  \n"
"            }  \n"
"        }  \n"
"        return results;  \n"
"    }  \n"
"  \n"
"    /* --------------------------------------------------------------------------  \n"
"     * HTMLTableElement  \n"
"     * -------------------------------------------------------------------------- */  \n"
"    if (global.HTMLTableElement && HTMLTableElement.prototype) {  \n"
"        const proto = HTMLTableElement.prototype;  \n"
"  \n"
"        Object.defineProperty(proto, 'caption', {  \n"
"            get() { return getTableChildrenByTag(this, 'caption')[0] || null; },  \n"
"            set(val) {  \n"
"                const old = this.caption;  \n"
"                if (old) this.removeChild(old);  \n"
"                if (val) this.insertBefore(val, this.firstChild);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createCaption = function() {  \n"
"            let cap = this.caption;  \n"
"            if (!cap) {  \n"
"                cap = this.ownerDocument.createElement('caption');  \n"
"                this.insertBefore(cap, this.firstChild);  \n"
"            }  \n"
"            return cap;  \n"
"        };  \n"
"  \n"
"        proto.deleteCaption = function() {  \n"
"            const cap = this.caption;  \n"
"            if (cap) this.removeChild(cap);  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'tHead', {  \n"
"            get() { return getTableChildrenByTag(this, 'thead')[0] || null; },  \n"
"            set(val) {  \n"
"                const old = this.tHead;  \n"
"                if (old) this.removeChild(old);  \n"
"                if (val) {  \n"
"                    const cap = this.caption;  \n"
"                    this.insertBefore(val, cap ? cap.nextSibling : this.firstChild);  \n"
"                }  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createTHead = function() {  \n"
"            let th = this.tHead;  \n"
"            if (!th) {  \n"
"                th = this.ownerDocument.createElement('thead');  \n"
"                const cap = this.caption;  \n"
"                this.insertBefore(th, cap ? cap.nextSibling : this.firstChild);  \n"
"            }  \n"
"            return th;  \n"
"        };  \n"
"  \n"
"        proto.deleteTHead = function() {  \n"
"            const th = this.tHead;  \n"
"            if (th) this.removeChild(th);  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'tFoot', {  \n"
"            get() { return getTableChildrenByTag(this, 'tfoot')[0] || null; },  \n"
"            set(val) {  \n"
"                const old = this.tFoot;  \n"
"                if (old) this.removeChild(old);  \n"
"                if (val) this.appendChild(val);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createTFoot = function() {  \n"
"            let tf = this.tFoot;  \n"
"            if (!tf) {  \n"
"                tf = this.ownerDocument.createElement('tfoot');  \n"
"                this.appendChild(tf);  \n"
"            }  \n"
"            return tf;  \n"
"        };  \n"
"  \n"
"        proto.deleteTFoot = function() {  \n"
"            const tf = this.tFoot;  \n"
"            if (tf) this.removeChild(tf);  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'tBodies', {  \n"
"            get() { return getTableChildrenByTag(this, 'tbody'); },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.createTBody = function() {  \n"
"            const tb = this.ownerDocument.createElement('tbody');  \n"
"            const tf = this.tFoot;  \n"
"            this.insertBefore(tb, tf || null);  \n"
"            return tb;  \n"
"        };  \n"
"  \n"
"        Object.defineProperty(proto, 'rows', {  \n"
"            get() {  \n"
"                const rowList = [];  \n"
"                if (this.tHead) rowList.push(...getTableChildrenByTag(this.tHead, 'tr'));  \n"
"                for (let tbody of this.tBodies) {  \n"
"                    rowList.push(...getTableChildrenByTag(tbody, 'tr'));  \n"
"                }  \n"
"                rowList.push(...getTableChildrenByTag(this, 'tr'));  \n"
"                if (this.tFoot) rowList.push(...getTableChildrenByTag(this.tFoot, 'tr'));  \n"
"                return rowList;  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.insertRow = function(index = -1) {  \n"
"            const allRows = this.rows;  \n"
"            if (index < -1 || index > allRows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const tr = this.ownerDocument.createElement('tr');  \n"
"            if (allRows.length === 0) {  \n"
"                let tb = this.tBodies[0] || this.createTBody();  \n"
"                tb.appendChild(tr);  \n"
"            } else if (index === -1 || index === allRows.length) {  \n"
"                const lastRow = allRows[allRows.length - 1];  \n"
"                lastRow.parentNode.appendChild(tr);  \n"
"            } else {  \n"
"                const targetRow = allRows[index];  \n"
"                targetRow.parentNode.insertBefore(tr, targetRow);  \n"
"            }  \n"
"            return tr;  \n"
"        };  \n"
"  \n"
"        proto.deleteRow = function(index) {  \n"
"            const allRows = this.rows;  \n"
"            if (index === -1) index = allRows.length - 1;  \n"
"            if (index < 0 || index >= allRows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const targetRow = allRows[index];  \n"
"            targetRow.parentNode.removeChild(targetRow);  \n"
"        };  \n"
"    }  \n"
"  \n"
"    /* --------------------------------------------------------------------------  \n"
"     * HTMLTableSectionElement  \n"
"     * -------------------------------------------------------------------------- */  \n"
"    if (global.HTMLTableSectionElement && HTMLTableSectionElement.prototype) {  \n"
"        const proto = HTMLTableSectionElement.prototype;  \n"
"  \n"
"        Object.defineProperty(proto, 'rows', {  \n"
"            get() { return getTableChildrenByTag(this, 'tr'); },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.insertRow = function(index = -1) {  \n"
"            const rows = this.rows;  \n"
"            if (index < -1 || index > rows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const tr = this.ownerDocument.createElement('tr');  \n"
"            if (index === -1 || index === rows.length) {  \n"
"                this.appendChild(tr);  \n"
"            } else {  \n"
"                this.insertBefore(tr, rows[index]);  \n"
"            }  \n"
"            return tr;  \n"
"        };  \n"
"  \n"
"        proto.deleteRow = function(index) {  \n"
"            const rows = this.rows;  \n"
"            if (index === -1) index = rows.length - 1;  \n"
"            if (index < 0 || index >= rows.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            this.removeChild(rows[index]);  \n"
"        };  \n"
"    }  \n"
"  \n"
"    /* --------------------------------------------------------------------------  \n"
"     * HTMLTableRowElement & HTMLTableCellElement  \n"
"     * -------------------------------------------------------------------------- */  \n"
"    if (global.HTMLTableRowElement && HTMLTableRowElement.prototype) {  \n"
"        const proto = HTMLTableRowElement.prototype;  \n"
"  \n"
"        Object.defineProperty(proto, 'cells', {  \n"
"            get() {  \n"
"                const list = [];  \n"
"                const ch = this.childNodes || [];  \n"
"                for (let i = 0; i < ch.length; i++) {  \n"
"                    if (ch[i].nodeType === 1 && (ch[i].tagName.toLowerCase() === 'td' || ch[i].tagName.toLowerCase() === 'th')) {  \n"
"                        list.push(ch[i]);  \n"
"                    }  \n"
"                }  \n"
"                return list;  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        Object.defineProperty(proto, 'rowIndex', {  \n"
"            get() {  \n"
"                let table = this.parentNode;  \n"
"                while (table && table.tagName.toLowerCase() !== 'table') table = table.parentNode;  \n"
"                if (!table) return -1;  \n"
"                return table.rows.indexOf(this);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        Object.defineProperty(proto, 'sectionRowIndex', {  \n"
"            get() {  \n"
"                if (!this.parentNode) return -1;  \n"
"                return getTableChildrenByTag(this.parentNode, 'tr').indexOf(this);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"  \n"
"        proto.insertCell = function(index = -1) {  \n"
"            const cells = this.cells;  \n"
"            if (index < -1 || index > cells.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            const td = this.ownerDocument.createElement('td');  \n"
"            if (index === -1 || index === cells.length) {  \n"
"                this.appendChild(td);  \n"
"            } else {  \n"
"                this.insertBefore(td, cells[index]);  \n"
"            }  \n"
"            return td;  \n"
"        };  \n"
"  \n"
"        proto.deleteCell = function(index) {  \n"
"            const cells = this.cells;  \n"
"            if (index === -1) index = cells.length - 1;  \n"
"            if (index < 0 || index >= cells.length) {  \n"
"                throw new DOMException(\"The index provided is out of bounds.\", \"IndexSizeError\");  \n"
"            }  \n"
"            this.removeChild(cells[index]);  \n"
"        };  \n"
"    }  \n"
"  \n"
"    if (global.HTMLTableCellElement && HTMLTableCellElement.prototype) {  \n"
"        Object.defineProperty(HTMLTableCellElement.prototype, 'cellIndex', {  \n"
"            get() {  \n"
"                if (!this.parentNode || this.parentNode.tagName.toLowerCase() !== 'tr') return -1;  \n"
"                return this.parentNode.cells.indexOf(this);  \n"
"            },  \n"
"            configurable: true, enumerable: true  \n"
"        });  \n"
"    }  \n"
"})(); \n"


"/* ========================================================================== MODULE 9: DOM PARSING & SERIALIZATION SUBSYSTEM ========================================================================== */  \n"
"(function() { 'use strict'; const global = globalThis; \n"
" \n"
"class DOMParser { parseFromString(string, type) { string = String(string); type = String(type).toLowerCase(); \n"
" \n"
"    if (type === 'text/html') {  \n"
"        const doc = document.implementation.createHTMLDocument('');  \n"
"        doc.documentElement.innerHTML = string;  \n"
"        return doc;  \n"
"    }  \n"
" \n"
"    if (type === 'text/xml' || type === 'application/xml' || type === 'application/xhtml+xml' || type === 'image/svg+xml') {  \n"
"        const doc = document.implementation.createDocument(  \n"
"            type === 'image/svg+xml' ? 'http://www.w3.org/2000/svg' : (type === 'application/xhtml+xml' ? 'http://www.w3.org/1999/xhtml' : null),  \n"
"            '',  \n"
"            null  \n"
"        );  \n"
" \n"
"        // Reconstruct basic tree representation  \n"
"        const template = document.createElement('template');  \n"
"        template.innerHTML = string;  \n"
"        const root = template.content ? template.content.firstChild : template.firstChild;  \n"
" \n"
"        if (root) {  \n"
"            const imported = doc.importNode(root, true);  \n"
"            doc.appendChild(imported);  \n"
"        } else {  \n"
"            const parserError = doc.createElementNS('http://www.mozilla.org/newlayout/xml/parsererror.xml', 'parsererror');  \n"
"            parserError.textContent = 'XML Parsing Error';  \n"
"            doc.appendChild(parserError);  \n"
"        }  \n"
"        return doc;  \n"
"    }  \n"
" \n"
"    throw new TypeError(`Failed to execute 'parseFromString' on 'DOMParser': The provided value '${type}' is not a valid enum value of type SupportedType.`);  \n"
"}  \n"
"} \n"
" \n"
"if (global.Element && Element.prototype) { const proto = Element.prototype; \n"
" \n"
"proto.insertAdjacentHTML = function(position, text) {  \n"
"    position = String(position).toLowerCase().trim();  \n"
"    const doc = this.ownerDocument || document;  \n"
"    const container = doc.createElement('template');  \n"
"    container.innerHTML = String(text);  \n"
"    const fragment = container.content || (function() {  \n"
"        const frag = doc.createDocumentFragment();  \n"
"        while (container.firstChild) frag.appendChild(container.firstChild);  \n"
"        return frag;  \n"
"    })();  \n"
" \n"
"    switch (position) {  \n"
"        case 'beforebegin':  \n"
"            if (!this.parentNode) {  \n"
"                throw new DOMException(\"Cannot insert HTML before an element without a parent.\", \"InvalidStateError\");  \n"
"            }  \n"
"            this.parentNode.insertBefore(fragment, this);  \n"
"            break;  \n"
"        case 'afterbegin':  \n"
"            this.insertBefore(fragment, this.firstChild);  \n"
"            break;  \n"
"        case 'beforeend':  \n"
"            this.appendChild(fragment);  \n"
"            break;  \n"
"        case 'afterend':  \n"
"            if (!this.parentNode) {  \n"
"                throw new DOMException(\"Cannot insert HTML after an element without a parent.\", \"InvalidStateError\");  \n"
"            }  \n"
"            this.parentNode.insertBefore(fragment, this.nextSibling);  \n"
"            break;  \n"
"        default:  \n"
"            throw new DOMException(`Failed to execute 'insertAdjacentHTML' on 'Element': The position provided ('${position}') is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.`, \"SyntaxError\");  \n"
"    }  \n"
"};  \n"
" \n"
"Object.defineProperty(proto, 'outerHTML', {  \n"
"    get() {  \n"
"        const serializer = new global.XMLSerializer();  \n"
"        return serializer.serializeToString(this);  \n"
"    },  \n"
"    set(htmlText) {  \n"
"        const parent = this.parentNode;  \n"
"        if (!parent) {  \n"
"            throw new DOMException(\"Cannot set outerHTML on an element with no parent node.\", \"NoModificationAllowedError\");  \n"
"        }  \n"
"        const doc = this.ownerDocument || document;  \n"
"        const template = doc.createElement('template');  \n"
"        template.innerHTML = String(htmlText);  \n"
"        const fragment = template.content || (function() {  \n"
"            const frag = doc.createDocumentFragment();  \n"
"            while (template.firstChild) frag.appendChild(template.firstChild);  \n"
"            return frag;  \n"
"        })();  \n"
"        parent.replaceChild(fragment, this);  \n"
"    },  \n"
"    configurable: true,  \n"
"    enumerable: true  \n"
"});  \n"
"} \n"
" \n"
"global.DOMParser = DOMParser; })(); \n"

"/* ==========================================================================  \n"
"/* ==========================================================================   \n"
"/* ==========================================================================   \n"
"/* ==========================================================================   \n"
"/* ==========================================================================   \n"
"/* ==========================================================================   \n"
"/* ==========================================================================   \n"
"   MODULE 12: STORAGE & FILES (Blob, File, FileReader, IndexedDB)   \n"
"   ========================================================================== */   \n"
"(function() {   \n"
"    'use strict';   \n"
"    const global = globalThis;   \n"
"   \n"
"    /* --------------------------------------------------------------------------   \n"
"     * Blob & File   \n"
"     * -------------------------------------------------------------------------- */   \n"
"    class Blob {   \n"
"        constructor(blobParts = [], options = {}) {   \n"
"            this._type = options.type ? String(options.type).toLowerCase() : '';   \n"
"            let parts = [];   \n"
"            if (blobParts && typeof blobParts[Symbol.iterator] === 'function') {   \n"
"                for (let part of blobParts) {   \n"
"                    if (part && part._buffer) {   \n"
"                        parts.push(part._buffer);   \n"
"                    } else if (part instanceof ArrayBuffer) {   \n"
"                        parts.push(new Uint8Array(part));   \n"
"                    } else if (ArrayBuffer.isView(part)) {   \n"
"                        parts.push(new Uint8Array(part.buffer, part.byteOffset, part.byteLength));   \n"
"                    } else {   \n"
"                        let str = String(part);   \n"
"                        let enc = new TextEncoder();   \n"
"                        parts.push(enc.encode(str));   \n"
"                    }   \n"
"                }   \n"
"            }   \n"
"            let totalLen = parts.reduce((acc, p) => acc + p.byteLength, 0);   \n"
"            let merged = new Uint8Array(totalLen);   \n"
"            let offset = 0;   \n"
"            for (let p of parts) {   \n"
"                merged.set(p, offset);   \n"
"                offset += p.byteLength;   \n"
"            }   \n"
"            this._buffer = merged;   \n"
"        }   \n"
"   \n"
"        get size() {   \n"
"            return this._buffer ? this._buffer.byteLength : 0;   \n"
"        }   \n"
"   \n"
"        get type() {   \n"
"            return this._type || '';   \n"
"        }   \n"
"   \n"
"        slice(start = 0, end = this.size, contentType = '') {   \n"
"            let len = this.size;   \n"
"            let relativeStart = start < 0 ? Math.max(len + start, 0) : Math.min(start, len);   \n"
"            let relativeEnd = end < 0 ? Math.max(len + end, 0) : Math.min(end, len);   \n"
"            let span = Math.max(relativeEnd - relativeStart, 0);   \n"
"            let slicedBuffer = this._buffer.subarray(relativeStart, relativeStart + span);   \n"
"            let b = new Blob([], { type: contentType });   \n"
"            b._buffer = new Uint8Array(slicedBuffer);   \n"
"            return b;   \n"
"        }   \n"
"   \n"
"        text() {   \n"
"            let dec = new TextDecoder();   \n"
"            return Promise.resolve(dec.decode(this._buffer));   \n"
"        }   \n"
"   \n"
"        arrayBuffer() {   \n"
"            return Promise.resolve(this._buffer.buffer.slice(   \n"
"                this._buffer.byteOffset,   \n"
"                this._buffer.byteOffset + this._buffer.byteLength   \n"
"            ));   \n"
"        }   \n"
"   \n"
"        stream() {   \n"
"            if (global.ReadableStream) {   \n"
"                let buf = this._buffer;   \n"
"                return new global.ReadableStream({   \n"
"                    start(controller) {   \n"
"                        controller.enqueue(buf);   \n"
"                        controller.close();   \n"
"                    }   \n"
"                });   \n"
"            }   \n"
"            return null;   \n"
"        }   \n"
"   \n"
"        get [Symbol.toStringTag]() {   \n"
"            return 'Blob';   \n"
"        }   \n"
"    }   \n"
"    global.Blob = Blob;   \n"
"   \n"
"    class File extends Blob {   \n"
"        constructor(fileBits, fileName, options = {}) {   \n"
"            super(fileBits, options);   \n"
"            this._name = String(fileName);   \n"
"            this._lastModified = options.lastModified !== undefined ? Number(options.lastModified) : Date.now();   \n"
"        }   \n"
"   \n"
"        get name() {   \n"
"            return this._name;   \n"
"        }   \n"
"   \n"
"        get lastModified() {   \n"
"            return this._lastModified;   \n"
"        }   \n"
"   \n"
"        get lastModifiedDate() {   \n"
"            return new Date(this._lastModified);   \n"
"        }   \n"
"   \n"
"        get [Symbol.toStringTag]() {   \n"
"            return 'File';   \n"
"        }   \n"
"    }   \n"
"    global.File = File;   \n"
"   \n"
"    /* --------------------------------------------------------------------------   \n"
"     * FileReader   \n"
"     * -------------------------------------------------------------------------- */   \n"
"    const BaseClass = global.EventTarget || class {};   \n"
"   \n"
"    class FileReader extends BaseClass {   \n"
"        constructor() {   \n"
"            super();   \n"
"            this.readyState = 0;   \n"
"            this.result = null;   \n"
"            this.error = null;   \n"
"            this.onloadstart = null;   \n"
"            this.onprogress = null;   \n"
"            this.onload = null;   \n"
"            this.onabort = null;   \n"
"            this.onerror = null;   \n"
"            this.onloadend = null;   \n"
"        }   \n"
"   \n"
"        _dispatch(type, eventProps = {}) {   \n"
"            let evt = global.Event ? new global.Event(type, { bubbles: false, cancelable: false }) : { type };   \n"
"            Object.assign(evt, eventProps);   \n"
"            if (typeof this['on' + type] === 'function') {   \n"
"                try { this['on' + type].call(this, evt); } catch(e) {}   \n"
"            }   \n"
"            if (typeof this.dispatchEvent === 'function') {   \n"
"                try { this.dispatchEvent(evt); } catch(e) {}   \n"
"            }   \n"
"        }   \n"
"   \n"
"        _read(blob, format) {   \n"
"            if (!(blob instanceof global.Blob)) {   \n"
"                throw new TypeError('Failed to execute readAs on FileReader: parameter 1 is not of type Blob.');   \n"
"            }   \n"
"            this.readyState = 1;   \n"
"            this.result = null;   \n"
"            this.error = null;   \n"
"   \n"
"            queueMicrotask(() => {   \n"
"                this._dispatch('loadstart');   \n"
"                blob.arrayBuffer().then(ab => {   \n"
"                    if (this.readyState !== 1) return;   \n"
"                    if (format === 'dataURL') {   \n"
"                        let bytes = new Uint8Array(ab);   \n"
"                        let binary = '';   \n"
"                        for (let i = 0; i < bytes.byteLength; i++) {   \n"
"                            binary += String.fromCharCode(bytes[i]);   \n"
"                        }   \n"
"                        let b64 = global.btoa ? global.btoa(binary) : '';   \n"
"                        let mime = blob.type || 'application/octet-stream';   \n"
"                        this.result = 'data:' + mime + ';base64,' + b64;   \n"
"                    } else if (format === 'arrayBuffer') {   \n"
"                        this.result = ab;   \n"
"                    } else if (format === 'text') {   \n"
"                        let dec = new TextDecoder();   \n"
"                        this.result = dec.decode(ab);   \n"
"                    } else if (format === 'binaryString') {   \n"
"                        let bytes = new Uint8Array(ab);   \n"
"                        let binary = '';   \n"
"                        for (let i = 0; i < bytes.byteLength; i++) {   \n"
"                            binary += String.fromCharCode(bytes[i]);   \n"
"                        }   \n"
"                        this.result = binary;   \n"
"                    }   \n"
"                    this.readyState = 2;   \n"
"                    this._dispatch('progress', { loaded: blob.size, total: blob.size, lengthComputable: true });   \n"
"                    this._dispatch('load');   \n"
"                    this._dispatch('loadend');   \n"
"                }).catch(err => {   \n"
"                    if (this.readyState !== 1) return;   \n"
"                    this.readyState = 2;   \n"
"                    this.error = err;   \n"
"                    this._dispatch('error');   \n"
"                    this._dispatch('loadend');   \n"
"                });   \n"
"            });   \n"
"        }   \n"
"   \n"
"        readAsDataURL(blob) { this._read(blob, 'dataURL'); }   \n"
"        readAsArrayBuffer(blob) { this._read(blob, 'arrayBuffer'); }   \n"
"        readAsText(blob, encoding) { this._read(blob, 'text'); }   \n"
"        readAsBinaryString(blob) { this._read(blob, 'binaryString'); }   \n"
"   \n"
"        abort() {   \n"
"            if (this.readyState === 1) {   \n"
"                this.readyState = 2;   \n"
"                this.result = null;   \n"
"                this.error = global.DOMException ? new global.DOMException('The operation was aborted', 'AbortError') : new Error('AbortError');   \n"
"                this._dispatch('abort');   \n"
"                this._dispatch('loadend');   \n"
"            }   \n"
"        }   \n"
"   \n"
"        get [Symbol.toStringTag]() {   \n"
"            return 'FileReader';   \n"
"        }   \n"
"    }   \n"
"    FileReader.EMPTY = 0;   \n"
"    FileReader.LOADING = 1;   \n"
"    FileReader.DONE = 2;   \n"
"    FileReader.prototype.EMPTY = 0;   \n"
"    FileReader.prototype.LOADING = 1;   \n"
"    FileReader.prototype.DONE = 2;   \n"
"    global.FileReader = FileReader;   \n"
"   \n"
"    if (global.URL) {   \n"
"        if (!global.URL.createObjectURL) {   \n"
"            global.URL.createObjectURL = function(blob) {   \n"
"                return 'blob:' + (global.location ? global.location.origin : 'http://localhost') + '/' + Math.random().toString(36).substring(2);   \n"
"            };   \n"
"        }   \n"
"        if (!global.URL.revokeObjectURL) {   \n"
"            global.URL.revokeObjectURL = function(url) {};   \n"
"        }   \n"
"    }   \n"
"   \n"
"    /* --------------------------------------------------------------------------   \n"
"     * IndexedDB Subsystem   \n"
"     * -------------------------------------------------------------------------- */   \n"
"    class IDBRequest extends BaseClass {   \n"
"        constructor() {   \n"
"            super();   \n"
"            this.result = null;   \n"
"            this.error = null;   \n"
"            this.source = null;   \n"
"            this.transaction = null;   \n"
"            this.readyState = 'pending';   \n"
"            this.onsuccess = null;   \n"
"            this.onerror = null;   \n"
"        }   \n"
"   \n"
"        _complete(res, err = null) {   \n"
"            this.readyState = 'done';   \n"
"            this.result = res;   \n"
"            this.error = err;   \n"
"            let evtType = err ? 'error' : 'success';   \n"
"            let evt = global.Event ? new global.Event(evtType, { bubbles: false, cancelable: true }) : { type: evtType };   \n"
"            evt.target = this;   \n"
"            if (typeof this['on' + evtType] === 'function') {   \n"
"                try { this['on' + evtType].call(this, evt); } catch(e) {}   \n"
"            }   \n"
"            if (typeof this.dispatchEvent === 'function') {   \n"
"                try { this.dispatchEvent(evt); } catch(e) {}   \n"
"            }   \n"
"        }   \n"
"    }   \n"
"   \n"
"    class IDBOpenDBRequest extends IDBRequest {   \n"
"        constructor() {   \n"
"            super();   \n"
"            this.onblocked = null;   \n"
"            this.onupgradeneeded = null;   \n"
"        }   \n"
"   \n"
"        _upgrade(db, oldVer, newVer) {   \n"
"            this.result = db;   \n"
"            this._hasUpgraded = true;   \n"
"            this._oldVersion = oldVer;   \n"
"            this._newVersion = newVer;   \n"
"            let evt = global.Event ? new global.Event('upgradeneeded', { bubbles: false, cancelable: false }) : { type: 'upgradeneeded' };   \n"
"            evt.target = this;   \n"
"            evt.oldVersion = oldVer;   \n"
"            evt.newVersion = newVer;   \n"
"            if (typeof this.onupgradeneeded === 'function') {   \n"
"                try { this.onupgradeneeded.call(this, evt); } catch(e) {}   \n"
"            }   \n"
"            if (typeof this.dispatchEvent === 'function') {   \n"
"                try { this.dispatchEvent(evt); } catch(e) {}   \n"
"            }   \n"
"        }   \n"
"    }   \n"
"   \n"
"    class IDBObjectStore {   \n"
"        constructor(db, name, options = {}) {   \n"
"            this._db = db;   \n"
"            this._name = name;   \n"
"            this._data = new Map();   \n"
"            this._keyPath = options.keyPath || null;   \n"
"            this._autoIncrement = !!options.autoIncrement;   \n"
"        }   \n"
"   \n"
"        get name() { return this._name; }   \n"
"        get keyPath() { return this._keyPath; }   \n"
"        get autoIncrement() { return this._autoIncrement; }   \n"
"        get indexNames() { return []; }   \n"
"        get transaction() { return null; }   \n"
"   \n"
"        put(value, key) {   \n"
"            let req = new IDBRequest();   \n"
"            if (key === undefined) key = 'auto_' + Math.random();   \n"
"            this._data.set(key, value);   \n"
"            req._complete(key);   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        add(value, key) { return this.put(value, key); }   \n"
"   \n"
"        get(key) {   \n"
"            let req = new IDBRequest();   \n"
"            let val = this._data.get(key);   \n"
"            req._complete(val !== undefined ? val : undefined);   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        getAll() {   \n"
"            let req = new IDBRequest();   \n"
"            let vals = Array.from(this._data.values());   \n"
"            req._complete(vals);   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        delete(key) {   \n"
"            let req = new IDBRequest();   \n"
"            this._data.delete(key);   \n"
"            req._complete(undefined);   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        clear() {   \n"
"            let req = new IDBRequest();   \n"
"            this._data.clear();   \n"
"            req._complete(undefined);   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        count() {   \n"
"            let req = new IDBRequest();   \n"
"            req._complete(this._data.size);   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        openCursor() {   \n"
"            let req = new IDBRequest();   \n"
"            req._complete(null);   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        createIndex() { return {}; }   \n"
"        index() { return {}; }   \n"
"        deleteIndex() {}   \n"
"    }   \n"
"   \n"
"    class IDBTransaction extends BaseClass {   \n"
"        constructor(db, storeNames, mode = 'readonly') {   \n"
"            super();   \n"
"            this._db = db;   \n"
"            this._mode = mode;   \n"
"            this._objectStoreNames = Array.isArray(storeNames) ? storeNames : [storeNames];   \n"
"            this.onabort = null;   \n"
"            this.oncomplete = null;   \n"
"            this.onerror = null;   \n"
"        }   \n"
"   \n"
"        get db() { return this._db; }   \n"
"        get mode() { return this._mode; }   \n"
"        get objectStoreNames() { return this._objectStoreNames; }   \n"
"        get error() { return null; }   \n"
"   \n"
"        objectStore(name) { return this._db._getStore(name); }   \n"
"        abort() {}   \n"
"    }   \n"
"   \n"
"    class IDBDatabase extends BaseClass {   \n"
"        constructor(name, version = 1) {   \n"
"            super();   \n"
"            this._name = name;   \n"
"            this._version = version;   \n"
"            this._stores = new Map();   \n"
"            this.onabort = null;   \n"
"            this.onerror = null;   \n"
"            this.onversionchange = null;   \n"
"        }   \n"
"   \n"
"        get name() { return this._name; }   \n"
"        get version() { return this._version; }   \n"
"        get objectStoreNames() {   \n"
"            let names = Array.from(this._stores.keys());   \n"
"            names.contains = (s) => this._stores.has(s);   \n"
"            names.item = (i) => names[i];   \n"
"            return names;   \n"
"        }   \n"
"   \n"
"        createObjectStore(name, options = {}) {   \n"
"            let store = new IDBObjectStore(this, name, options);   \n"
"            this._stores.set(name, store);   \n"
"            return store;   \n"
"        }   \n"
"   \n"
"        deleteObjectStore(name) { this._stores.delete(name); }   \n"
"   \n"
"        transaction(storeNames, mode = 'readonly') {   \n"
"            return new IDBTransaction(this, storeNames, mode);   \n"
"        }   \n"
"   \n"
"        _getStore(name) {   \n"
"            return this._stores.get(name) || new IDBObjectStore(this, name);   \n"
"        }   \n"
"   \n"
"        close() {}   \n"
"    }   \n"
"   \n"
"    const dbs = new Map();   \n"
"   \n"
"    class IDBFactory {   \n"
"        open(name, version = 1) {   \n"
"            let req = new IDBOpenDBRequest();   \n"
"            queueMicrotask(() => {   \n"
"                let db = dbs.get(name);   \n"
"                if (!db) {   \n"
"                    db = new IDBDatabase(name, version);   \n"
"                    dbs.set(name, db);   \n"
"                }   \n"
"                req._upgrade(db, 0, version);   \n"
"                req._complete(db);   \n"
"            });   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        deleteDatabase(name) {   \n"
"            let req = new IDBOpenDBRequest();   \n"
"            dbs.delete(name);   \n"
"            queueMicrotask(() => {   \n"
"                req._complete(undefined);   \n"
"            });   \n"
"            return req;   \n"
"        }   \n"
"   \n"
"        cmp(a, b) {   \n"
"            if (a === b) return 0;   \n"
"            return a < b ? -1 : 1;   \n"
"        }   \n"
"    }   \n"
"   \n"
"    global.IDBRequest = IDBRequest;   \n"
"    global.IDBOpenDBRequest = IDBOpenDBRequest;   \n"
"    global.IDBDatabase = IDBDatabase;   \n"
"    global.IDBTransaction = IDBTransaction;   \n"
"    global.IDBObjectStore = IDBObjectStore;   \n"
"    global.IDBFactory = IDBFactory;   \n"
"   \n"
"    const idb = new IDBFactory();   \n"
"    global.indexedDB = idb;   \n"
"    global.webkitIndexedDB = idb;   \n"
"    global.mozIndexedDB = idb;   \n"
"    global.moz_indexedDB = idb;   \n"
"    global.oIndexedDB = idb;   \n"
"    global.msIndexedDB = idb;   \n"
"   \n"
"    /* Ensure readAsDataURL and readAsArrayBuffer are on FileReader prototype */   \n"
"    if (global.FileReader && global.FileReader.prototype) {   \n"
"        if (!global.FileReader.prototype.readAsDataURL) {   \n"
"            global.FileReader.prototype.readAsDataURL = function(blob) { this._read(blob, 'dataURL'); };   \n"
"        }   \n"
"        if (!global.FileReader.prototype.readAsArrayBuffer) {   \n"
"            global.FileReader.prototype.readAsArrayBuffer = function(blob) { this._read(blob, 'arrayBuffer'); };   \n"
"        }   \n"
"        if (!global.FileReader.prototype.readAsText) {   \n"
"            global.FileReader.prototype.readAsText = function(blob, encoding) { this._read(blob, 'text'); };   \n"
"        }   \n"
"        if (!global.FileReader.prototype.readAsBinaryString) {   \n"
"            global.FileReader.prototype.readAsBinaryString = function(blob) { this._read(blob, 'binaryString'); };   \n"
"        }   \n"
"    }   \n"
"})();  \n"
;

#endif /* WISP_NEW_POLYFILLS_H */
