static const char wisp_core_polyfills_js[] =
"\n"
"(function() { \n"
"    'use strict'; \n"
" \n"
"    const global = globalThis; \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 1. CSSOM View: matchMedia & MediaQueryList \n"
"     * -------------------------------------------------------------------------- */ \n"
"    class MediaQueryList extends EventTarget { \n"
"        constructor(query) { \n"
"            super(); \n"
"            this._query = String(query || '').trim(); \n"
"            this._onchange = null; \n"
"        } \n"
" \n"
"        get media() { \n"
"            return this._query; \n"
"        } \n"
" \n"
"        get matches() { \n"
"            return this._evaluate(this._query); \n"
"        } \n"
" \n"
"        get onchange() { \n"
"            return this._onchange; \n"
"        } \n"
" \n"
"        set onchange(handler) { \n"
"            if (this._onchange) { \n"
"                this.removeEventListener('change', this._onchange); \n"
"            } \n"
"            this._onchange = typeof handler === 'function' ? handler : null; \n"
"            if (this._onchange) { \n"
"                this.addEventListener('change', this._onchange); \n"
"            } \n"
"        } \n"
" \n"
"        addListener(listener) { \n"
"            this.addEventListener('change', listener); \n"
"        } \n"
" \n"
"        removeListener(listener) { \n"
"            this.removeEventListener('change', listener); \n"
"        } \n"
" \n"
"        _parsePx(val) { \n"
"            val = String(val).trim().toLowerCase(); \n"
"            if (val.endsWith('px')) return parseFloat(val); \n"
"            if (val.endsWith('em') || val.endsWith('rem')) return parseFloat(val) * 16; \n"
"            return parseFloat(val) || 0; \n"
"        } \n"
" \n"
"        _evaluate(query) { \n"
"            if (!query || query === 'all') return true; \n"
"            if (query === 'not all' || query === 'print') return false; \n"
" \n"
"            const w = global.innerWidth || (global.document && global.document.documentElement ? global.document.documentElement.clientWidth : 1024); \n"
"            const h = global.innerHeight || (global.document && global.document.documentElement ? global.document.documentElement.clientHeight : 768); \n"
" \n"
"            const expressions = query.split(/\\s+and\\s+/i); \n"
"            for (let expr of expressions) { \n"
"                expr = expr.trim(); \n"
"                if (expr.startsWith('(') && expr.endsWith(')')) { \n"
"                    expr = expr.slice(1, -1).trim(); \n"
"                } \n"
"                const colon = expr.indexOf(':'); \n"
"                if (colon === -1) { \n"
"                    if (expr.toLowerCase() === 'screen' || expr.toLowerCase() === 'all') continue; \n"
"                    return false; \n"
"                } \n"
"                const feature = expr.slice(0, colon).trim().toLowerCase(); \n"
"                const value = expr.slice(colon + 1).trim().toLowerCase(); \n"
" \n"
"                if (feature === 'min-width' && !(w >= this._parsePx(value))) return false; \n"
"                if (feature === 'max-width' && !(w <= this._parsePx(value))) return false; \n"
"                if (feature === 'width' && !(w === this._parsePx(value))) return false; \n"
"                if (feature === 'min-height' && !(h >= this._parsePx(value))) return false; \n"
"                if (feature === 'max-height' && !(h <= this._parsePx(value))) return false; \n"
"                if (feature === 'height' && !(h === this._parsePx(value))) return false; \n"
"                if (feature === 'orientation') { \n"
"                    const isPortrait = h >= w; \n"
"                    if (value === 'portrait' && !isPortrait) return false; \n"
"                    if (value === 'landscape' && isPortrait) return false; \n"
"                } \n"
"                if (feature === 'prefers-color-scheme') { \n"
"                    if (value === 'dark' || value === 'light') return true; \n"
"                } \n"
"            } \n"
"            return true; \n"
"        } \n"
"    } \n"
" \n"
"    global.matchMedia = function(query) { \n"
"        return new MediaQueryList(query); \n"
"    }; \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 2. ResizeObserver & ResizeObserverEntry \n"
"     * -------------------------------------------------------------------------- */ \n"
"    class ResizeObserverEntry { \n"
"        constructor(target) { \n"
"            this.target = target; \n"
"            const rect = target.getBoundingClientRect ? target.getBoundingClientRect() : { width: 0, height: 0, top: 0, left: 0, right: 0, bottom: 0, x: 0, y: 0 }; \n"
"            const inlineSize = target.clientWidth || rect.width || 0; \n"
"            const blockSize = target.clientHeight || rect.height || 0; \n"
" \n"
"            this.contentRect = (global.DOMRectReadOnly && global.DOMRectReadOnly.fromRect)  \n"
"                ? DOMRectReadOnly.fromRect({ x: 0, y: 0, width: inlineSize, height: blockSize }) \n"
"                : { x: 0, y: 0, width: inlineSize, height: blockSize, top: 0, left: 0, right: inlineSize, bottom: blockSize }; \n"
" \n"
"            this.borderBoxSize = Object.freeze([{ inlineSize: rect.width, blockSize: rect.height }]); \n"
"            this.contentBoxSize = Object.freeze([{ inlineSize, blockSize }]); \n"
"            this.devicePixelContentBoxSize = Object.freeze([{ inlineSize: inlineSize * (global.devicePixelRatio || 1), blockSize: blockSize * (global.devicePixelRatio || 1) }]); \n"
"        } \n"
"    } \n"
" \n"
"    class ResizeObserver { \n"
"        constructor(callback) { \n"
"            if (typeof callback !== 'function') { \n"
"                throw new TypeError(\"Failed to construct 'ResizeObserver': The callback provided as parameter 1 is not a function.\"); \n"
"            } \n"
"            this._callback = callback; \n"
"            this._targets = new Set(); \n"
"            this._lastSizes = new WeakMap(); \n"
"            this._timer = null; \n"
"        } \n"
" \n"
"        observe(target) { \n"
"            if (!target || target.nodeType !== 1) { \n"
"                throw new TypeError(\"Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.\"); \n"
"            } \n"
"            this._targets.add(target); \n"
"            const w = target.clientWidth || 0; \n"
"            const h = target.clientHeight || 0; \n"
"            this._lastSizes.set(target, { w, h }); \n"
"            this._start(); \n"
"        } \n"
" \n"
"        unobserve(target) { \n"
"            this._targets.delete(target); \n"
"            this._lastSizes.delete(target); \n"
"            if (this._targets.size === 0) { \n"
"                this._stop(); \n"
"            } \n"
"        } \n"
" \n"
"        disconnect() { \n"
"            this._targets.clear(); \n"
"            this._stop(); \n"
"        } \n"
" \n"
"        _start() { \n"
"            if (this._timer) return; \n"
"            this._timer = setInterval(() => { \n"
"                const entries = []; \n"
"                for (const target of this._targets) { \n"
"                    const last = this._lastSizes.get(target); \n"
"                    const cw = target.clientWidth || 0; \n"
"                    const ch = target.clientHeight || 0; \n"
"                    if (!last || last.w !== cw || last.h !== ch) { \n"
"                        this._lastSizes.set(target, { w: cw, h: ch }); \n"
"                        entries.push(new ResizeObserverEntry(target)); \n"
"                    } \n"
"                } \n"
"                if (entries.length > 0) { \n"
"                    try { \n"
"                        this._callback(entries, this); \n"
"                    } catch (e) { \n"
"                        console.error('ResizeObserver callback exception:', e); \n"
"                    } \n"
"                } \n"
"            }, 50); \n"
"        } \n"
" \n"
"        _stop() { \n"
"            if (this._timer) { \n"
"                clearInterval(this._timer); \n"
"                this._timer = null; \n"
"            } \n"
"        } \n"
"    } \n"
" \n"
"    global.ResizeObserver = ResizeObserver; \n"
"    global.ResizeObserverEntry = ResizeObserverEntry; \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 3. Full DOMTokenList Specification \n"
"     * -------------------------------------------------------------------------- */ \n"
"    class DOMTokenList { \n"
"        constructor(element, attrName) { \n"
"            this._element = element; \n"
"            this._attrName = attrName; \n"
"        } \n"
" \n"
"        _getTokens() { \n"
"            const val = this._element.getAttribute(this._attrName) || ''; \n"
"            return val.trim() === '' ? [] : val.trim().split(/\\s+/); \n"
"        } \n"
" \n"
"        _setTokens(tokens) { \n"
"            this._element.setAttribute(this._attrName, tokens.join(' ')); \n"
"        } \n"
" \n"
"        _validate(token) { \n"
"            token = String(token); \n"
"            if (token === '') { \n"
"                throw new DOMException(\"The token provided must not be empty.\", \"SyntaxError\"); \n"
"            } \n"
"            if (/[\\t\\n\\f\\r ]/.test(token)) { \n"
"                throw new DOMException(\"The token provided contains HTML space characters, which are not permitted.\", \"InvalidCharacterError\"); \n"
"            } \n"
"            return token; \n"
"        } \n"
" \n"
"        get length() { \n"
"            return this._getTokens().length; \n"
"        } \n"
" \n"
"        get value() { \n"
"            return this._element.getAttribute(this._attrName) || ''; \n"
"        } \n"
" \n"
"        set value(val) { \n"
"            this._element.setAttribute(this._attrName, String(val)); \n"
"        } \n"
" \n"
"        item(index) { \n"
"            const tokens = this._getTokens(); \n"
"            index = Number(index); \n"
"            return (index >= 0 && index < tokens.length) ? tokens[index] : null; \n"
"        } \n"
" \n"
"        contains(token) { \n"
"            token = this._validate(token); \n"
"            return this._getTokens().includes(token); \n"
"        } \n"
" \n"
"        add(...tokens) { \n"
"            const curr = this._getTokens(); \n"
"            let changed = false; \n"
"            for (let token of tokens) { \n"
"                token = this._validate(token); \n"
"                if (!curr.includes(token)) { \n"
"                    curr.push(token); \n"
"                    changed = true; \n"
"                } \n"
"            } \n"
"            if (changed) this._setTokens(curr); \n"
"        } \n"
" \n"
"        remove(...tokens) { \n"
"            let curr = this._getTokens(); \n"
"            for (let token of tokens) { \n"
"                token = this._validate(token); \n"
"                curr = curr.filter(t => t !== token); \n"
"            } \n"
"            this._setTokens(curr); \n"
"        } \n"
" \n"
"        toggle(token, force) { \n"
"            token = this._validate(token); \n"
"            const exists = this.contains(token); \n"
"            if (force === undefined) { \n"
"                if (exists) { \n"
"                    this.remove(token); \n"
"                    return false; \n"
"                } else { \n"
"                    this.add(token); \n"
"                    return true; \n"
"                } \n"
"            } \n"
"            if (force) { \n"
"                this.add(token); \n"
"                return true; \n"
"            } else { \n"
"                this.remove(token); \n"
"                return false; \n"
"            } \n"
"        } \n"
" \n"
"        replace(oldToken, newToken) { \n"
"            oldToken = this._validate(oldToken); \n"
"            newToken = this._validate(newToken); \n"
"            const curr = this._getTokens(); \n"
"            const idx = curr.indexOf(oldToken); \n"
"            if (idx === -1) return false; \n"
"            curr[idx] = newToken; \n"
"            this._setTokens(curr); \n"
"            return true; \n"
"        } \n"
" \n"
"        supports(token) { \n"
"            return true; \n"
"        } \n"
" \n"
"        toString() { \n"
"            return this.value; \n"
"        } \n"
" \n"
"        *[Symbol.iterator]() { \n"
"            for (const t of this._getTokens()) yield t; \n"
"        } \n"
"    } \n"
" \n"
"    if (global.Element && Element.prototype) { \n"
"        Object.defineProperty(Element.prototype, 'classList', { \n"
"            get() { \n"
"                if (!this.__wisp_classList) { \n"
"                    this.__wisp_classList = new DOMTokenList(this, 'class'); \n"
"                } \n"
"                return this.__wisp_classList; \n"
"            }, \n"
"            configurable: true, \n"
"            enumerable: true \n"
"        }); \n"
"    } \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 4. Modern ParentNode & ChildNode DOM Mutations \n"
"     * -------------------------------------------------------------------------- */ \n"
"    function convertNodesOrStrings(nodes, doc) { \n"
"        const frag = doc.createDocumentFragment(); \n"
"        for (let item of nodes) { \n"
"            if (typeof item === 'string') { \n"
"                frag.appendChild(doc.createTextNode(item)); \n"
"            } else if (item && item.nodeType) { \n"
"                frag.appendChild(item); \n"
"            } \n"
"        } \n"
"        return frag; \n"
"    } \n"
" \n"
"    function mixinParentNode(proto) { \n"
"        if (!proto) return; \n"
"        proto.prepend = function(...nodes) { \n"
"            const frag = convertNodesOrStrings(nodes, this.ownerDocument || this); \n"
"            this.insertBefore(frag, this.firstChild); \n"
"        }; \n"
"        proto.append = function(...nodes) { \n"
"            const frag = convertNodesOrStrings(nodes, this.ownerDocument || this); \n"
"            this.appendChild(frag); \n"
"        }; \n"
"        proto.replaceChildren = function(...nodes) { \n"
"            while (this.firstChild) { \n"
"                this.removeChild(this.firstChild); \n"
"            } \n"
"            this.append(...nodes); \n"
"        }; \n"
"    } \n"
" \n"
"    function mixinChildNode(proto) { \n"
"        if (!proto) return; \n"
"        proto.before = function(...nodes) { \n"
"            if (!this.parentNode) return; \n"
"            const frag = convertNodesOrStrings(nodes, this.ownerDocument); \n"
"            this.parentNode.insertBefore(frag, this); \n"
"        }; \n"
"        proto.after = function(...nodes) { \n"
"            if (!this.parentNode) return; \n"
"            const frag = convertNodesOrStrings(nodes, this.ownerDocument); \n"
"            this.parentNode.insertBefore(frag, this.nextSibling); \n"
"        }; \n"
"        proto.replaceWith = function(...nodes) { \n"
"            if (!this.parentNode) return; \n"
"            const parent = this.parentNode; \n"
"            const frag = convertNodesOrStrings(nodes, this.ownerDocument); \n"
"            parent.replaceChild(frag, this); \n"
"        }; \n"
"        proto.remove = function() { \n"
"            if (this.parentNode) { \n"
"                this.parentNode.removeChild(this); \n"
"            } \n"
"        }; \n"
"    } \n"
" \n"
"    if (global.Element && Element.prototype) { \n"
"        mixinParentNode(Element.prototype); \n"
"        mixinChildNode(Element.prototype); \n"
" \n"
"        Element.prototype.closest = function(selectors) { \n"
"            let curr = this; \n"
"            while (curr && curr.nodeType === 1) { \n"
"                if (curr.matches && curr.matches(selectors)) return curr; \n"
"                curr = curr.parentNode || curr.parentElement; \n"
"            } \n"
"            return null; \n"
"        }; \n"
" \n"
"        Element.prototype.scrollIntoView = function(arg) { \n"
"            let alignTop = true; \n"
"            if (typeof arg === 'object' && arg !== null) { \n"
"                if (arg.block === 'end') alignTop = false; \n"
"            } else if (typeof arg === 'boolean') { \n"
"                alignTop = arg; \n"
"            } \n"
"            const rect = this.getBoundingClientRect(); \n"
"            const top = (global.pageYOffset || 0) + rect.top; \n"
"            const targetY = alignTop ? top : (top - (global.innerHeight || 768) + rect.height); \n"
"            global.scrollTo({ top: targetY, left: 0, behavior: (arg && arg.behavior) || 'auto' }); \n"
"        }; \n"
"    } \n"
" \n"
"    if (global.Document && Document.prototype) { \n"
"        mixinParentNode(Document.prototype); \n"
"    } \n"
"    if (global.DocumentFragment && DocumentFragment.prototype) { \n"
"        mixinParentNode(DocumentFragment.prototype); \n"
"    } \n"
"    if (global.CharacterData && CharacterData.prototype) { \n"
"        mixinChildNode(CharacterData.prototype); \n"
"    } \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 5. TreeWalker, NodeIterator, and NodeFilter \n"
"     * -------------------------------------------------------------------------- */ \n"
"    global.NodeFilter = { \n"
"        FILTER_ACCEPT: 1, \n"
"        FILTER_REJECT: 2, \n"
"        FILTER_SKIP: 3, \n"
"        SHOW_ALL: 0xFFFFFFFF, \n"
"        SHOW_ELEMENT: 0x1, \n"
"        SHOW_ATTRIBUTE: 0x2, \n"
"        SHOW_TEXT: 0x4, \n"
"        SHOW_CDATA_SECTION: 0x8, \n"
"        SHOW_ENTITY_REFERENCE: 0x10, \n"
"        SHOW_ENTITY: 0x20, \n"
"        SHOW_PROCESSING_INSTRUCTION: 0x40, \n"
"        SHOW_COMMENT: 0x80, \n"
"        SHOW_DOCUMENT: 0x100, \n"
"        SHOW_DOCUMENT_TYPE: 0x200, \n"
"        SHOW_DOCUMENT_FRAGMENT: 0x400, \n"
"        SHOW_NOTATION: 0x800 \n"
"    }; \n"
" \n"
"    class TreeWalker { \n"
"        constructor(root, whatToShow = 0xFFFFFFFF, filter = null) { \n"
"            if (!root) throw new TypeError(\"Failed to construct 'TreeWalker': root is required\"); \n"
"            this.root = root; \n"
"            this.whatToShow = whatToShow; \n"
"            this.filter = filter; \n"
"            this.currentNode = root; \n"
"        } \n"
" \n"
"        _acceptNode(node) { \n"
"            const flag = 1 << (node.nodeType - 1); \n"
"            if (!(this.whatToShow & flag)) { \n"
"                return global.NodeFilter.FILTER_SKIP; \n"
"            } \n"
"            if (typeof this.filter === 'function') { \n"
"                return this.filter(node); \n"
"            } \n"
"            if (this.filter && typeof this.filter.acceptNode === 'function') { \n"
"                return this.filter.acceptNode(node); \n"
"            } \n"
"            return global.NodeFilter.FILTER_ACCEPT; \n"
"        } \n"
" \n"
"        parentNode() { \n"
"            let node = this.currentNode; \n"
"            while (node && node !== this.root) { \n"
"                node = node.parentNode; \n"
"                if (node) { \n"
"                    const result = this._acceptNode(node); \n"
"                    if (result === global.NodeFilter.FILTER_ACCEPT) { \n"
"                        this.currentNode = node; \n"
"                        return node; \n"
"                    } \n"
"                } \n"
"            } \n"
"            return null; \n"
"        } \n"
" \n"
"        firstChild() { \n"
"            return this._traverseChildren(this.currentNode, 'first'); \n"
"        } \n"
" \n"
"        lastChild() { \n"
"            return this._traverseChildren(this.currentNode, 'last'); \n"
"        } \n"
" \n"
"        previousSibling() { \n"
"            return this._traverseSiblings(this.currentNode, 'prev'); \n"
"        } \n"
" \n"
"        nextSibling() { \n"
"            return this._traverseSiblings(this.currentNode, 'next'); \n"
"        } \n"
" \n"
"        _traverseChildren(node, direction) { \n"
"            let child = direction === 'first' ? node.firstChild : node.lastChild; \n"
"            while (child) { \n"
"                const result = this._acceptNode(child); \n"
"                if (result === global.NodeFilter.FILTER_ACCEPT) { \n"
"                    this.currentNode = child; \n"
"                    return child; \n"
"                } \n"
"                if (result === global.NodeFilter.FILTER_SKIP) { \n"
"                    const grandchild = this._traverseChildren(child, direction); \n"
"                    if (grandchild) return grandchild; \n"
"                } \n"
"                child = direction === 'first' ? child.nextSibling : child.previousSibling; \n"
"            } \n"
"            return null; \n"
"        } \n"
" \n"
"        _traverseSiblings(node, direction) { \n"
"            let sibling = node; \n"
"            while (sibling) { \n"
"                if (sibling === this.root) return null; \n"
"                sibling = direction === 'next' ? sibling.nextSibling : sibling.previousSibling; \n"
"                if (!sibling) return null; \n"
"                const result = this._acceptNode(sibling); \n"
"                if (result === global.NodeFilter.FILTER_ACCEPT) { \n"
"                    this.currentNode = sibling; \n"
"                    return sibling; \n"
"                } \n"
"                if (result === global.NodeFilter.FILTER_SKIP) { \n"
"                    const child = this._traverseChildren(sibling, direction === 'next' ? 'first' : 'last'); \n"
"                    if (child) return child; \n"
"                } \n"
"            } \n"
"            return null; \n"
"        } \n"
" \n"
"        nextNode() { \n"
"            let node = this.currentNode; \n"
"            let result = global.NodeFilter.FILTER_ACCEPT; \n"
" \n"
"            while (true) { \n"
"                while (result !== global.NodeFilter.FILTER_REJECT && node.firstChild) { \n"
"                    node = node.firstChild; \n"
"                    result = this._acceptNode(node); \n"
"                    if (result === global.NodeFilter.FILTER_ACCEPT) { \n"
"                        this.currentNode = node; \n"
"                        return node; \n"
"                    } \n"
"                } \n"
" \n"
"                while (node) { \n"
"                    if (node === this.root) return null; \n"
"                    if (node.nextSibling) { \n"
"                        node = node.nextSibling; \n"
"                        break; \n"
"                    } \n"
"                    node = node.parentNode; \n"
"                } \n"
" \n"
"                if (!node) return null; \n"
"                result = this._acceptNode(node); \n"
"                if (result === global.NodeFilter.FILTER_ACCEPT) { \n"
"                    this.currentNode = node; \n"
"                    return node; \n"
"                } \n"
"            } \n"
"        } \n"
" \n"
"        previousNode() { \n"
"            let node = this.currentNode; \n"
"            while (node !== this.root) { \n"
"                let sibling = node.previousSibling; \n"
"                while (sibling) { \n"
"                    node = sibling; \n"
"                    let result = this._acceptNode(node); \n"
"                    while (result !== global.NodeFilter.FILTER_REJECT && node.lastChild) { \n"
"                        node = node.lastChild; \n"
"                        result = this._acceptNode(node); \n"
"                    } \n"
"                    if (result === global.NodeFilter.FILTER_ACCEPT) { \n"
"                        this.currentNode = node; \n"
"                        return node; \n"
"                    } \n"
"                    sibling = node.previousSibling; \n"
"                } \n"
"                if (node === this.root || !node.parentNode) return null; \n"
"                node = node.parentNode; \n"
"                if (this._acceptNode(node) === global.NodeFilter.FILTER_ACCEPT) { \n"
"                    this.currentNode = node; \n"
"                    return node; \n"
"                } \n"
"            } \n"
"            return null; \n"
"        } \n"
"    } \n"
" \n"
"    if (global.Document && Document.prototype) { \n"
"        Document.prototype.createTreeWalker = function(root, whatToShow, filter) { \n"
"            return new TreeWalker(root, whatToShow, filter); \n"
"        }; \n"
"        Document.prototype.createNodeIterator = function(root, whatToShow, filter) { \n"
"            return new TreeWalker(root, whatToShow, filter); \n"
"        }; \n"
"    } \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 6. Contextual Range & DOM Parsing \n"
"     * -------------------------------------------------------------------------- */ \n"
"    if (global.Range && Range.prototype) { \n"
"        Range.prototype.createContextualFragment = function(fragment) { \n"
"            const doc = this.startContainer ? (this.startContainer.ownerDocument || this.startContainer) : document; \n"
"            const container = doc.createElement('template'); \n"
"            container.innerHTML = fragment; \n"
"            return container.content || (function() { \n"
"                const frag = doc.createDocumentFragment(); \n"
"                while (container.firstChild) { \n"
"                    frag.appendChild(container.firstChild); \n"
"                } \n"
"                return frag; \n"
"            })(); \n"
"        }; \n"
"    } \n"
" \n"
"    class XMLSerializer { \n"
"        serializeToString(root) { \n"
"            if (!root) return ''; \n"
"            if (root.nodeType === 3) { \n"
"                return root.nodeValue.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); \n"
"            } \n"
"            if (root.nodeType === 8) { \n"
"                return `<!--${root.nodeValue}-->`; \n"
"            } \n"
"            if (root.nodeType === 1) { \n"
"                const tagName = root.tagName.toLowerCase(); \n"
"                let attrs = ''; \n"
"                if (root.attributes) { \n"
"                    for (let i = 0; i < root.attributes.length; i++) { \n"
"                        const attr = root.attributes[i]; \n"
"                        attrs += ` ${attr.name}=\"${attr.value.replace(/\"/g, '&quot;')}\"`; \n"
"                    } \n"
"                } \n"
"                const voidTags = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr']); \n"
"                if (voidTags.has(tagName) && (!root.childNodes || root.childNodes.length === 0)) { \n"
"                    return `<${tagName}${attrs}/>`; \n"
"                } \n"
"                let inner = ''; \n"
"                for (const child of (root.childNodes || [])) { \n"
"                    inner += this.serializeToString(child); \n"
"                } \n"
"                return `<${tagName}${attrs}>${inner}</${tagName}>`; \n"
"            } \n"
"            if (root.nodeType === 9 || root.nodeType === 11) { \n"
"                let inner = ''; \n"
"                for (const child of (root.childNodes || [])) { \n"
"                    inner += this.serializeToString(child); \n"
"                } \n"
"                return inner; \n"
"            } \n"
"            return ''; \n"
"        } \n"
"    } \n"
" \n"
"    global.XMLSerializer = XMLSerializer; \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 7. Window Scrolling Architecture \n"
"     * -------------------------------------------------------------------------- */ \n"
"    let _scrollX = 0; \n"
"    let _scrollY = 0; \n"
" \n"
"    global.scrollTo = function(xOrOptions, y) { \n"
"        if (typeof xOrOptions === 'object' && xOrOptions !== null) { \n"
"            if (xOrOptions.left !== undefined) _scrollX = Number(xOrOptions.left) || 0; \n"
"            if (xOrOptions.top !== undefined) _scrollY = Number(xOrOptions.top) || 0; \n"
"        } else { \n"
"            _scrollX = Number(xOrOptions) || 0; \n"
"            _scrollY = Number(y) || 0; \n"
"        } \n"
"        if (global.document && global.document.documentElement) { \n"
"            global.document.documentElement.scrollLeft = _scrollX; \n"
"            global.document.documentElement.scrollTop = _scrollY; \n"
"        } \n"
"        global.dispatchEvent(new Event('scroll')); \n"
"    }; \n"
" \n"
"    global.scroll = global.scrollTo; \n"
" \n"
"    global.scrollBy = function(xOrOptions, y) { \n"
"        if (typeof xOrOptions === 'object' && xOrOptions !== null) { \n"
"            global.scrollTo({ \n"
"                left: _scrollX + (Number(xOrOptions.left) || 0), \n"
"                top: _scrollY + (Number(xOrOptions.top) || 0), \n"
"                behavior: xOrOptions.behavior \n"
"            }); \n"
"        } else { \n"
"            global.scrollTo(_scrollX + (Number(xOrOptions) || 0), _scrollY + (Number(y) || 0)); \n"
"        } \n"
"    }; \n"
" \n"
"    Object.defineProperty(global, 'pageXOffset', { get: () => _scrollX, configurable: true, enumerable: true }); \n"
"    Object.defineProperty(global, 'pageYOffset', { get: () => _scrollY, configurable: true, enumerable: true }); \n"
"    Object.defineProperty(global, 'scrollX', { get: () => _scrollX, configurable: true, enumerable: true }); \n"
"    Object.defineProperty(global, 'scrollY', { get: () => _scrollY, configurable: true, enumerable: true }); \n"
" \n"
"    /* -------------------------------------------------------------------------- \n"
"     * 8. Bidirectional URLSearchParams & URL \n"
"     * -------------------------------------------------------------------------- */ \n"
"    class URLSearchParams { \n"
"        constructor(init = '') { \n"
"            this._entries = []; \n"
"            this._urlObj = null; \n"
" \n"
"            if (typeof init === 'string') { \n"
"                if (init.startsWith('?')) init = init.slice(1); \n"
"                if (init) { \n"
"                    const pairs = init.split('&'); \n"
"                    for (const pair of pairs) { \n"
"                        const idx = pair.indexOf('='); \n"
"                        if (idx !== -1) { \n"
"                            this.append(decodeURIComponent(pair.slice(0, idx).replace(/\\+/g, ' ')), \n"
"                                        decodeURIComponent(pair.slice(idx + 1).replace(/\\+/g, ' '))); \n"
"                        } else { \n"
"                            this.append(decodeURIComponent(pair.replace(/\\+/g, ' ')), ''); \n"
"                        } \n"
"                    } \n"
"                } \n"
"            } else if (Array.isArray(init)) { \n"
"                for (const [k, v] of init) this.append(k, v); \n"
"            } else if (init && typeof init === 'object') { \n"
"                for (const k of Object.keys(init)) this.append(k, init[k]); \n"
"            } \n"
"        } \n"
" \n"
"        _mutate() { \n"
"            if (this._urlObj) { \n"
"                this._urlObj._search = this.toString() ? ('?' + this.toString()) : ''; \n"
"            } \n"
"        } \n"
" \n"
"        append(name, value) { \n"
"            this._entries.push([String(name), String(value)]); \n"
"            this._mutate(); \n"
"        } \n"
" \n"
"        delete(name) { \n"
"            name = String(name); \n"
"            this._entries = this._entries.filter(([k]) => k !== name); \n"
"            this._mutate(); \n"
"        } \n"
" \n"
"        get(name) { \n"
"            name = String(name); \n"
"            const found = this._entries.find(([k]) => k === name); \n"
"            return found ? found[1] : null; \n"
"        } \n"
" \n"
"        getAll(name) { \n"
"            name = String(name); \n"
"            return this._entries.filter(([k]) => k === name).map(([, v]) => v); \n"
"        } \n"
" \n"
"        has(name) { \n"
"            name = String(name); \n"
"            return this._entries.some(([k]) => k === name); \n"
"        } \n"
" \n"
"        set(name, value) { \n"
"            name = String(name); \n"
"            value = String(value); \n"
"            let replaced = false; \n"
"            this._entries = this._entries.filter(([k]) => { \n"
"                if (k === name) { \n"
"                    if (!replaced) { \n"
"                        replaced = true; \n"
"                        return true; \n"
"                    } \n"
"                    return false; \n"
"                } \n"
"                return true; \n"
"            }); \n"
"            if (replaced) { \n"
"                const idx = this._entries.findIndex(([k]) => k === name); \n"
"                this._entries[idx] = [name, value]; \n"
"            } else { \n"
"                this._entries.push([name, value]); \n"
"            } \n"
"            this._mutate(); \n"
"        } \n"
" \n"
"        sort() { \n"
"            this._entries.sort(([a], [b]) => (a > b ? 1 : a < b ? -1 : 0)); \n"
"            this._mutate(); \n"
"        } \n"
" \n"
"        toString() { \n"
"            return this._entries \n"
"                .map(([k, v]) => encodeURIComponent(k).replace(/%20/g, '+') + '=' + encodeURIComponent(v).replace(/%20/g, '+')) \n"
"                .join('&'); \n"
"        } \n"
" \n"
"        *[Symbol.iterator]() { \n"
"            for (const item of this._entries) yield item; \n"
"        } \n"
" \n"
"        forEach(callback, thisArg) { \n"
"            for (const [k, v] of this._entries) { \n"
"                callback.call(thisArg, v, k, this); \n"
"            } \n"
"        } \n"
" \n"
"        keys() { return this._entries.map(([k]) => k)[Symbol.iterator](); } \n"
"        values() { return this._entries.map(([, v]) => v)[Symbol.iterator](); } \n"
"        entries() { return this[Symbol.iterator](); } \n"
"    } \n"
" \n"
"    global.URLSearchParams = URLSearchParams; \n"
" \n"
"})();\n"
"\n"
"/* ========================================================================== \n"
"   MODULE 9: DOM PARSING & SERIALIZATION SUBSYSTEM \n"
"   ========================================================================== */ \n"
"(function() { \n"
"    'use strict'; \n"
"    const global = globalThis; \n"
" \n"
"    class DOMParser { \n"
"        parseFromString(string, type) { \n"
"            string = String(string); \n"
"            type = String(type).toLowerCase(); \n"
" \n"
"            if (type === 'text/html') { \n"
"                const doc = document.implementation.createHTMLDocument(''); \n"
"                doc.documentElement.innerHTML = string; \n"
"                return doc; \n"
"            } \n"
" \n"
"            if (type === 'text/xml' || type === 'application/xml' || type === 'application/xhtml+xml' || type === 'image/svg+xml') { \n"
"                const doc = document.implementation.createDocument( \n"
"                    type === 'image/svg+xml' ? 'http://www.w3.org/2000/svg' : (type === 'application/xhtml+xml' ? 'http://www.w3.org/1999/xhtml' : null), \n"
"                    '', \n"
"                    null \n"
"                ); \n"
" \n"
"                // Reconstruct basic tree representation \n"
"                const template = document.createElement('template'); \n"
"                template.innerHTML = string; \n"
"                const children = template.content ? template.content.childNodes : template.childNodes; \n"
"                let rootElement = null; \n"
"                for (let i = 0; i < children.length; i++) { \n"
"                    if (children[i].nodeType === 1) { \n"
"                        rootElement = children[i]; \n"
"                        break; \n"
"                    } \n"
"                } \n"
" \n"
"                if (rootElement) { \n"
"                    const imported = doc.importNode(rootElement, true); \n"
"                    try { doc.replaceChild(imported, doc.documentElement); } catch(e) { try { doc.appendChild(imported); } catch(e) {} } \n"
"                } else { \n"
"                    const parserError = doc.createElementNS('http://www.mozilla.org/newlayout/xml/parsererror.xml', 'parsererror'); \n"
"                    parserError.textContent = 'XML Parsing Error'; \n"
"                    try { doc.replaceChild(parserError, doc.documentElement); } catch(e) { try { doc.appendChild(parserError); } catch(e) {} } \n"
"                } \n"
"                return doc; \n"
"            } \n"
" \n"
"            throw new TypeError(`Failed to execute 'parseFromString' on 'DOMParser': The provided value '${type}' is not a valid enum value of type SupportedType.`); \n"
"        } \n"
"    } \n"
" \n"
"    if (global.Element && Element.prototype) { \n"
"        const proto = Element.prototype; \n"
" \n"
"        proto.insertAdjacentHTML = function(position, text) { \n"
"            position = String(position).toLowerCase().trim(); \n"
"            const doc = this.ownerDocument || document; \n"
"            const container = doc.createElement('template'); \n"
"            container.innerHTML = String(text); \n"
"            const fragment = container.content || (function() { \n"
"                const frag = doc.createDocumentFragment(); \n"
"                while (container.firstChild) frag.appendChild(container.firstChild); \n"
"                return frag; \n"
"            })(); \n"
" \n"
"            switch (position) { \n"
"                case 'beforebegin': \n"
"                    if (!this.parentNode) { \n"
"                        throw new DOMException(\"Cannot insert HTML before an element without a parent.\", \"InvalidStateError\"); \n"
"                    } \n"
"                    this.parentNode.insertBefore(fragment, this); \n"
"                    break; \n"
"                case 'afterbegin': \n"
"                    this.insertBefore(fragment, this.firstChild); \n"
"                    break; \n"
"                case 'beforeend': \n"
"                    this.appendChild(fragment); \n"
"                    break; \n"
"                case 'afterend': \n"
"                    if (!this.parentNode) { \n"
"                        throw new DOMException(\"Cannot insert HTML after an element without a parent.\", \"InvalidStateError\"); \n"
"                    } \n"
"                    this.parentNode.insertBefore(fragment, this.nextSibling); \n"
"                    break; \n"
"                default: \n"
"                    throw new DOMException(`Failed to execute 'insertAdjacentHTML' on 'Element': The position provided ('${position}') is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.`, \"SyntaxError\"); \n"
"            } \n"
"        }; \n"
" \n"
"        Object.defineProperty(proto, 'outerHTML', { \n"
"            get() { \n"
"                const serializer = new global.XMLSerializer(); \n"
"                return serializer.serializeToString(this); \n"
"            }, \n"
"            set(htmlText) { \n"
"                const parent = this.parentNode; \n"
"                if (!parent) { \n"
"                    throw new DOMException(\"Cannot set outerHTML on an element with no parent node.\", \"NoModificationAllowedError\"); \n"
"                } \n"
"                const doc = this.ownerDocument || document; \n"
"                const template = doc.createElement('template'); \n"
"                template.innerHTML = String(htmlText); \n"
"                const fragment = template.content || (function() { \n"
"                    const frag = doc.createDocumentFragment(); \n"
"                    while (template.firstChild) frag.appendChild(template.firstChild); \n"
"                    return frag; \n"
"                })(); \n"
"                parent.replaceChild(fragment, this); \n"
"            }, \n"
"            configurable: true, \n"
"            enumerable: true \n"
"        }); \n"
"    } \n"
" \n"
"    global.DOMParser = DOMParser; \n"
"})();\n"

;
