#ifndef WISP_POLYFILL_CSSOM_H
#define WISP_POLYFILL_CSSOM_H

static const char *cssom_polyfill =
    "(function() {\n"
    "    'use strict';\n"
    "    const global = globalThis;\n"
    "\n"
    "    class CSSRule {\n"
    "        constructor(cssText, parentRule = null, parentStyleSheet = null) {\n"
    "            this.cssText = cssText;\n"
    "            this.parentRule = parentRule;\n"
    "            this.parentStyleSheet = parentStyleSheet;\n"
    "            this.type = 1;\n"
    "        }\n"
    "    }\n"
    "    CSSRule.STYLE_RULE = 1;\n"
    "    CSSRule.CHARSET_RULE = 2;\n"
    "    CSSRule.IMPORT_RULE = 3;\n"
    "    CSSRule.MEDIA_RULE = 4;\n"
    "    CSSRule.FONT_FACE_RULE = 5;\n"
    "    CSSRule.PAGE_RULE = 6;\n"
    "    CSSRule.KEYFRAMES_RULE = 7;\n"
    "    CSSRule.KEYFRAME_RULE = 8;\n"
    "    CSSRule.MARGIN_RULE = 9;\n"
    "    CSSRule.NAMESPACE_RULE = 10;\n"
    "    CSSRule.SUPPORTS_RULE = 12;\n"
    "\n"
    "    class CSSRuleList extends Array {\n"
    "        item(index) {\n"
    "            index = Number(index);\n"
    "            return (index >= 0 && index < this.length) ? this[index] : null;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSStyleRule extends CSSRule {\n"
    "        constructor(selectorText, cssPropertiesText, sheet) {\n"
    "            super('', null, sheet);\n"
    "            this.selectorText = selectorText.trim();\n"
    "            // We need a dummy style declaration if we don't use CSSStyleDeclaration natively here\n"
    "            // Actually, we can use an object with cssText if native CSSStyleDeclaration is not instantiable\n"
    "            // Wait, we can instantiate it, or just use a proxy.\n"
    "            // But the test checks if it is CSSStyleDeclaration?\n"
    "            // Let's create an anonymous class that acts like it, or just a simple JS object, but name it something.\n"
    "            // But wait, the reviewer specifically complained about replacing the native instantiation with `new CSSStyleDeclaration()` for *elements*.\n"
    "            // Does `CSSStyleRule` need to return the native `CSSStyleDeclaration`?\n"
    "            // The test we added checks `sheet.cssRules[0].style.getPropertyValue('background-color')`.\n"
    "            // We can just define `CSSStyleDeclarationImpl` again strictly for `CSSStyleRule`, but don't assign it to `global.CSSStyleDeclaration`.\n"
    "            this.style = new CSSStyleDeclarationImpl(this);\n"
    "            this.style.cssText = cssPropertiesText;\n"
    "            this.type = CSSRule.STYLE_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            return `${this.selectorText} { ${this.style.cssText} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            const braceOpen = val.indexOf('{');\n"
    "            const braceClose = val.lastIndexOf('}');\n"
    "            if (braceOpen !== -1 && braceClose !== -1) {\n"
    "                this.selectorText = val.slice(0, braceOpen).trim();\n"
    "                this.style.cssText = val.slice(braceOpen + 1, braceClose).trim();\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSStyleDeclarationImpl {\n"
    "        constructor(parentRule = null) {\n"
    "            this._properties = new Map();\n"
    "            this._priorities = new Map();\n"
    "            this.parentRule = parentRule;\n"
    "        }\n"
    "        getPropertyValue(name) {\n"
    "            return this._properties.get(String(name).toLowerCase()) || '';\n"
    "        }\n"
    "        getPropertyPriority(name) {\n"
    "            return this._priorities.get(String(name).toLowerCase()) || '';\n"
    "        }\n"
    "        setProperty(name, value, priority = '') {\n"
    "            name = String(name).toLowerCase().trim();\n"
    "            value = String(value).trim();\n"
    "            if (!value) {\n"
    "                this.removeProperty(name);\n"
    "                return;\n"
    "            }\n"
    "            this._properties.set(name, value);\n"
    "            if (String(priority).toLowerCase() === 'important') {\n"
    "                this._priorities.set(name, 'important');\n"
    "            } else {\n"
    "                this._priorities.delete(name);\n"
    "            }\n"
    "        }\n"
    "        removeProperty(name) {\n"
    "            name = String(name).toLowerCase().trim();\n"
    "            const prev = this.getPropertyValue(name);\n"
    "            this._properties.delete(name);\n"
    "            this._priorities.delete(name);\n"
    "            return prev;\n"
    "        }\n"
    "        get length() {\n"
    "            return this._properties.size;\n"
    "        }\n"
    "        item(index) {\n"
    "            const keys = Array.from(this._properties.keys());\n"
    "            return (index >= 0 && index < keys.length) ? keys[index] : '';\n"
    "        }\n"
    "        get cssText() {\n"
    "            const out = [];\n"
    "            this._properties.forEach((val, key) => {\n"
    "                const prio = this._priorities.get(key) ? ' !important' : '';\n"
    "                out.push(`${key}: ${val}${prio};`);\n"
    "            });\n"
    "            return out.join(' ');\n"
    "        }\n"
    "        set cssText(text) {\n"
    "            this._properties.clear();\n"
    "            this._priorities.clear();\n"
    "            if (!text) return;\n"
    "            const parts = text.split(';');\n"
    "            for (let part of parts) {\n"
    "                const colon = part.indexOf(':');\n"
    "                if (colon !== -1) {\n"
    "                    const key = part.slice(0, colon).trim();\n"
    "                    let val = part.slice(colon + 1).trim();\n"
    "                    let prio = '';\n"
    "                    if (val.toLowerCase().endsWith('!important')) {\n"
    "                        prio = 'important';\n"
    "                        val = val.slice(0, -10).trim();\n"
    "                    }\n"
    "                    this.setProperty(key, val, prio);\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSStyleSheet {\n"
    "        constructor(options = {}) {\n"
    "            this.ownerRule = null;\n"
    "            this.disabled = false;\n"
    "            this.href = options.href || null;\n"
    "            this.title = options.title || null;\n"
    "            this.type = 'text/css';\n"
    "            this.cssRules = new CSSRuleList();\n"
    "        }\n"
    "        get rules() {\n"
    "            return this.cssRules;\n"
    "        }\n"
    "        insertRule(ruleText, index = 0) {\n"
    "            ruleText = String(ruleText).trim();\n"
    "            if (index < 0 || index > this.cssRules.length) {\n"
    "                throw new DOMException(\"Failed to execute 'insertRule': The index provided is invalid.\", \"IndexSizeError\");\n"
    "            }\n"
    "            const braceOpen = ruleText.indexOf('{');\n"
    "            const braceClose = ruleText.lastIndexOf('}');\n"
    "            if (braceOpen === -1 || braceClose === -1) {\n"
    "                throw new DOMException(\"Failed to execute 'insertRule': Syntax error in CSS rule.\", \"SyntaxError\");\n"
    "            }\n"
    "            const sel = ruleText.slice(0, braceOpen).trim();\n"
    "            const props = ruleText.slice(braceOpen + 1, braceClose).trim();\n"
    "            const rule = new CSSStyleRule(sel, props, this);\n"
    "            this.cssRules.splice(index, 0, rule);\n"
    "            return index;\n"
    "        }\n"
    "        deleteRule(index) {\n"
    "            index = Number(index);\n"
    "            if (index < 0 || index >= this.cssRules.length) {\n"
    "                throw new DOMException(\"Failed to execute 'deleteRule': The index provided is invalid.\", \"IndexSizeError\");\n"
    "            }\n"
    "            this.cssRules.splice(index, 1);\n"
    "        }\n"
    "        replace(text) {\n"
    "            return Promise.resolve(this.replaceSync(text));\n"
    "        }\n"
    "        replaceSync(text) {\n"
    "            this.cssRules.length = 0;\n"
    "            this.insertRule(text, 0);\n"
    "            return this;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    global.CSSRule = CSSRule;\n"
    "    global.CSSStyleRule = CSSStyleRule;\n"
    "    global.CSSRuleList = CSSRuleList;\n"
    "    global.CSSStyleSheet = CSSStyleSheet;\n"
    "    // global.CSSStyleDeclaration is kept as native C bindings, so we DO NOT overwrite it here.\n"
    "})();\n";

#endif /* WISP_POLYFILL_CSSOM_H */
