const char *intl_polyfill =
    "if (typeof globalThis.Intl === 'undefined') {\n"
    "    globalThis.Intl = {\n"
    "        DateTimeFormat: function() {\n"
    "            return {\n"
    "                format: function(date) { return date ? date.toString() : new Date().toString(); },\n"
    "                resolvedOptions: function() { return { locale: 'en-US' }; }\n"
    "            };\n"
    "        },\n"
    "        NumberFormat: function() {\n"
    "            return {\n"
    "                format: function(num) { return num ? num.toString() : '0'; },\n"
    "                resolvedOptions: function() { return { locale: 'en-US' }; }\n"
    "            };\n"
    "        },\n"
    "        Collator: function() {\n"
    "            return {\n"
    "                compare: function(a, b) {\n"
    "                    if (a === b) return 0;\n"
    "                    return a < b ? -1 : 1;\n"
    "                },\n"
    "                resolvedOptions: function() { return { locale: 'en-US' }; }\n"
    "            };\n"
    "        },\n"
    "        PluralRules: function() {\n"
    "            return {\n"
    "                select: function(n) { return n === 1 ? 'one' : 'other'; },\n"
    "                resolvedOptions: function() { return { locale: 'en-US' }; }\n"
    "            };\n"
    "        },\n"
    "        RelativeTimeFormat: function() {\n"
    "            return {\n"
    "                format: function(value, unit) { return value + ' ' + unit; },\n"
    "                resolvedOptions: function() { return { locale: 'en-US' }; }\n"
    "            };\n"
    "        },\n"
    "        ListFormat: function() {\n"
    "            return {\n"
    "                format: function(list) { return list.join(', '); },\n"
    "                resolvedOptions: function() { return { locale: 'en-US' }; }\n"
    "            };\n"
    "        },\n"
    "        Segmenter: function() {\n"
    "            return {\n"
    "                segment: function(str) { return [{segment: str, index: 0, input: str}]; },\n"
    "                resolvedOptions: function() { return { locale: 'en-US' }; }\n"
    "            };\n"
    "        },\n"
    "        Locale: function(tag) { this.baseName = tag; this.language = tag; },\n"
    "        getCanonicalLocales: function(locales) {\n"
    "            if (!locales) return [];\n"
    "            return Array.isArray(locales) ? locales : [locales];\n"
    "        }\n"
    "    };\n"
    "}\n";
