/* src/content/handlers/javascript/quickjs/polyfill_ui_events_c.h */
#ifndef WISP_POLYFILL_UI_EVENTS_H
#define WISP_POLYFILL_UI_EVENTS_H

static const char *ui_events_polyfill =
    "(function() {\n"
    "    'use strict';\n"
    "    const global = globalThis;\n"
    "\n"
    "    function getModifierState(key) {\n"
    "        key = String(key);\n"
    "        switch (key) {\n"
    "            case 'Alt': return !!this.altKey;\n"
    "            case 'Control': return !!this.ctrlKey;\n"
    "            case 'Shift': return !!this.shiftKey;\n"
    "            case 'Meta': return !!this.metaKey;\n"
    "            case 'AltGraph': return !!(this.altKey && this.ctrlKey);\n"
    "            default: return false;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    if (global.MouseEvent && global.MouseEvent.prototype) {\n"
    "        const proto = global.MouseEvent.prototype;\n"
    "        proto.getModifierState = getModifierState;\n"
    "        Object.defineProperty(proto, 'pageX', {\n"
    "            get() { return (this.clientX || 0) + (global.pageXOffset || 0); },\n"
    "            configurable: true, enumerable: true\n"
    "        });\n"
    "        Object.defineProperty(proto, 'pageY', {\n"
    "            get() { return (this.clientY || 0) + (global.pageYOffset || 0); },\n"
    "            configurable: true, enumerable: true\n"
    "        });\n"
    "        Object.defineProperty(proto, 'which', {\n"
    "            get() { return (this.button !== undefined) ? this.button + 1 : 1; },\n"
    "            configurable: true, enumerable: true\n"
    "        });\n"
    "    }\n"
    "\n"
    "    if (global.KeyboardEvent && global.KeyboardEvent.prototype) {\n"
    "        const proto = global.KeyboardEvent.prototype;\n"
    "        proto.getModifierState = getModifierState;\n"
    "        proto.DOM_KEY_LOCATION_STANDARD = 0x00;\n"
    "        proto.DOM_KEY_LOCATION_LEFT = 0x01;\n"
    "        proto.DOM_KEY_LOCATION_RIGHT = 0x02;\n"
    "        proto.DOM_KEY_LOCATION_NUMPAD = 0x03;\n"
    "        if (global.KeyboardEvent) {\n"
    "            global.KeyboardEvent.DOM_KEY_LOCATION_STANDARD = 0x00;\n"
    "            global.KeyboardEvent.DOM_KEY_LOCATION_LEFT = 0x01;\n"
    "            global.KeyboardEvent.DOM_KEY_LOCATION_RIGHT = 0x02;\n"
    "            global.KeyboardEvent.DOM_KEY_LOCATION_NUMPAD = 0x03;\n"
    "        }\n"
    "        Object.defineProperty(proto, 'which', {\n"
    "            get() { return this.keyCode || 0; },\n"
    "            configurable: true, enumerable: true\n"
    "        });\n"
    "        Object.defineProperty(proto, 'charCode', {\n"
    "            get() { return (this.type === 'keypress') ? (this.keyCode || 0) : 0;\n"
    "            },\n"
    "            configurable: true, enumerable: true\n"
    "        });\n"
    "    }\n"
    "\n"
    "    if (global.WheelEvent && global.WheelEvent.prototype) {\n"
    "        const proto = global.WheelEvent.prototype;\n"
    "        proto.DOM_DELTA_PIXEL = 0x00;\n"
    "        proto.DOM_DELTA_LINE = 0x01;\n"
    "        proto.DOM_DELTA_PAGE = 0x02;\n"
    "        if (global.WheelEvent) {\n"
    "            global.WheelEvent.DOM_DELTA_PIXEL = 0x00;\n"
    "            global.WheelEvent.DOM_DELTA_LINE = 0x01;\n"
    "            global.WheelEvent.DOM_DELTA_PAGE = 0x02;\n"
    "        }\n"
    "    }\n"
    "})();\n";

#endif /* WISP_POLYFILL_UI_EVENTS_H */