#ifndef WISP_POLYFILL_CSSOM_H
#define WISP_POLYFILL_CSSOM_H

static const char *cssom_polyfill =
    "(function() {\n"
    "    'use strict';\n"
    "    const global = globalThis;\n"
    "\n"
    "    class CSSRule {\n"
    "        constructor(cssText = '', parentRule = null, parentStyleSheet = null) {\n"
    "            this._cssText = cssText;\n"
    "            this.parentRule = parentRule;\n"
    "            this.parentStyleSheet = parentStyleSheet;\n"
    "            this.type = 1;\n"
    "        }\n"
    "        get cssText() {\n"
    "            return this._cssText;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "    CSSRule.STYLE_RULE = 1;\n"
    "    CSSRule.CHARSET_RULE = 2;\n"
    "    CSSRule.IMPORT_RULE = 3;\n"
    "    CSSRule.MEDIA_RULE = 4;\n"
    "    CSSRule.FONT_FACE_RULE = 5;\n"
    "    CSSRule.PAGE_RULE = 6;\n"
    "    CSSRule.KEYFRAMES_RULE = 7;\n"
    "    CSSRule.KEYFRAME_RULE = 8;\n"
    "    CSSRule.MARGIN_RULE = 9;\n"
    "    CSSRule.NAMESPACE_RULE = 10;\n"
    "    CSSRule.SUPPORTS_RULE = 12;\n"
    "\n"
    "    class CSSRuleList extends Array {\n"
    "        item(index) {\n"
    "            index = Number(index);\n"
    "            return (index >= 0 && index < this.length) ? this[index] : null;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSStyleDeclarationImpl {\n"
    "        constructor(parentRule = null) {\n"
    "            this._properties = new Map();\n"
    "            this._priorities = new Map();\n"
    "            this.parentRule = parentRule;\n"
    "        }\n"
    "        getPropertyValue(name) {\n"
    "            return this._properties.get(String(name).toLowerCase()) || '';\n"
    "        }\n"
    "        getPropertyPriority(name) {\n"
    "            return this._priorities.get(String(name).toLowerCase()) || '';\n"
    "        }\n"
    "        setProperty(name, value, priority = '') {\n"
    "            name = String(name).toLowerCase().trim();\n"
    "            value = String(value).trim();\n"
    "            if (!value) {\n"
    "                this.removeProperty(name);\n"
    "                return;\n"
    "            }\n"
    "            this._properties.set(name, value);\n"
    "            if (String(priority).toLowerCase() === 'important') {\n"
    "                this._priorities.set(name, 'important');\n"
    "            } else {\n"
    "                this._priorities.delete(name);\n"
    "            }\n"
    "        }\n"
    "        removeProperty(name) {\n"
    "            name = String(name).toLowerCase().trim();\n"
    "            const prev = this.getPropertyValue(name);\n"
    "            this._properties.delete(name);\n"
    "            this._priorities.delete(name);\n"
    "            return prev;\n"
    "        }\n"
    "        get length() {\n"
    "            return this._properties.size;\n"
    "        }\n"
    "        item(index) {\n"
    "            const keys = Array.from(this._properties.keys());\n"
    "            return (index >= 0 && index < keys.length) ? keys[index] : '';\n"
    "        }\n"
    "        get cssText() {\n"
    "            const out = [];\n"
    "            this._properties.forEach((val, key) => {\n"
    "                const prio = this._priorities.get(key) ? ' !important' : '';\n"
    "                out.push(`${key}: ${val}${prio};`);\n"
    "            });\n"
    "            return out.join(' ');\n"
    "        }\n"
    "        set cssText(text) {\n"
    "            this._properties.clear();\n"
    "            this._priorities.clear();\n"
    "            if (!text) return;\n"
    "            const parts = text.split(';');\n"
    "            for (let part of parts) {\n"
    "                const colon = part.indexOf(':');\n"
    "                if (colon !== -1) {\n"
    "                    const key = part.slice(0, colon).trim();\n"
    "                    let val = part.slice(colon + 1).trim();\n"
    "                    let prio = '';\n"
    "                    if (val.toLowerCase().endsWith('!important')) {\n"
    "                        prio = 'important';\n"
    "                        val = val.slice(0, -10).trim();\n"
    "                    }\n"
    "                    this.setProperty(key, val, prio);\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSStyleRule extends CSSRule {\n"
    "        constructor(selectorText, cssPropertiesText, sheet = null) {\n"
    "            super('', null, sheet);\n"
    "            this.selectorText = selectorText ? selectorText.trim() : '';\n"
    "            this.style = new CSSStyleDeclarationImpl(this);\n"
    "            if (cssPropertiesText) {\n"
    "                this.style.cssText = cssPropertiesText;\n"
    "            }\n"
    "            this.type = CSSRule.STYLE_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            return `${this.selectorText} { ${this.style.cssText} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            const braceOpen = val.indexOf('{');\n"
    "            const braceClose = val.lastIndexOf('}');\n"
    "            if (braceOpen !== -1 && braceClose !== -1) {\n"
    "                this.selectorText = val.slice(0, braceOpen).trim();\n"
    "                this.style.cssText = val.slice(braceOpen + 1, braceClose).trim();\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSGroupingRule extends CSSRule {\n"
    "        constructor(cssText = '', sheet = null) {\n"
    "            super(cssText, null, sheet);\n"
    "            this.cssRules = new CSSRuleList();\n"
    "        }\n"
    "        insertRule(ruleText, index = 0) {\n"
    "            if (index < 0 || index > this.cssRules.length) {\n"
    "                throw new DOMException(\"Failed to execute 'insertRule': The index provided is invalid.\", \"IndexSizeError\");\n"
    "            }\n"
    "            const rule = new CSSStyleRule('', ruleText, this.parentStyleSheet);\n"
    "            rule.parentRule = this;\n"
    "            this.cssRules.splice(index, 0, rule);\n"
    "            return index;\n"
    "        }\n"
    "        deleteRule(index) {\n"
    "            index = Number(index);\n"
    "            if (index < 0 || index >= this.cssRules.length) {\n"
    "                throw new DOMException(\"Failed to execute 'deleteRule': The index provided is invalid.\", \"IndexSizeError\");\n"
    "            }\n"
    "            this.cssRules.splice(index, 1);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSMediaRule extends CSSGroupingRule {\n"
    "        constructor(conditionText = 'all', sheet = null) {\n"
    "            super('', sheet);\n"
    "            this.conditionText = conditionText.trim();\n"
    "            this.media = { mediaText: this.conditionText, length: 1, item: () => this.conditionText };\n"
    "            this.type = CSSRule.MEDIA_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            const rulesStr = this.cssRules.map(r => r.cssText).join(' ');\n"
    "            return `@media ${this.conditionText} { ${rulesStr} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSSupportsRule extends CSSGroupingRule {\n"
    "        constructor(conditionText = '', sheet = null) {\n"
    "            super('', sheet);\n"
    "            this.conditionText = conditionText.trim();\n"
    "            this.type = CSSRule.SUPPORTS_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            const rulesStr = this.cssRules.map(r => r.cssText).join(' ');\n"
    "            return `@supports ${this.conditionText} { ${rulesStr} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSKeyframeRule extends CSSRule {\n"
    "        constructor(keyText = '0%', cssPropertiesText = '', sheet = null) {\n"
    "            super('', null, sheet);\n"
    "            this.keyText = keyText.trim();\n"
    "            this.style = new CSSStyleDeclarationImpl(this);\n"
    "            this.style.cssText = cssPropertiesText;\n"
    "            this.type = CSSRule.KEYFRAME_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            return `${this.keyText} { ${this.style.cssText} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSKeyframesRule extends CSSRule {\n"
    "        constructor(name = '', sheet = null) {\n"
    "            super('', null, sheet);\n"
    "            this.name = name.trim();\n"
    "            this.cssRules = new CSSRuleList();\n"
    "            this.type = CSSRule.KEYFRAMES_RULE;\n"
    "        }\n"
    "        appendRule(ruleText) {\n"
    "            const braceOpen = ruleText.indexOf('{');\n"
    "            const braceClose = ruleText.lastIndexOf('}');\n"
    "            if (braceOpen !== -1 && braceClose !== -1) {\n"
    "                const key = ruleText.slice(0, braceOpen).trim();\n"
    "                const props = ruleText.slice(braceOpen + 1, braceClose).trim();\n"
    "                this.cssRules.push(new CSSKeyframeRule(key, props, this.parentStyleSheet));\n"
    "            }\n"
    "        }\n"
    "        deleteRule(select) {\n"
    "            const idx = this.cssRules.findIndex(r => r.keyText === select);\n"
    "            if (idx !== -1) this.cssRules.splice(idx, 1);\n"
    "        }\n"
    "        findRule(select) {\n"
    "            return this.cssRules.find(r => r.keyText === select) || null;\n"
    "        }\n"
    "        get cssText() {\n"
    "            const rulesStr = this.cssRules.map(r => r.cssText).join(' ');\n"
    "            return `@keyframes ${this.name} { ${rulesStr} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSFontFaceRule extends CSSRule {\n"
    "        constructor(cssPropertiesText = '', sheet = null) {\n"
    "            super('', null, sheet);\n"
    "            this.style = new CSSStyleDeclarationImpl(this);\n"
    "            this.style.cssText = cssPropertiesText;\n"
    "            this.type = CSSRule.FONT_FACE_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            return `@font-face { ${this.style.cssText} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSPageRule extends CSSRule {\n"
    "        constructor(selectorText = '', cssPropertiesText = '', sheet = null) {\n"
    "            super('', null, sheet);\n"
    "            this.selectorText = selectorText.trim();\n"
    "            this.style = new CSSStyleDeclarationImpl(this);\n"
    "            this.style.cssText = cssPropertiesText;\n"
    "            this.type = CSSRule.PAGE_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            const sel = this.selectorText ? ` ${this.selectorText}` : '';\n"
    "            return `@page${sel} { ${this.style.cssText} }`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSNamespaceRule extends CSSRule {\n"
    "        constructor(namespaceURI = '', prefix = '', sheet = null) {\n"
    "            super('', null, sheet);\n"
    "            this.namespaceURI = namespaceURI.trim();\n"
    "            this.prefix = prefix.trim();\n"
    "            this.type = CSSRule.NAMESPACE_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            const pref = this.prefix ? `${this.prefix} ` : '';\n"
    "            return `@namespace ${pref}url(\"${this.namespaceURI}\");`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSImportRule extends CSSRule {\n"
    "        constructor(href = '', media = 'all', sheet = null) {\n"
    "            super('', null, sheet);\n"
    "            this.href = href.trim();\n"
    "            this.media = { mediaText: media.trim(), length: 1, item: () => media.trim() };\n"
    "            this.styleSheet = null;\n"
    "            this.type = CSSRule.IMPORT_RULE;\n"
    "        }\n"
    "        get cssText() {\n"
    "            return `@import url(\"${this.href}\") ${this.media.mediaText};`;\n"
    "        }\n"
    "        set cssText(val) {\n"
    "            this._cssText = String(val);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    class CSSStyleSheet {\n"
    "        constructor(options = {}) {\n"
    "            this.ownerRule = null;\n"
    "            this.disabled = false;\n"
    "            this.href = options.href || null;\n"
    "            this.title = options.title || null;\n"
    "            this.type = 'text/css';\n"
    "            this.cssRules = new CSSRuleList();\n"
    "        }\n"
    "        get rules() {\n"
    "            return this.cssRules;\n"
    "        }\n"
    "        insertRule(ruleText, index = 0) {\n"
    "            ruleText = String(ruleText).trim();\n"
    "            if (index < 0 || index > this.cssRules.length) {\n"
    "                throw new DOMException(\"Failed to execute 'insertRule': The index provided is invalid.\", \"IndexSizeError\");\n"
    "            }\n"
    "            let rule;\n"
    "            if (ruleText.startsWith('@media')) {\n"
    "                const braceOpen = ruleText.indexOf('{');\n"
    "                const cond = ruleText.slice(6, braceOpen !== -1 ? braceOpen : undefined);\n"
    "                rule = new CSSMediaRule(cond, this);\n"
    "            } else if (ruleText.startsWith('@supports')) {\n"
    "                const braceOpen = ruleText.indexOf('{');\n"
    "                const cond = ruleText.slice(9, braceOpen !== -1 ? braceOpen : undefined);\n"
    "                rule = new CSSSupportsRule(cond, this);\n"
    "            } else if (ruleText.startsWith('@keyframes')) {\n"
    "                const braceOpen = ruleText.indexOf('{');\n"
    "                const name = ruleText.slice(10, braceOpen !== -1 ? braceOpen : undefined);\n"
    "                rule = new CSSKeyframesRule(name, this);\n"
    "            } else if (ruleText.startsWith('@font-face')) {\n"
    "                const braceOpen = ruleText.indexOf('{');\n"
    "                const braceClose = ruleText.lastIndexOf('}');\n"
    "                const props = (braceOpen !== -1 && braceClose !== -1) ? ruleText.slice(braceOpen + 1, braceClose) : '';\n"
    "                rule = new CSSFontFaceRule(props, this);\n"
    "            } else if (ruleText.startsWith('@import')) {\n"
    "                rule = new CSSImportRule(ruleText, 'all', this);\n"
    "            } else if (ruleText.startsWith('@page')) {\n"
    "                const braceOpen = ruleText.indexOf('{');\n"
    "                const braceClose = ruleText.lastIndexOf('}');\n"
    "                const sel = ruleText.slice(5, braceOpen !== -1 ? braceOpen : undefined);\n"
    "                const props = (braceOpen !== -1 && braceClose !== -1) ? ruleText.slice(braceOpen + 1, braceClose) : '';\n"
    "                rule = new CSSPageRule(sel, props, this);\n"
    "            } else if (ruleText.startsWith('@namespace')) {\n"
    "                rule = new CSSNamespaceRule(ruleText, '', this);\n"
    "            } else {\n"
    "                const braceOpen = ruleText.indexOf('{');\n"
    "                const braceClose = ruleText.lastIndexOf('}');\n"
    "                if (braceOpen === -1 || braceClose === -1) {\n"
    "                    throw new DOMException(\"Failed to execute 'insertRule': Syntax error in CSS rule.\", \"SyntaxError\");\n"
    "                }\n"
    "                const sel = ruleText.slice(0, braceOpen).trim();\n"
    "                const props = ruleText.slice(braceOpen + 1, braceClose).trim();\n"
    "                rule = new CSSStyleRule(sel, props, this);\n"
    "            }\n"
    "            this.cssRules.splice(index, 0, rule);\n"
    "            return index;\n"
    "        }\n"
    "        deleteRule(index) {\n"
    "            index = Number(index);\n"
    "            if (index < 0 || index >= this.cssRules.length) {\n"
    "                throw new DOMException(\"Failed to execute 'deleteRule': The index provided is invalid.\", \"IndexSizeError\");\n"
    "            }\n"
    "            this.cssRules.splice(index, 1);\n"
    "        }\n"
    "        replace(text) {\n"
    "            return Promise.resolve(this.replaceSync(text));\n"
    "        }\n"
    "        replaceSync(text) {\n"
    "            this.cssRules.length = 0;\n"
    "            this.insertRule(text, 0);\n"
    "            return this;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    global.CSSRule = CSSRule;\n"
    "    global.CSSStyleRule = CSSStyleRule;\n"
    "    global.CSSGroupingRule = CSSGroupingRule;\n"
    "    global.CSSMediaRule = CSSMediaRule;\n"
    "    global.CSSSupportsRule = CSSSupportsRule;\n"
    "    global.CSSKeyframeRule = CSSKeyframeRule;\n"
    "    global.CSSKeyframesRule = CSSKeyframesRule;\n"
    "    global.CSSFontFaceRule = CSSFontFaceRule;\n"
    "    global.CSSPageRule = CSSPageRule;\n"
    "    global.CSSNamespaceRule = CSSNamespaceRule;\n"
    "    global.CSSImportRule = CSSImportRule;\n"
    "    global.CSSRuleList = CSSRuleList;\n"
    "    global.CSSStyleSheet = CSSStyleSheet;\n"
    "})();\n";

#endif /* WISP_POLYFILL_CSSOM_H */
