static const char *forms_polyfill =
    "(function() { \n"
    "    'use strict'; \n"
    "    const global = globalThis; \n"
    " \n"
    "    class RadioNodeList extends Array { \n"
    "        constructor() { \n"
    "            super(); \n"
    "        } \n"
    " \n"
    "        get value() { \n"
    "            for (let i = 0; i < this.length; i++) { \n"
    "                const el = this[i]; \n"
    "                if (el && el.type === 'radio' && el.checked) { \n"
    "                    return el.value !== undefined ? el.value : 'on'; \n"
    "                } \n"
    "            } \n"
    "            return ''; \n"
    "        } \n"
    " \n"
    "        set value(val) { \n"
    "            val = String(val); \n"
    "            for (let i = 0; i < this.length; i++) { \n"
    "                const el = this[i]; \n"
    "                if (el && el.type === 'radio') { \n"
    "                    el.checked = (el.value === val); \n"
    "                } \n"
    "            } \n"
    "        } \n"
    "    } \n"
    " \n"
    "    class HTMLFormControlsCollection { \n"
    "        constructor(formElement) { \n"
    "            this._form = formElement; \n"
    "        } \n"
    " \n"
    "        _getControls() { \n"
    "            if (!this._form) return []; \n"
    "            const tags = ['input', 'button', 'select', 'textarea', 'fieldset', 'output', 'object']; \n"
    "            const controls = []; \n"
    "            for (let tag of tags) { \n"
    "                const list = this._form.getElementsByTagName(tag); \n"
    "                for (let i = 0; i < list.length; i++) { \n"
    "                    controls.push(list[i]); \n"
    "                } \n"
    "            } \n"
    "            // Sort by tree order \n"
    "            return controls.sort((a, b) => { \n"
    "                const pos = a.compareDocumentPosition(b); \n"
    "                return (pos & 0x02) ? 1 : -1; \n"
    "            }); \n"
    "        } \n"
    " \n"
    "        get length() { \n"
    "            return this._getControls().length; \n"
    "        } \n"
    " \n"
    "        item(index) { \n"
    "            const controls = this._getControls(); \n"
    "            return (index >= 0 && index < controls.length) ? controls[index] : null; \n"
    "        } \n"
    " \n"
    "        namedItem(name) { \n"
    "            if (!name) return null; \n"
    "            name = String(name); \n"
    "            const controls = this._getControls(); \n"
    "            const matched = []; \n"
    " \n"
    "            for (let ctrl of controls) { \n"
    "                const id = ctrl.getAttribute('id'); \n"
    "                const ctrlName = ctrl.getAttribute('name'); \n"
    "                if (ctrlName === name || id === name) { \n"
    "                    matched.push(ctrl); \n"
    "                } \n"
    "            } \n"
    " \n"
    "            if (matched.length === 0) return null; \n"
    "            if (matched.length === 1) return matched[0]; \n"
    " \n"
    "            const rnl = new RadioNodeList(); \n"
    "            for (let el of matched) rnl.push(el); \n"
    "            return rnl; \n"
    "        } \n"
    "    } \n"
    "\n"
    "    class HTMLOptionsCollectionImpl { \n"
    "        constructor(selectElement) { \n"
    "            this._select = selectElement; \n"
    "        } \n"
    " \n"
    "        get length() { \n"
    "            return this.options.length; \n"
    "        } \n"
    " \n"
    "        set length(val) { \n"
    "            val = Number(val) || 0; \n"
    "            const current = this.options; \n"
    "            if (val < current.length) { \n"
    "                for (let i = current.length - 1; i >= val; i--) { \n"
    "                    this._select.removeChild(current[i]); \n"
    "                } \n"
    "            } \n"
    "        } \n"
    " \n"
    "        get options() { \n"
    "            const list = []; \n"
    "            const ch = this._select.getElementsByTagName('option'); \n"
    "            for (let i = 0; i < ch.length; i++) list.push(ch[i]); \n"
    "            return list; \n"
    "        } \n"
    " \n"
    "        item(index) { \n"
    "            const opts = this.options; \n"
    "            return (index >= 0 && index < opts.length) ? opts[index] : null; \n"
    "        } \n"
    " \n"
    "        namedItem(name) { \n"
    "            name = String(name); \n"
    "            for (let opt of this.options) { \n"
    "                if (opt.getAttribute('name') === name || opt.getAttribute('id') === name) { \n"
    "                    return opt; \n"
    "                } \n"
    "            } \n"
    "            return null; \n"
    "        } \n"
    " \n"
    "        add(element, before = null) { \n"
    "            if (!(element instanceof global.HTMLElement)) { \n"
    "                throw new TypeError(\"Failed to execute 'add' on 'HTMLOptionsCollection': The element provided is not of type 'HTMLElement'.\"); \n"
    "            } \n"
    "            if (before === null || before === undefined) { \n"
    "                this._select.appendChild(element); \n"
    "            } else if (typeof before === 'number') { \n"
    "                const target = this.item(before); \n"
    "                if (target) this._select.insertBefore(element, target); \n"
    "                else this._select.appendChild(element); \n"
    "            } else if (before instanceof global.HTMLElement) { \n"
    "                this._select.insertBefore(element, before); \n"
    "            } \n"
    "        } \n"
    " \n"
    "        remove(index) { \n"
    "            const target = this.item(index); \n"
    "            if (target && target.parentNode) { \n"
    "                target.parentNode.removeChild(target); \n"
    "            } \n"
    "        } \n"
    " \n"
    "        get selectedIndex() { \n"
    "            const opts = this.options; \n"
    "            for (let i = 0; i < opts.length; i++) { \n"
    "                if (opts[i].selected) return i; \n"
    "            } \n"
    "            return opts.length > 0 ? 0 : -1; \n"
    "        } \n"
    " \n"
    "        set selectedIndex(idx) { \n"
    "            const opts = this.options; \n"
    "            for (let i = 0; i < opts.length; i++) { \n"
    "                opts[i].selected = (i === idx); \n"
    "            } \n"
    "        } \n"
    "    } \n"
    " \n"
    "    const HTMLOptionsCollection = new Proxy(function() {}, { \n"
    "        construct(target, args) { \n"
    "            const impl = new HTMLOptionsCollectionImpl(args[0]); \n"
    "            return new Proxy(impl, { \n"
    "                get(target, prop) { \n"
    "                    if (prop in target) return typeof target[prop] === 'function' ? target[prop].bind(target) : target[prop]; \n"
    "                    if (typeof prop === 'string' && !isNaN(prop)) return target.item(Number(prop)); \n"
    "                    return target.namedItem(prop); \n"
    "                }, \n"
    "                set(target, prop, value) { \n"
    "                    if (prop in target) { target[prop] = value; return true; } \n"
    "                    if (typeof prop === 'string' && !isNaN(prop)) { \n"
    "                        const index = Number(prop); \n"
    "                        const current = target.options; \n"
    "                        if (value === null || value === undefined) { target.remove(index); return true; } \n"
    "                        if (index < current.length) { \n"
    "                            target._select.replaceChild(value, current[index]); \n"
    "                        } else { \n"
    "                            target._select.appendChild(value); \n"
    "                        } \n"
    "                        return true; \n"
    "                    } \n"
    "                    return false; \n"
    "                } \n"
    "            }); \n"
    "        } \n"
    "    }); \n"
    " \n"
    "    class ValidityState { \n"
    "        constructor(element) { \n"
    "            this._el = element; \n"
    "        } \n"
    " \n"
    "        get valueMissing() { \n"
    "            const el = this._el; \n"
    "            if (!el.required || el.disabled) return false; \n"
    "            if (el.type === 'checkbox') return !el.checked; \n"
    "            if (el.type === 'radio') { \n"
    "                const form = el.form; \n"
    "                const name = el.name; \n"
    "                if (!name) return !el.checked; \n"
    "                const radios = (form ? form.elements.namedItem(name) : null) || [el]; \n"
    "                let anyChecked = false; \n"
    "                for (let i = 0; i < radios.length; i++) { \n"
    "                    if (radios[i].checked) { anyChecked = true; break; } \n"
    "                } \n"
    "                return !anyChecked; \n"
    "            } \n"
    "            return !el.value || el.value.trim() === ''; \n"
    "        } \n"
    " \n"
    "        get typeMismatch() { \n"
    "            const el = this._el; \n"
    "            const val = el.value || ''; \n"
    "            if (!val || el.disabled) return false; \n"
    "            if (el.type === 'email') { \n"
    "                return !/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test(val); \n"
    "            } \n"
    "            if (el.type === 'url') { \n"
    "                return !/^(?:https?|ftp):\\/\\/[^\\s/$.?#].[^\\s]*$/i.test(val); \n"
    "            } \n"
    "            return false; \n"
    "        } \n"
    " \n"
    "        get patternMismatch() { \n"
    "            const el = this._el; \n"
    "            const pattern = el.getAttribute('pattern'); \n"
    "            if (!pattern || !el.value || el.disabled) return false; \n"
    "            const regex = new RegExp(`^(?:${pattern})$`, 'u'); \n"
    "            return !regex.test(el.value); \n"
    "        } \n"
    " \n"
    "        get tooLong() { \n"
    "            const el = this._el; \n"
    "            const max = el.maxLength; \n"
    "            return (max >= 0 && el.value && el.value.length > max); \n"
    "        } \n"
    " \n"
    "        get tooShort() { \n"
    "            const el = this._el; \n"
    "            const min = el.minLength; \n"
    "            return (min >= 0 && el.value && el.value.length > 0 && el.value.length < min); \n"
    "        } \n"
    " \n"
    "        get rangeUnderflow() { \n"
    "            const el = this._el; \n"
    "            const min = parseFloat(el.min); \n"
    "            const val = parseFloat(el.value); \n"
    "            return (!isNaN(min) && !isNaN(val) && val < min); \n"
    "        } \n"
    " \n"
    "        get rangeOverflow() { \n"
    "            const el = this._el; \n"
    "            const max = parseFloat(el.max); \n"
    "            const val = parseFloat(el.value); \n"
    "            return (!isNaN(max) && !isNaN(val) && val > max); \n"
    "        } \n"
    " \n"
    "        get stepMismatch() { \n"
    "            const el = this._el; \n"
    "            const step = parseFloat(el.step); \n"
    "            const val = parseFloat(el.value); \n"
    "            const min = isNaN(parseFloat(el.min)) ? 0 : parseFloat(el.min); \n"
    "            if (isNaN(step) || step <= 0 || isNaN(val)) return false; \n"
    "            const diff = Math.abs(val - min); \n"
    "            const remainder = diff % step; \n"
    "            return (remainder > 0.0000001 && Math.abs(remainder - step) > 0.0000001); \n"
    "        } \n"
    " \n"
    "        get badInput() { \n"
    "            const el = this._el; \n"
    "            if (el.type === 'number' && el.value) { \n"
    "                return isNaN(Number(el.value)); \n"
    "            } \n"
    "            return false; \n"
    "        } \n"
    " \n"
    "        get customError() { \n"
    "            return !!(this._el._customValidity); \n"
    "        } \n"
    " \n"
    "        get valid() { \n"
    "            return !(this.valueMissing || this.typeMismatch || this.patternMismatch || \n"
    "                     this.tooLong || this.tooShort || this.rangeUnderflow || \n"
    "                     this.rangeOverflow || this.stepMismatch || this.badInput || this.customError); \n"
    "        } \n"
    "    } \n"
    " \n"
    "    function applyValidationInterface(proto) { \n"
    "        if (!proto) return; \n"
    " \n"
    "        Object.defineProperty(proto, 'validity', { \n"
    "            get() { \n"
    "                if (!this._validityState) this._validityState = new ValidityState(this); \n"
    "                return this._validityState; \n"
    "            }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        Object.defineProperty(proto, 'willValidate', { \n"
    "            get() { \n"
    "                return !(this.disabled || this.readOnly || this.type === 'hidden' || this.type === 'button' || this.type === 'reset'); \n"
    "            }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        Object.defineProperty(proto, 'validationMessage', { \n"
    "            get() { \n"
    "                if (!this.willValidate || this.validity.valid) return ''; \n"
    "                if (this._customValidity) return this._customValidity; \n"
    "                if (this.validity.valueMissing) return 'Please fill out this field.'; \n"
    "                if (this.validity.typeMismatch) return 'Please match the requested format.'; \n"
    "                if (this.validity.patternMismatch) return 'Please match the requested pattern.'; \n"
    "                if (this.validity.tooLong) return 'Input is too long.'; \n"
    "                if (this.validity.tooShort) return 'Input is too short.'; \n"
    "                if (this.validity.rangeUnderflow) return `Value must be greater than or equal to ${this.min}.`; \n"
    "                if (this.validity.rangeOverflow) return `Value must be less than or equal to ${this.max}.`; \n"
    "                if (this.validity.stepMismatch) return 'Please enter a valid step value.'; \n"
    "                if (this.validity.badInput) return 'Please enter a valid value.'; \n"
    "                return 'Invalid value.'; \n"
    "            }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        proto.setCustomValidity = function(message) { \n"
    "            this._customValidity = message ? String(message) : ''; \n"
    "        }; \n"
    " \n"
    "        proto.checkValidity = function() { \n"
    "            if (!this.willValidate || this.validity.valid) return true; \n"
    "            const evt = new CustomEvent('invalid', { bubbles: false, cancelable: true }); \n"
    "            this.dispatchEvent(evt); \n"
    "            return false; \n"
    "        }; \n"
    " \n"
    "        proto.reportValidity = function() { \n"
    "            return this.checkValidity(); \n"
    "        }; \n"
    "    } \n"
    " \n"
    "    if (global.HTMLInputElement && HTMLInputElement.prototype) applyValidationInterface(HTMLInputElement.prototype); \n"
    "    if (global.HTMLSelectElement && HTMLSelectElement.prototype) { \n"
    "        const proto = HTMLSelectElement.prototype; \n"
    " \n"
    "        applyValidationInterface(proto); \n"
    " \n"
    "        Object.defineProperty(proto, 'options', { \n"
    "            get() { \n"
    "                if (!this._optionsColl) { \n"
    "                    this._optionsColl = new HTMLOptionsCollection(this); \n"
    "                } \n"
    "                return this._optionsColl; \n"
    "            }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        Object.defineProperty(proto, 'selectedIndex', { \n"
    "            get() { return this.options.selectedIndex; }, \n"
    "            set(val) { this.options.selectedIndex = val; }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        Object.defineProperty(proto, 'value', { \n"
    "            get() { \n"
    "                const idx = this.selectedIndex; \n"
    "                const opt = this.options.item(idx); \n"
    "                return opt ? (opt.value !== undefined ? opt.value : opt.text) : ''; \n"
    "            }, \n"
    "            set(val) { \n"
    "                val = String(val); \n"
    "                const opts = this.options.options; \n"
    "                for (let opt of opts) { \n"
    "                    if (opt.value === val || opt.text === val) { \n"
    "                        opt.selected = true; \n"
    "                        return; \n"
    "                    } \n"
    "                } \n"
    "            }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    "    } \n"
    " \n"
    "    if (global.HTMLOptionElement && HTMLOptionElement.prototype) { \n"
    "        const proto = HTMLOptionElement.prototype; \n"
    " \n"
    "        Object.defineProperty(proto, 'text', { \n"
    "            get() { return this.textContent || ''; }, \n"
    "            set(val) { this.textContent = String(val); }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        Object.defineProperty(proto, 'value', { \n"
    "            get() { \n"
    "                return this.hasAttribute('value') ? this.getAttribute('value') : this.text; \n"
    "            }, \n"
    "            set(val) { this.setAttribute('value', String(val)); }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        Object.defineProperty(proto, 'selected', { \n"
    "            get() { return this._selected !== undefined ? this._selected : this.hasAttribute('selected'); }, \n"
    "            set(val) { this._selected = !!val; }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    "    } \n"
    " \n"
    "    if (global.HTMLTextAreaElement && HTMLTextAreaElement.prototype) applyValidationInterface(HTMLTextAreaElement.prototype); \n"
    "    if (global.HTMLButtonElement && HTMLButtonElement.prototype) applyValidationInterface(HTMLButtonElement.prototype); \n"
    " \n"
    "    if (global.HTMLFormElement && HTMLFormElement.prototype) { \n"
    "        Object.defineProperty(HTMLFormElement.prototype, 'elements', { \n"
    "            get() { \n"
    "                if (!this._elements) this._elements = new HTMLFormControlsCollection(this); \n"
    "                return this._elements; \n"
    "            }, \n"
    "            configurable: true, enumerable: true \n"
    "        }); \n"
    " \n"
    "        HTMLFormElement.prototype.checkValidity = function() { \n"
    "            let allValid = true; \n"
    "            const controls = this.elements._getControls(); \n"
    "            for (let ctrl of controls) { \n"
    "                if (ctrl.willValidate && !ctrl.checkValidity()) { \n"
    "                    allValid = false; \n"
    "                } \n"
    "            } \n"
    "            return allValid; \n"
    "        }; \n"
    " \n"
    "        HTMLFormElement.prototype.reportValidity = function() { \n"
    "            return this.checkValidity(); \n"
    "        }; \n"
    " \n"
    "        HTMLFormElement.prototype.reset = function() { \n"
    "            const controls = this.elements._getControls(); \n"
    "            for (let ctrl of controls) { \n"
    "                if (ctrl.type === 'checkbox' || ctrl.type === 'radio') { \n"
    "                    ctrl.checked = ctrl.defaultChecked; \n"
    "                } else if (ctrl.defaultValue !== undefined) { \n"
    "                    ctrl.value = ctrl.defaultValue; \n"
    "                } \n"
    "            } \n"
    "            this.dispatchEvent(new Event('reset', { bubbles: true, cancelable: true })); \n"
    "        }; \n"
    "    } \n"
    " \n"
    "    global.RadioNodeList = RadioNodeList; \n"
    "    global.HTMLFormControlsCollection = HTMLFormControlsCollection; \n"
    "    global.HTMLOptionsCollection = HTMLOptionsCollection; \n"
    "    global.Option = function(text = '', value = '', defaultSelected = false, selected = false) { \n"
    "        const opt = document.createElement('option'); \n"
    "        if (text) opt.text = String(text); \n"
    "        if (value) opt.value = String(value); \n"
    "        if (defaultSelected) opt.setAttribute('selected', ''); \n"
    "        opt.selected = !!selected; \n"
    "        return opt; \n"
    "    }; \n"
    "    global.ValidityState = ValidityState; \n"
    "})();\n"
;
