/*
 * Generated by qjs_binding_generator.py - DO NOT EDIT MANUALLY
 * Copyright 2026 Neosurf Contributors
 */

#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include "quickjs.h"
#include <wisp/utils/log.h>
#include "utils/libdom.h"
#include "dom_bridge.h"

/* Forward declarations for Text */
static JSValue js_text_splitText(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv);
static JSValue js_text_wholeText_get(JSContext *ctx, JSValueConst this_val);

JSClassID qjs_text_class_id;

static void js_text_finalizer(JSRuntime *rt, JSValue val)
{
    QJSNodePrivate *priv = JS_GetOpaque(val, qjs_text_class_id);
    if (priv) {
        qjs_bridge_remove_node(rt, (dom_node *)priv->node, priv->ctx);
        if (priv->is_dom_node && priv->node) dom_node_unref((dom_node *)priv->node);
        free(priv);
    }
}

static JSClassDef js_text_class = {
    "Text",
    .finalizer = js_text_finalizer,
};

static const JSCFunctionListEntry js_text_proto_funcs[] = {
    JS_CFUNC_DEF("splitText", 1, js_text_splitText),
    JS_CGETSET_DEF("wholeText", js_text_wholeText_get, NULL),
};

/* Implementation stubs */

static JSValue js_text_splitText(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    QJSNodePrivate *priv = JS_GetOpaque(this_val, qjs_text_class_id);
    if (!priv || !priv->node || argc < 1) return JS_EXCEPTION;

    uint32_t offset = 0;
    JS_ToUint32(ctx, &offset, argv[0]);

    struct dom_text *result = NULL;
    dom_exception exc = dom_text_split_text((dom_text *)priv->node, offset, &result);

    if (exc != DOM_NO_ERR || result == NULL) return JS_ThrowInternalError(ctx, "dom_text_split_text failed");

    JSValue val = qjs_wrap_node(ctx, (dom_node *)result);
    dom_node_unref((dom_node *)result);
    return val;
}

static JSValue js_text_wholeText_get(JSContext *ctx, JSValueConst this_val)
{
    QJSNodePrivate *priv = JS_GetOpaque(this_val, qjs_text_class_id);
    if (!priv || !priv->node) return JS_NULL;

    dom_string *text = NULL;
    dom_exception exc = dom_text_get_whole_text((dom_text *)priv->node, &text);

    if (exc != DOM_NO_ERR || text == NULL) return JS_NULL;

    JSValue val = JS_NewStringLen(ctx, dom_string_data(text), dom_string_byte_length(text));
    dom_string_unref(text);
    return val;
}

int qjs_init_text(JSContext *ctx)
{
    JSRuntime *rt = JS_GetRuntime(ctx);
    if (qjs_text_class_id == 0) {
        JS_NewClassID(rt, &qjs_text_class_id);
    }
    if (!JS_IsRegisteredClass(rt, qjs_text_class_id)) {
        if (JS_NewClass(rt, qjs_text_class_id, &js_text_class) < 0)
            return -1;
    }

    JSValue proto = JS_NewObject(ctx);
    JS_SetPropertyFunctionList(ctx, proto, js_text_proto_funcs, sizeof(js_text_proto_funcs) / sizeof(js_text_proto_funcs[0]));

    JS_SetClassProto(ctx, qjs_text_class_id, proto);

    /* For Window, we often want to attach everything to the global object */
    if (strcmp("Text", "Window") == 0) {
        JSValue global_obj = JS_GetGlobalObject(ctx);
        JS_SetPropertyFunctionList(ctx, global_obj, js_text_proto_funcs, sizeof(js_text_proto_funcs) / sizeof(js_text_proto_funcs[0]));
        JS_FreeValue(ctx, global_obj);
    }

    return 0;
}

/* Utility to wrap a native object */
JSValue qjs_new_text(JSContext *ctx, void *node, bool is_dom_node)
{
    JSValue obj = JS_NewObjectClass(ctx, qjs_text_class_id);
    QJSNodePrivate *priv = calloc(1, sizeof(QJSNodePrivate));
    if (!priv) return JS_ThrowOutOfMemory(ctx);
    priv->node = node; priv->ctx = ctx; priv->is_dom_node = is_dom_node;
    if (is_dom_node && node) dom_node_ref((dom_node *)node);
    JS_SetOpaque(obj, priv); return obj;
}
