//  de facto set of features for console object
// https://developer.mozilla.org/en-US/docs/DOM/console
// http://msdn.microsoft.com/en-us/library/dd565625%28v=vs.85%29.aspx#consolelogging
// 31st October
// Yay for non-standard standards

interface Console {
  void debug(DOMString msg, any... subst);
  void dir(JSValue object);
  void error(DOMString msg, any... subst);
  void group();
  void groupCollapsed();
  void groupEnd();
  void info(DOMString msg, any... subst);
  void log(DOMString msg, any... subst);
  void time(DOMString timerName);
  void timeEnd(DOMString timerName);
  void trace();
  void warn(DOMString msg, any... subst);
};

partial interface Window {
  readonly attribute Console console;
};