// Retrieved from https://drafts.csswg.org/cssom-1/
// Wed Nov  4 15:39:43 GMT 2015
// Removed duplicate IDL from appendix


[ArrayClass]interface MediaList  {
  [TreatNullAs=EmptyString] stringifier  attribute DOMString mediaText;
  readonly attribute unsigned long length;
  getter DOMString? item(unsigned long index );
  void appendMedium(DOMString medium );
  void deleteMedium(DOMString medium );
};

interface StyleSheet  {
  readonly attribute DOMString type;
  readonly attribute DOMString? href;
  readonly attribute (Element or ProcessingInstruction)? ownerNode;
  readonly attribute StyleSheet? parentStyleSheet;
  readonly attribute DOMString? title;
  [SameObject, PutForwards=mediaText] readonly attribute MediaList media;
  attribute boolean disabled;
};



[ArrayClass]interface StyleSheetList  {
  getter StyleSheet? item(unsigned long index );
  readonly attribute unsigned long length;
};

partial interface Document {
  [SameObject] readonly attribute StyleSheetList styleSheets;
  attribute DOMString? selectedStyleSheetSet;
  readonly attribute DOMString? lastStyleSheetSet;
  readonly attribute DOMString? preferredStyleSheetSet;
  readonly attribute DOMString[] styleSheetSets;
  void enableStyleSheetsForSet(DOMString? name );
};

[NoInterfaceObject]interface LinkStyle  {
  readonly attribute StyleSheet? sheet;
};

ProcessingInstruction implements LinkStyle;























[NoInterfaceObject]interface ElementCSSInlineStyle  {
  [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};

HTMLElement implements ElementCSSInlineStyle;

SVGElement implements ElementCSSInlineStyle;

partial interface Window {
  [NewObject] CSSStyleDeclaration getComputedStyle(Element elt , optional DOMString? pseudoElt );
};

[NoInterfaceObject]interface GetStyleUtils  {
  [SameObject] readonly attribute CSSStyleDeclaration cascadedStyle;
  [SameObject] readonly attribute CSSStyleDeclaration defaultStyle;
  [SameObject] readonly attribute CSSStyleDeclaration rawComputedStyle;
  [SameObject] readonly attribute CSSStyleDeclaration usedStyle;
};

partial interface Element {
  PseudoElement? pseudo(DOMString pseudoElt );
};

Element implements GetStyleUtils;

interface PseudoElement  {
};

PseudoElement implements GetStyleUtils;

interface CSS  {
  static DOMString escape(DOMString ident );
};
