// Retrieved from http://www.w3.org/TR/DOM-Parsing/
// Wed Nov  4 15:39:43 GMT 2015
// Manually extracted IDL

[Constructor]
interface XMLSerializer {
  DOMString serializeToString (Node root);
};

partial interface Element {
  [TreatNullAs=EmptyString]
    attribute DOMString innerHTML;
};

partial interface Range {
  [NewObject]
    DocumentFragment createContextualFragment (DOMString fragment);
};
