# ----------------------------------------------------------------------------
# BeOS-specific options
# ----------------------------------------------------------------------------

# Where to install the wisp binary
WISP_BEOS_BIN := /boot/apps/wisp/

# Where to search for Wisp's resources. Standard Haiku apps use
# ~/config/settings/wisp, but we still support WISPRES.
# It must have a trailing /
WISP_BEOS_RESOURCES := /boot/apps/wisp/res/

# Enable Wisp's use of libsvgtiny for displaying SVGs
# Valid options: YES, NO, AUTO
WISP_USE_NSSVG := YES

# Enable Wisp's use of librosprite for displaying RISC OS Sprites
# Valid options: YES, NO, AUTO
WISP_USE_ROSPRITE := AUTO

# Enable Wisp's use of libharu for PDF export.
# Valid options: YES, NO
WISP_USE_HARU_PDF := NO

# Force using glibc internal iconv implementation instead of external libiconv
# Valid options: YES, NO
WISP_USE_LIBICONV_PLUG := NO

# Optimisation levels
CFLAGS += -pipe -O2
