#!/usr/bin/env python3
"""
QuickJS-ng Binding Generator for Wisp browser.
Generates boilerplate and implementation stubs separately.
"""

import os
import sys
import argparse
from datetime import datetime

try:
    import widlparser
except ImportError:
    print("Error: widlparser not installed. Install via: pip install widlparser")
    sys.exit(1)

class QuickJSBindingGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.parser = widlparser.Parser()
        self.interfaces = {}
        self.mixins = {}

    def parse_idl(self, idl_path: str):
        with open(idl_path, 'r') as f:
            self.parser.parse(f.read())
        
        for construct in self.parser.constructs:
            if isinstance(construct, widlparser.constructs.Interface):
                self.interfaces[construct.name] = construct
            elif isinstance(construct, widlparser.constructs.ImplementsStatement):
                if construct.name not in self.mixins:
                    self.mixins[construct.name] = []
                self.mixins[construct.name].append(construct.implements)

    def _get_members(self, interface):
        name = interface.name
        attributes = []
        operations = []
        constants = []
        to_process = [interface]
        if name in self.mixins:
            for mixin_name in self.mixins[name]:
                mixin = self.interfaces.get(mixin_name)
                if mixin: to_process.append(mixin)
        seen_members = set()
        for current in to_process:
            for member in current.members:
                m = getattr(member, 'member', None)
                if not m or member.name in seen_members: continue
                seen_members.add(member.name)
                if isinstance(m, widlparser.productions.Attribute):
                    attr_str = str(m.attribute)
                    attributes.append({'name': member.name, 'readonly': 'readonly' in attr_str, 'type': str(m.idl_type)})
                elif isinstance(m, widlparser.productions.Operation):
                    if member.name: operations.append({'name': member.name, 'args': m.arguments})
                elif isinstance(m, widlparser.constructs.Const):
                    constants.append({'name': member.name, 'value': str(m.value), 'type': str(m.idl_type)})
        return attributes, operations, constants

    def generate_inc(self, interface_name: str) -> str:
        interface = self.interfaces.get(interface_name)
        if not interface: raise ValueError(f"Interface '{interface_name}' not found")
        name = interface.name
        lower_name = name.lower()
        attributes, operations, constants = self._get_members(interface)
        
        code = f"/* Generated by qjs_binding_generator.py - DO NOT EDIT MANUALLY */\n\n"
        # Forward declarations
        for op in operations:
            code += f"static JSValue js_{lower_name}_{op['name']}(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv);\n"
        for attr in attributes:
            code += f"static JSValue js_{lower_name}_{attr['name']}_get(JSContext *ctx, JSValueConst this_val);\n"
            if not attr['readonly']:
                code += f"static JSValue js_{lower_name}_{attr['name']}_set(JSContext *ctx, JSValueConst this_val, JSValueConst val);\n"
        
        code += f"\nstatic const JSCFunctionListEntry js_{lower_name}_proto_funcs[] = {{\n"
        for op in operations:
            code += f"    JS_CFUNC_DEF(\"{op['name']}\", {len(op['args'])}, js_{lower_name}_{op['name']}),\n"
        for attr in attributes:
            if attr['readonly']:
                code += f"    JS_CGETSET_DEF(\"{attr['name']}\", js_{lower_name}_{attr['name']}_get, NULL),\n"
            else:
                code += f"    JS_CGETSET_DEF(\"{attr['name']}\", js_{lower_name}_{attr['name']}_get, js_{lower_name}_{attr['name']}_set),\n"
        for const in constants:
            code += f"    JS_PROP_INT32_DEF(\"{const['name']}\", {const['value']}, JS_PROP_CONFIGURABLE),\n"
        code += "};\n\n"
        
        code += f"static JSClassDef js_{lower_name}_class = {{\n    \"{name}\",\n    .finalizer = js_{lower_name}_finalizer,\n}};\n"
        return code

    def generate_stubs(self, interface_name: str) -> str:
        interface = self.interfaces.get(interface_name)
        name = interface.name
        lower_name = name.lower()
        attributes, operations, constants = self._get_members(interface)
        year = datetime.now().year
        
        code = f"/* Implementation for {name} */\n"
        code += f"#include <stdlib.h>\n#include <string.h>\n#include <stdbool.h>\n#include \"quickjs.h\"\n"
        code += f"#include \"dom_bridge.h\"\n#include <wisp/utils/log.h>\n#include \"utils/libdom.h\"\n\n"
        code += f"#include \"{lower_name}.inc\"\n\n"
        
        code += f"static void js_{lower_name}_finalizer(JSRuntime *rt, JSValue val)\n{{\n"
        code += f"    QJSNodePrivate *priv = JS_GetOpaque(val, qjs_{lower_name}_class_id);\n"
        code += f"    if (priv) {{\n        if (priv->is_dom_node && priv->node) dom_node_unref((dom_node *)priv->node);\n        free(priv);\n    }}\n}}\n\n"
        
        for op in operations:
            code += f"static JSValue js_{lower_name}_{op['name']}(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)\n{{\n"
            code += f"    NSLOG(wisp, DEBUG, \"{name}.{op['name']}() called (stub)\");\n    return JS_UNDEFINED;\n}}\n\n"
        for attr in attributes:
            code += f"static JSValue js_{lower_name}_{attr['name']}_get(JSContext *ctx, JSValueConst this_val)\n{{\n"
            code += f"    NSLOG(wisp, DEBUG, \"{name}.{attr['name']} getter called (stub)\");\n    return JS_UNDEFINED;\n}}\n\n"
            if not attr['readonly']:
                code += f"static JSValue js_{lower_name}_{attr['name']}_set(JSContext *ctx, JSValueConst this_val, JSValueConst val)\n{{\n"
                code += f"    NSLOG(wisp, DEBUG, \"{name}.{attr['name']} setter called (stub)\");\n    return JS_UNDEFINED;\n}}\n\n"
        
        code += f"int qjs_init_{lower_name}(JSContext *ctx)\n{{\n"
        code += f"    JSRuntime *rt = JS_GetRuntime(ctx);\n    if (qjs_{lower_name}_class_id == 0) JS_NewClassID(rt, &qjs_{lower_name}_class_id);\n"
        code += f"    if (!JS_IsRegisteredClass(rt, qjs_{lower_name}_class_id)) JS_NewClass(rt, qjs_{lower_name}_class_id, &js_{lower_name}_class);\n"
        code += f"    JSValue proto = JS_NewObject(ctx);\n    JS_SetPropertyFunctionList(ctx, proto, js_{lower_name}_proto_funcs, sizeof(js_{lower_name}_proto_funcs) / sizeof(js_{lower_name}_proto_funcs[0]));\n"
        code += f"    JS_SetClassProto(ctx, qjs_{lower_name}_class_id, proto);\n    return 0;\n}}\n\n"

        code += f"JSValue qjs_new_{lower_name}(JSContext *ctx, void *node, bool is_dom_node)\n{{\n"
        code += f"    JSValue obj = JS_NewObjectClass(ctx, qjs_{lower_name}_class_id);\n"
        code += f"    QJSNodePrivate *priv = calloc(1, sizeof(QJSNodePrivate));\n    if (!priv) return JS_ThrowOutOfMemory(ctx);\n"
        code += f"    priv->node = node; priv->is_dom_node = is_dom_node;\n    if (is_dom_node && node) dom_node_ref((dom_node *)node);\n"
        code += f"    JS_SetOpaque(obj, priv); return obj;\n}}\n"
        return code

def main():
    parser = argparse.ArgumentParser(description='Generate QuickJS-ng C bindings from WebIDL files')
    parser.add_argument('idl_file', help='Path to the IDL file')
    parser.add_argument('-o', '--output', required=True, help='Output directory')
    parser.add_argument('--interface', help='Specific interface to generate')
    args = parser.parse_args()
    os.makedirs(args.output, exist_ok=True)
    generator = QuickJSBindingGenerator(args.output)
    generator.parse_idl(args.idl_file)
    interfaces = [args.interface] if args.interface else list(generator.interfaces.keys())
    for name in interfaces:
        lower = name.lower()
        with open(os.path.join(args.output, f"{lower}.inc"), "w") as f: f.write(generator.generate_inc(name))
        c_path = os.path.join(args.output, f"{lower}.c")
        if not os.path.exists(c_path):
            with open(c_path, "w") as f: f.write(generator.generate_stubs(name))
        print(f"Generated: {name}")

if __name__ == '__main__':
    main()
