/*
 * This file is part of LibCSS.
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2008 John-Mark Bell <jmb@netsurf-browser.org>
 *
 * CSS parser string identifiers (enum + string table)
 * ====================================================
 * Auto-generated property names are included first via propstrings_enum.inc.
 * Manual entries (tokens, keywords, colours) follow.
 *
 * To add CSS properties, update properties.toml — the generator handles the rest.
 * To add keywords/tokens, add them to the manual section below.
 */

#ifndef css_css__parse_propstrings_h_
#define css_css__parse_propstrings_h_

#include "utils/css_utils.h"

enum {
    /* ═══════════════════════════════════════════════════════════════════
     * AUTO-GENERATED property names (from property_generator.py)
     * These MUST come first — CSS_PROP_* enum values are numeric indexes.
     * ═══════════════════════════════════════════════════════════════════ */
    FIRST_PROP,

/* AUTO-GENERATED - Property enum values from property_generator.py */
#include "propstrings_enum.inc"


    /* ═══════════════════════════════════════════════════════════════════
     * MANUAL entries below — tokens, keywords, colours, etc.
     * The generator auto-creates SMAP entries for all identifiers here.
     *
     * RANGE MARKERS: The following names are skipped by the generator
     * (they share slots with real entries or mark array bounds):
     *   FIRST_PROP, LAST_PROP, FIRST_COLOUR, LAST_COLOUR,
     *   FIRST_SYSTEMCOLOUR, LAST_SYSTEMCOLOUR,
     *   FIRST_DEPRECATEDCOLOUR, LAST_DEPRECATEDCOLOUR, LAST_KNOWN
     * If you add new range markers, update PROPSTRINGS_RANGE_MARKERS
     * in property_generator.py too!
     *
     * WARNING: Names like FIRST_CHILD, LAST_CHILD, FIRST_LINE etc.
     * are REAL CSS identifiers, NOT range markers — do not skip them.
     * ═══════════════════════════════════════════════════════════════════ */

    /* Universal selector */
    UNIVERSAL,

    /* Common tokens */
    COLON,
    COMMA,
    SEMICOLON,
    OPEN_CURLY_BRACE,
    CLOSE_CURLY_BRACE,
    ZERO_VALUE,

    /* At-rules */
    CHARSET,
    LIBCSS_IMPORT,
    MEDIA,
    NAMESPACE,
    FONT_FACE,
    PAGE,

    /* Media types */
    AURAL,
    BRAILLE,
    EMBOSSED,
    HANDHELD,
    PRINT,
    PROJECTION,
    SCREEN,
    SPEECH,
    TTY,
    TV,
    ALL,

    /* Pseudo classes */
    FIRST_CHILD,
    LINK,
    VISITED,
    HOVER,
    ACTIVE,
    FOCUS,
    LANG,
    /* LEFT, RIGHT, -- already in properties */
    FIRST,
    ROOT,
    NTH_CHILD,
    NTH_LAST_CHILD,
    NTH_OF_TYPE,
    NTH_LAST_OF_TYPE,
    LAST_CHILD,
    FIRST_OF_TYPE,
    LAST_OF_TYPE,
    ONLY_CHILD,
    ONLY_OF_TYPE,
    EMPTY,
    TARGET,
    ENABLED,
    DISABLED,
    CHECKED,
    NOT,

    /* Pseudo elements */
    FIRST_LINE,
    FIRST_LETTER,
    BEFORE,
    AFTER,

    /* Other keywords */
    INHERIT,
    UNSET,
    IMPORTANT,
    NONE,
    BOTH,
    FIXED,
    SCROLL,
    TRANSPARENT,
    NO_REPEAT,
    REPEAT_X,
    REPEAT_Y,
    REPEAT,
    HIDDEN,
    DOTTED,
    DASHED,
    SOLID,
    LIBCSS_DOUBLE,
    GROOVE,
    RIDGE,
    INSET,
    OUTSET,
    THIN,
    MEDIUM,
    THICK,
    COLLAPSE,
    SEPARATE,
    AUTO,
    LTR,
    RTL,
    INLINE,
    BLOCK,
    LIST_ITEM,
    RUN_IN,
    INLINE_BLOCK,
    TABLE,
    INLINE_TABLE,
    TABLE_ROW_GROUP,
    TABLE_HEADER_GROUP,
    TABLE_FOOTER_GROUP,
    TABLE_ROW,
    TABLE_COLUMN_GROUP,
    TABLE_COLUMN,
    TABLE_CELL,
    TABLE_CAPTION,
    BELOW,
    LEVEL,
    ABOVE,
    HIGHER,
    LOWER,
    SHOW,
    HIDE,
    XX_SMALL,
    X_SMALL,
    SMALL,
    LARGE,
    X_LARGE,
    XX_LARGE,
    LARGER,
    SMALLER,
    NORMAL,
    ITALIC,
    OBLIQUE,
    SMALL_CAPS,
    BOLD,
    BOLDER,
    LIGHTER,
    INSIDE,
    OUTSIDE,
    DISC,
    CIRCLE,
    SQUARE,
    DECIMAL,
    DECIMAL_LEADING_ZERO,
    LOWER_ROMAN,
    UPPER_ROMAN,
    LOWER_GREEK,
    LOWER_LATIN,
    UPPER_LATIN,
    ARMENIAN,
    GEORGIAN,
    LOWER_ALPHA,
    UPPER_ALPHA,
    BINARY,
    OCTAL,
    LOWER_HEXADECIMAL,
    UPPER_HEXADECIMAL,
    ARABIC_INDIC,
    LOWER_ARMENIAN,
    UPPER_ARMENIAN,
    BENGALI,
    CAMBODIAN,
    KHMER,
    CJK_DECIMAL,
    DEVANAGARI,
    GUJARATI,
    GURMUKHI,
    HEBREW,
    KANNADA,
    LAO,
    MALAYALAM,
    MONGOLIAN,
    MYANMAR,
    ORIYA,
    PERSIAN,
    TAMIL,
    TELUGU,
    THAI,
    TIBETAN,
    CJK_EARTHLY_BRANCH,
    CJK_HEAVENLY_STEM,
    HIAGANA,
    HIAGANA_IROHA,
    KATAKANA,
    KATAKANA_IROHA,
    JAPANESE_INFORMAL,
    JAPANESE_FORMAL,
    KOREAN_HANGUL_FORMAL,
    KOREAN_HANJA_INFORMAL,
    KOREAN_HANJA_FORMAL,
    INVERT,
    VISIBLE,
    ALWAYS,
    AVOID,
    X_LOW,
    LOW,
    HIGH,
    X_HIGH,
    LIBCSS_STATIC,
    RELATIVE,
    ABSOLUTE,
    ONCE,
    DIGITS,
    CONTINUOUS,
    CODE,
    SPELL_OUT,
    X_SLOW,
    SLOW,
    FAST,
    X_FAST,
    FASTER,
    SLOWER,
    CENTER,
    JUSTIFY,
    CAPITALIZE,
    UPPERCASE,
    LOWERCASE,
    EMBED,
    BIDI_OVERRIDE,
    BASELINE,
    SUB,
    SUPER,
    TEXT_TOP,
    MIDDLE,
    TEXT_BOTTOM,
    SILENT,
    X_SOFT,
    SOFT,
    LOUD,
    X_LOUD,
    PRE,
    NOWRAP,
    PRE_WRAP,
    PRE_LINE,
    LEFTWARDS,
    RIGHTWARDS,
    LEFT_SIDE,
    FAR_LEFT,
    CENTER_LEFT,
    CENTER_RIGHT,
    FAR_RIGHT,
    RIGHT_SIDE,
    BEHIND,
    RECT,
    OPEN_QUOTE,
    CLOSE_QUOTE,
    NO_OPEN_QUOTE,
    NO_CLOSE_QUOTE,
    ATTR,
    COUNTER,
    COUNTERS,
    CROSSHAIR,
    DEFAULT,
    POINTER,
    MOVE,
    E_RESIZE,
    NE_RESIZE,
    NW_RESIZE,
    N_RESIZE,
    SE_RESIZE,
    SW_RESIZE,
    S_RESIZE,
    W_RESIZE,
    LIBCSS_TEXT,
    WAIT,
    HELP,
    PROGRESS,
    SERIF,
    SANS_SERIF,
    CURSIVE,
    FANTASY,
    MONOSPACE,
    MALE,
    FEMALE,
    CHILD,
    MIX,
    UNDERLINE,
    OVERLINE,
    LINE_THROUGH,
    BLINK,
    RGB,
    RGBA,
    HSL,
    HSLA,
    HWB,
    LIBCSS_LEFT,
    LIBCSS_CENTER,
    LIBCSS_RIGHT,
    CURRENTCOLOR,
    ODD,
    EVEN,
    OF, /* CSS Selectors Level 4: :nth-child(An+B of <selector>) */
    SRC,
    LOCAL,
    INITIAL,
    REVERT,
    FORMAT,
    WOFF,
    TRUETYPE,
    OPENTYPE,
    EMBEDDED_OPENTYPE,
    SVG,
    COLUMN,
    AVOID_PAGE,
    AVOID_COLUMN,
    BALANCE,
    HORIZONTAL_TB,
    VERTICAL_RL,
    VERTICAL_LR,
    CONTENT_BOX,
    BORDER_BOX,
    STRETCH,
    INLINE_FLEX,
    FLEX_START,
    FLEX_END,
    SPACE_BETWEEN,
    SPACE_AROUND,
    SPACE_EVENLY,
    ROW,
    ROW_REVERSE,
    COLUMN_REVERSE,
    WRAP_STRING,
    WRAP_REVERSE,
    AND,
    OR,
    ONLY,
    INFINITE,
    GRID,
    INLINE_GRID,
    STICKY,
    CALC,
    LAB,
    LCH,
    OKLAB,
    OKLCH,
    /* CSS Grid keywords */
    DENSE,
    ROW_DENSE,
    COLUMN_DENSE,
    /* CSS Grid track sizing functions and keywords */
    MINMAX,
    MIN_CONTENT,
    MAX_CONTENT,
    FIT_CONTENT,
    SPAN,
    /* Object-fit keywords */
    /* Note: FILL is auto-generated as a property name (same string "fill") */
    CONTAIN,
    COVER,
    SCALE_DOWN,
    /* CSS transform function keywords */
    TRANSLATE,
    TRANSLATEX,
    TRANSLATEY,
    SCALE,
    SCALEX,
    SCALEY,
    ROTATE,
    /* CSS gradient functions */
    LINEAR_GRADIENT,
    RADIAL_GRADIENT,
    /* Named colours */
    FIRST_COLOUR,

    ALICEBLUE = FIRST_COLOUR,
    ANTIQUEWHITE,
    AQUA,
    AQUAMARINE,
    AZURE,
    BEIGE,
    BISQUE,
    BLACK,
    BLANCHEDALMOND,
    BLUE,
    BLUEVIOLET,
    BROWN,
    BURLYWOOD,
    CADETBLUE,
    CHARTREUSE,
    CHOCOLATE,
    CORAL,
    CORNFLOWERBLUE,
    CORNSILK,
    CRIMSON,
    CYAN,
    DARKBLUE,
    DARKCYAN,
    DARKGOLDENROD,
    DARKGRAY,
    DARKGREEN,
    DARKGREY,
    DARKKHAKI,
    DARKMAGENTA,
    DARKOLIVEGREEN,
    DARKORANGE,
    DARKORCHID,
    DARKRED,
    DARKSALMON,
    DARKSEAGREEN,
    DARKSLATEBLUE,
    DARKSLATEGRAY,
    DARKSLATEGREY,
    DARKTURQUOISE,
    DARKVIOLET,
    DEEPPINK,
    DEEPSKYBLUE,
    DIMGRAY,
    DIMGREY,
    DODGERBLUE,
    FELDSPAR,
    FIREBRICK,
    FLORALWHITE,
    FORESTGREEN,
    FUCHSIA,
    GAINSBORO,
    GHOSTWHITE,
    GOLD,
    GOLDENROD,
    GRAY,
    GREEN,
    GREENYELLOW,
    GREY,
    HONEYDEW,
    HOTPINK,
    INDIANRED,
    INDIGO,
    IVORY,
    KHAKI,
    LAVENDER,
    LAVENDERBLUSH,
    LAWNGREEN,
    LEMONCHIFFON,
    LIGHTBLUE,
    LIGHTCORAL,
    LIGHTCYAN,
    LIGHTGOLDENRODYELLOW,
    LIGHTGRAY,
    LIGHTGREEN,
    LIGHTGREY,
    LIGHTPINK,
    LIGHTSALMON,
    LIGHTSEAGREEN,
    LIGHTSKYBLUE,
    LIGHTSLATEBLUE,
    LIGHTSLATEGRAY,
    LIGHTSLATEGREY,
    LIGHTSTEELBLUE,
    LIGHTYELLOW,
    LIME,
    LIMEGREEN,
    LINEN,
    MAGENTA,
    MAROON,
    MEDIUMAQUAMARINE,
    MEDIUMBLUE,
    MEDIUMORCHID,
    MEDIUMPURPLE,
    MEDIUMSEAGREEN,
    MEDIUMSLATEBLUE,
    MEDIUMSPRINGGREEN,
    MEDIUMTURQUOISE,
    MEDIUMVIOLETRED,
    MIDNIGHTBLUE,
    MINTCREAM,
    MISTYROSE,
    MOCCASIN,
    NAVAJOWHITE,
    NAVY,
    OLDLACE,
    OLIVE,
    OLIVEDRAB,
    ORANGE,
    ORANGERED,
    ORCHID,
    PALEGOLDENROD,
    PALEGREEN,
    PALETURQUOISE,
    PALEVIOLETRED,
    PAPAYAWHIP,
    PEACHPUFF,
    PERU,
    PINK,
    PLUM,
    POWDERBLUE,
    PURPLE,
    RED,
    ROSYBROWN,
    ROYALBLUE,
    SADDLEBROWN,
    SALMON,
    SANDYBROWN,
    SEAGREEN,
    SEASHELL,
    SIENNA,
    SILVER,
    SKYBLUE,
    SLATEBLUE,
    SLATEGRAY,
    SLATEGREY,
    SNOW,
    SPRINGGREEN,
    STEELBLUE,
    TAN,
    TEAL,
    THISTLE,
    TOMATO,
    TURQUOISE,
    VIOLET,
    VIOLETRED,
    WHEAT,
    WHITE,
    WHITESMOKE,
    YELLOW,
    YELLOWGREEN,
    REBECCAPURPLE,

    LAST_COLOUR = REBECCAPURPLE,

    /* CSS Color Module Level 4 system colors */
    FIRST_SYSTEMCOLOUR,

    ACCENTCOLOR = FIRST_SYSTEMCOLOUR,
    ACCENTCOLORTEXT,
    ACTIVETEXT,
    BUTTONBORDER,
    BUTTONFACE,
    BUTTONTEXT,
    CANVAS,
    CANVASTEXT,
    FIELD,
    FIELDTEXT,
    GRAYTEXT,
    HIGHLIGHT,
    HIGHLIGHTTEXT,
    LINKTEXT,
    MARK,
    MARKTEXT,
    SELECTEDITEM,
    SELECTEDITEMTEXT,
    VISITEDTEXT,

    LAST_SYSTEMCOLOUR = VISITEDTEXT,

    /* CSS Color Module Level 4 deprecated system colors */
    FIRST_DEPRECATEDCOLOUR,

    ACTIVEBORDER = FIRST_DEPRECATEDCOLOUR,
    ACTIVECAPTION,
    APPWORKSPACE,
    DCBACKGROUND,
    BUTTONHIGHLIGHT,
    BUTTONSHADOW,
    CAPTIONTEXT,
    INACTIVEBORDER,
    INACTIVECAPTION,
    INACTIVECAPTIONTEXT,
    INFOBACKGROUND,
    INFOTEXT,
    MENU,
    MENUTEXT,
    SCROLLBAR,
    THREEDDARKSHADOW,
    THREEDFACE,
    THREEDHIGHLIGHT,
    THREEDLIGHTSHADOW,
    THREEDSHADOW,
    WINDOW,
    WINDOWFRAME,
    WINDOWTEXT,

    LAST_DEPRECATEDCOLOUR = WINDOWTEXT,

    LAST_KNOWN
};

css_error css__propstrings_get(lwc_string ***strings);
void css__propstrings_unref(void);

#endif
