/*
 * This file is part of LibCSS.
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2008 John-Mark Bell <jmb@netsurf-browser.org>
 *
 * CSS parser string mappings
 * ==========================
 * Auto-generated property SMAP entries come first (propstrings_strings.inc),
 * followed by auto-generated keyword SMAP entries (keywords_strings.inc).
 *
 * Both are generated by property_generator.py from properties.toml and
 * propstrings.h respectively. Do NOT edit them manually.
 */

#include "parse/propstrings.h"
#include "stylesheet.h"

#include <assert.h>

/** build string map entry with a string constant */
#define SMAP(s) {s, (sizeof((s)) - 1) /* -1 for '\0' */}


typedef struct stringmap_entry {
    const char *data;
    size_t len;
} stringmap_entry;

typedef struct css__propstrings_ctx {
    uint32_t count;
    lwc_string *strings[LAST_KNOWN];
} css__propstrings_ctx;

static css__propstrings_ctx css__propstrings;

/* Must be synchronised with enum in propstrings.h */
const stringmap_entry stringmap[LAST_KNOWN] = {
/* AUTO-GENERATED - Property string entries from property_generator.py */
#include "propstrings_strings.inc"

/* AUTO-GENERATED - Keyword string entries from property_generator.py */
#include "keywords_strings.inc"
};


/**
 * Obtain pointer to interned propstring list
 *
 * \param sheet	    Returns pointer to propstring table
 * \return CSS_OK on success,
 *	   CSS_NOMEM on memory exhaustion
 *
 * The propstring list is generated with the first call to this function and
 * destroyed when it has no more users.  Call css__propstrings_unref() when
 * finished with the propstring list.
 */
css_error css__propstrings_get(lwc_string ***strings)
{
    if (css__propstrings.count > 0) {
        css__propstrings.count++;
    } else {
        int i;
        lwc_error lerror;

        /* Intern all known strings */
        for (i = 0; i < LAST_KNOWN; i++) {
            lerror = lwc_intern_string(stringmap[i].data, stringmap[i].len, &css__propstrings.strings[i]);

            if (lerror != lwc_error_ok)
                return CSS_NOMEM;
        }
        css__propstrings.count++;
    }

    *strings = css__propstrings.strings;

    return CSS_OK;
}

/**
 * Reduce reference count for propstring list by one.
 *
 * When count hits zero, the list is destroyed.
 */
void css__propstrings_unref(void)
{
    css__propstrings.count--;

    if (css__propstrings.count == 0) {
        int i;

        for (i = 0; i < LAST_KNOWN; i++)
            lwc_string_unref(css__propstrings.strings[i]);
    }
}
